### ISSUE TITLE
default build system

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#10615]
Shall we talk about build system? :)

We always had our custom build system until recently, with acr + makefiles + scripts all around. More often than not, makefiles hides a lot of complexity just to create libraries. We also provide some scripts in `./sys` to ease the installation and building of radare2, which make even more opaque the building/installation process.

Almost all projects out there just use a very simple and standard way to build their software and that's what people expect to see. People expect to see:
```
autoreconf
./configure
make
```
or
```
mkdir build; cd build
cmake ..
make
```
or (as in our case)
```
meson build
cd build; ninja
```

No opaque scripts here and there. No custom shell/python scripts to "ease" the process.
My proposal is that we finally switch away from the custom build system which we have used until now and we only focus on meson. And even with meson, people should be able to just use the "usual" meson commands, no hand-crafted python scripts that do part of the work and let some others to meson.

The doc should be updated to suggest the meson compilation.
The build process should be simplified as much as possibile to reduce the use of external sh/python scripts to "configure" meson.
External libraries should be optionally treated as external, and their code should not just be included in the repository to "avoid dependencies".

**Comment by XVilka** [comment]
.configure;make just works, using it for installation in Gentoo, OpenSUSE,
Fedora.

**Comment by ret2libc** [comment]
@XVilka yes, but it's not standard build system (our configure doesn't have all the options of a "regular" configure) and it's hard to understand what our build system does because there are so many makefiles which just do tons of stuff.

More than a makefile, most of them seems like just bash scripting.

Just to compare... Makefile:
```
BIN=radare2
BINDEPS=r_core r_parse r_search r_cons r_config
BINDEPS+=r_bin r_debug r_anal r_reg r_bp r_io r_fs
BINDEPS+=r_lang r_asm r_syscall r_hash
BINDEPS+=r_magic r_socket r_flag r_egg r_crypto r_util

include ../../config-user.mk

FOOD_LIBS=$(addprefix ../../libr/,$(subst r_,,$(BINDEPS)))
SIGN_LIBS=$(addsuffix /libr_*.dylib,$(FOOD_LIBS))

include ../rules.mk

include ../../libr/socket/deps.mk
include ../../libr/magic/deps.mk
include ../../shlr/zip/deps.mk
include ../../shlr/gdb/deps.mk
include ../../shlr/java/deps.mk
include ../../shlr/bochs/deps.mk
include ../../shlr/qnx/deps.mk
include ../../shlr/ar/deps.mk
```
meson.build:
```
executable('radare2', 'radare2.c',
  include_directories: [platform_inc],
  link_with: [
    r_util, r_socket, r_core, r_io, r_magic, r_fs, r_bin, r_flag, r_cons,
    r_asm, r_debug, r_config, r_bp, r_reg, r_syscall, r_anal, r_parse, r_egg,
    r_search, r_hash, r_crypto,
  ],
  install: true,
  implicit_include_directories: false
)
```

And I didn't even pasted all the `*.mk` files.

**Comment by xarkes** [comment]
I think one could argue that meson + ninja requires you to download python and the meson module, as well as the ninja build system, while the `./configure; make` alternative requires nothing but build-essentials.
I prefer to use meson because as ret2libc said I think it's cleaner and there's no hacky scripts.

**Comment by ret2libc** [comment]
Yeah that's the only *drawback*. But let's be honest, installing meson/ninja is just an `apt-get/dnf/yum/pacman` away. And if one compiles from source code, he already needs to have things installed.

**Comment by radare** [comment]
> On 4 Jul 2018, at 10:07, Riccardo Schirone <notifications@github.com> wrote:
> 
> @XVilka <https://github.com/XVilka> yes, but it's not standard build system (our configure doesn't have all the options of a "regular" configure) and it's hard to understand what our build system does because there are so many makefiles which just do tons of stuff.
> 
which one do you miss? many distros are packaging software using acr and i got 0 complains in many years. f something is missing just add it. autotools is bloatware and acr is easy to maintain and generates clean sh.

> More than a makefile, most of them seems like just bash scripting.
> 
> Just to compare... Makefile:
> 
> BIN=radare2
> BINDEPS=r_core r_parse r_search r_cons r_config
> BINDEPS+=r_bin r_debug r_anal r_reg r_bp r_io r_fs
> BINDEPS+=r_lang r_asm r_syscall r_hash
> BINDEPS+=r_magic r_socket r_flag r_egg r_crypto r_util
> 
> include ../../config-user.mk
> 
> FOOD_LIBS=$(addprefix ../../libr/,$(subst r_,,$(BINDEPS)))
> SIGN_LIBS=$(addsuffix /libr_*.dylib,$(FOOD_LIBS))
> 
> include ../rules.mk
> 
> include ../../libr/socket/deps.mk
> include ../../libr/magic/deps.mk
> include ../../shlr/zip/deps.mk
> include ../../shlr/gdb/deps.mk
> include ../../shlr/java/deps.mk
> include ../../shlr/bochs/deps.mk
> include ../../shlr/qnx/deps.mk
> include ../../shlr/ar/deps.mk
> meson.build:
> 
> executable('radare2', 'radare2.c',
>   include_directories: [platform_inc],
>   link_with: [
>     r_util, r_socket, r_core, r_io, r_magic, r_fs, r_bin, r_flag, r_cons,
>     r_asm, r_debug, r_config, r_bp, r_reg, r_syscall, r_anal, r_parse, r_egg,
>     r_search, r_hash, r_crypto,
>   ],
>   install: true,
>   implicit_include_directories: false
> )

thats ugly python which requires a 50MB virtual machine that is slow and boring. make is included in all unix systems and python is not, same goes for ninja, so i dont want people to depend on shit that will be probably deprecated in 3years because someone wrote a better system. the history of build systems is tricky. and make is a defacto standard. so no plans to kill it, we can improve the makefiles.

also the current meson system have a bunch of limitations that acr is able to manage, so iimho meson is not yet ready to replace acr, because at the end, the meson system end sup depending on some .bat and .sh files to do stuff, without saying that it depends on python, which is a crappy language that crashes in half of my machines. and by experience ALL the things written in python are eventually replaced by something better some years later… think about mercurial, django, gyp or jhbuild as few examples. otherwise they would be written in a decent language.

**Comment by ret2libc** [comment]
@radare `also the current meson system have a bunch of limitations that acr is able to manage` examples?
I agree the current meson build in r2 is not super ready, but I'm saying that we should focus on a standard system (e.g. meson) more than on a custom one.

`acr` is so good, it's included in all unix systems, it's well maintained by many people, tested and used by many projects and... autotools is bloatware, used by few people and in few projects. Right? :) And python is not used, there are no good python projects and it's usually hard to install python/meson/ninja/whatever on a system.

**Comment by xarkes** [comment]
A big advantage of meson is that it runs on all platforms whereas configure/Makefile cannot be used with standard Microsoft tools for example.

**Comment by radare** [comment]
make is stable, works everywhere and its not a pain to maintain it, its just the meson thing which is the moving target that 

> On 4 Jul 2018, at 12:01, Riccardo Schirone <notifications@github.com> wrote:
> 
> @radare <https://github.com/radare> also the current meson system have a bunch of limitations that acr is able to manage examples?
> I agree the current meson build in r2 is not super ready, but I'm saying that we should focus on a standard system (e.g. meson) more than on a custom one.
> 
> acr is so good, it's included in all unix systems, it's well maintained by many people, tested and used by many projects and... autotools is bloatware, used by few people and in few projects. Right? :) And python is not used, there are no good python projects and it's usually hard to install python/meson/ninja/whatever on a system.
> 
> 
im not saying autotools is not used, its the completely way around, but acr is ZILLIONS of times easier to maintain and use than autotools, and acr doesnt replaces autotools. only autoconf, and automake is a huge mess that is hard to fix when you found a bug.. right now its pretty stable, but when i started r2, autotools was having A LOT of problems in solaris and hpux for example. and yes, i was using those systems frequently, so wriitng makefiles by hand is way easier than maintaining and expecting people to use the specific version of automake/aclocal whatever gnu crap.. thats why distros pack 2-3 versions of autotools .. because there are drawbacks in all of them. acr just works, and yep, there may be about 10 projects using it, but all their users are happy from what they told me, so if you have an issue with it just report it.

imho there’s no reason to kill acr/make. and meson is used a lot in gnome nowadays, but some years ago it was jhbuild, autotools and they also used another python-based build system, so its something totally unstable. even more when almost nobody knows how to write good meson things, and also because meson depends on python to work, not just to run, but also to be extended to do stuff. imho thats a really bad design issue because it ties you to a language. and personally i have a lot of complains on this language. but i respect it and i appreciate its goodies, like building faster than make because the less of forks and the support for windows. but there’s nothing perfect

**Comment by ret2libc** [comment]
I'm not saying to kill acr/make. But to shift our focus on a more declarative and more structured system which clearly defines what is a library, what is an executable, what they depend on, etc. Things that many *modern* build systems have in common. Maybe not now, but if we start moving to a better system, in 6 months/1 year/whatever, we'll have an easier build system, less messy. 

From what it concerns me I'd be okay even with `cmake`, which anyway has a lot of features provided by meson too. I'm for meson only because there was already some effort to use it in r2 and it already works. The simplicity in writing meson build files is evident IMHO.

**Comment by XVilka** [comment]
I have to say that Python is ubiquitous now, so this part is not an issue anymore. And HP UX is dead nowadays, along with Sun and many others. Even AIX is struggling to survive. On the other hand I have to agree that meson is still too novel. They mentioned though, that its syntax is not tied up to Python and there were an ideas to reimplement it in another language.

**Comment by MaskRay** [comment]
+1 for meson as the default.

> make is included in all unix systems and python is not

There are also a lot of variants to `make`. `radare2/Makefile` is GNU make only. Note on FreeBSD `gmake` is not pre-installed.

**Comment by unixfreaxjp** [comment]
I am a UNIX system engineer & FreeBSD user along with my other job descriptions, and a happy user of radare since 2007, I still remember like yesterday when I firstly `/usr/ports/devel/radare2/ && make install  radare`. May I add several opinions: 

I am not against technogy or improvement, so don't get me wrong. But, as a *"server guy"*, I am on _portability, stability, and compatibility_. r2 is proven runs well in many NIX platforms and that is the great achievement of the software, and that's why people like me started to use it in the first place, and believe me, the sysadmins don't peeky on software easily. So please consider not to drop current r2 quality on compatibility/portability. From my *userland* point of view itself, as long as the compilation can be done as smooth as we have now with the `sys/install.sh`, it will not face problem, therefore, as if in _meson_, the etc softwares (python..is a serious words, and some modules needed too for meson), that are needed to be installed.. have to be handled properly, either with _install script_ or _r2pm_ or a _clear howto manual_

For this implementation, _the tests and more tests_ is also a must, and maybe the current Travis config has to be added/improved beforehand to handle big changes as per discussed or future changes too. That's it. 

Several notes:

> Note on FreeBSD gmake is not pre-installed.

Correct!
```asm
$ cc --version
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.4
Thread model: posix
```

>  And HP UX is dead nowadays, along with Sun and many others. Even AIX is struggling to survive. 

@XVilka I must say **No** to you, w/ respect intact, I will be very careful studying facts beforehand before making that statement. [HP UX is not dead](https://www.hpe.com/global/softwarereleases/releases-media2/HPEredesign/latest/AR1805/Support_Matrix.pdf), and I am as sysadmin in important servers still run by it.  Sun Solaris is dead, BUT [Oracle Solaris is still running](https://docs.oracle.com/cd/E37838_01/html/E60974/index.html), and AIX (btw current version is AIX 7.1 TL4) [won't die that easily](http://www-01.ibm.com/support/docview.wss?uid=isg3T1012517) since that is the originality of IBM OS and many governments related system in the world are still depending on it.

**Comment by unixfreaxjp** [comment]
I am a UNIX system engineer & FreeBSD user along with my other job descriptions, and a happy user of radare since 2007, I still remember like yesterday when I firstly `/usr/ports/devel/radare2/ && make install  radare`. May I add several opinions: 

I am not against technogy or improvement, so don't get me wrong. But, as a *"server guy"*, I am on _portability, stability, and compatibility_. r2 is proven runs well in many NIX platforms and that is the great achievement of the software, and that's why people like me started to use it in the first place, and believe me, the sysadmins don't peeky on software easily. So please consider not to drop current r2 quality on compatibility/portability. From my *userland* point of view itself, as long as the compilation can be done as smooth as we have now with the `sys/install.sh`, it will not face problem, therefore, as if in _meson_, the etc softwares (python..is a serious words, and some modules needed too for meson), that are needed to be installed.. have to be handled properly, either with _install script_ or _r2pm_ or a _clear howto manual_

For this implementation, _the tests and more tests_ is also a must, and maybe the current Travis config has to be added/improved beforehand to handle big changes as per discussed or future changes too. That's it. 

Several notes:

> Note on FreeBSD gmake is not pre-installed.

Correct!
```asm
$ cc --version
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.4
Thread model: posix
```

>  And HP UX is dead nowadays, along with Sun and many others. Even AIX is struggling to survive. 

@XVilka I must say **No** to you, w/ respect intact, I will be very careful studying facts beforehand before making that statement. [HP UX is not dead](https://www.hpe.com/global/softwarereleases/releases-media2/HPEredesign/latest/AR1805/Support_Matrix.pdf), and I am as sysadmin in [important servers still run by it](http://3000newswire.blogs.com/.a/6a00d83452e85869e201bb085d9d2c970d-popup).  Sun Solaris is dead, BUT [Oracle Solaris is still running](https://docs.oracle.com/cd/E37838_01/html/E60974/index.html) also they seems [don't intend to get dead soon too](https://upload.wikimedia.org/wikipedia/en/timeline/f7553b81ea538a3eaee47310c452ee93.png) :) , and AIX (btw current version is AIX 7.1 TL4/5.. and has roadmap like to 2022, fyi) [won't die that easily](http://www-01.ibm.com/support/docview.wss?uid=isg3T1012517) since that is the originality of IBM OS and many governments related system in the world are still depending on it.

**Comment by radare** [comment]
Can we close this issue? I think it's pretty clear that we want to keep make and meson, there are enough systems covered and enough developers willing to maintain both systems. I don't see a reason to replace one with the other or to include any other build system right now.
