### ISSUE TITLE
Radare2 install into PATH Windows

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#10657]
When installing r2 for Windows, I've noticed that the binary dir doesn't get added to the user's PATH. Also, it ends up in a strange place that people wouldn't look for it.

Recommend either/both installing r2 into Program Files, and adding the bin directory to the user's %PATH% so that the user can just "radare2.exe" to run it.

EDIT: Looks like it __is__ being added to the user's path, but my Windows installs never seem to honor the user's PATH variable, they only look at the system PATH variable. Perhaps give an option to allow installing into the System PATH variable? I.e.: "Install for all users" type prompt.

**Comment by xarkes** [comment]
If I remember correctly, you would have to logout and login again for the user %PATH% variable to take effect.

**Comment by bannsec** [comment]
I've done that. The problem is that the user's PATH variable isn't actually populating when i open a cmd.exe. If i `echo %PATH%`, i see the System's PATH var, and none from the user's. Not sure why, but if i add the radare2 bin path to the system's PATH var, then it ends up in cmd.exe's environment.

**Comment by Maijin** [comment]
You can contribute to the windows installer script, it's plain text 👍

**Comment by riverar** [comment]
`Program Files` is not a per-user location. `%LocalAppData%` is the correct location for installation. I've also verified the `PATH` is set up correctly. Not seeing a bug here, recommend closure.

@bannsec Suspect your environment variables are screwed up. Typically happens when someone sticks unnecessary `"` quotes or `;` semi colons in there.

**Comment by justinlangley3** [comment]
This is a somewhat old issue, but I discovered it in a Google search when my radare2 installation was not working. It turns out I was doing everything correctly, except one thing. As per, @xarkes comment, after a system restart it began working.

My steps to get radare2 working and PATH set correctly:
* This is assuming a Windows 10 install
1) Download the radare2.zip from http://radare.mikelloc.com/get/3.6.0/radare2-msvc_64-3.6.0.zip
2) Unzip the archive
3) Travel into the unzipped folder until you see the folders bin, include, lib, and share
4) Put these folders into their own folder aptly named radare2
5) Place the radare2 folder from the previous step in the C:\ folder, or a directory of your choice
6) Go to Control Panel -> System & Security -> System -> Advanced System Settings -> Environment Variables
7) Select the PATH variable and click EDIT
8) Add the location of the "radare2\bin" folder (for this guide it would be "C:\radare2\bin")
9) Save the edits and restart your machine
10) Discard any un-needed files leftover in your downloads folder (the radare2 zip, and extracted files)

Now you can access radare2 from cmd.exe using either radare2.exe or simply radare2

**Comment by bannsec** [comment]
I'll be honest, i don't bother installing via the package from radare2 directly anymore. It's always been a PITA. If I'm using r2 on Windows these days I just use chocolatey to install it correctly.

**Comment by riverar** [comment]
@justinlangley3 Restarting Windows is not required. You only need to restart any processes that need to inherit the new environmental changes (e.g. cmd.exe) if any. Don't really see an issue here, this is normal Windows behavior. Correct me if I missed something here.

**Comment by Maijin** [comment]
Then issue is closed
