### ISSUE TITLE
Capstone - switch to master branch

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10805]
Due to https://github.com/aquynh/capstone/issues/1096#issuecomment-407057696

**Comment by radare** [comment]
Kk

**Comment by ret2libc** [comment]
I'm working on it. BTW, I'm trying to upstream the patches we have for capstone. Unless @radare shows me actual reproducers for those, the only ones that are needed/can be upstreamed I think are:
1. fix-x86-16.patch
2. fix-m68k-oob.patch
3. fix-underflow-tms.patch

the others:
1. sstream-null: there are few cases where you need to just "return NULL"... If there are users of that function that pass a NULL value, they should be fixed, not this function. I think we don't need it. And if we do, this is probably not the right fix.
2. sparc-crash: the only use case of getRegisterName seems to check if the value is a register and the function is not exported by libcapstone, so... not necessary IMHO, again.
3. capstone-calloc: this patch is simply wrong. Apart from the malloc/calloc replacements (which could make sense), the realloc handling is just plain wrong. And that means only one thing: this PR is not necessary, and if it is, let's show a reproducer and fix it the proper way

**Comment by radare** [comment]
> On 23 Jul 2018, at 20:22, Riccardo Schirone <notifications@github.com> wrote:
> 
> I'm working on it. BTW, I'm trying to upstream the patches we have for capstone. Unless @radare shows me actual reproducers for those, the only ones that are needed/can be upstreamed I think are:
> 
> fix-x86-16.patch
> fix-m68k-oob.patch
> fix-underflow-tms.patch
> the others:
> 
> sstream-null: there are few cases where you need to just "return NULL"... If there are users of that function that pass a NULL value, they should be fixed, not this function. I think we don't need it. And if we do, this is probably not the right fix.

Thats up to capstone to decide. Imho it makes the api more solid. Use coverity to find out those offended callers

> sparc-crash: the only use case of getRegisterName seems to check if the value is a register and the function is not exported by libcapstone, so... not necessary IMHO, again.

Ok then. This means it was fixed in capstone after my quickfix. It was easier to fix this in one place than on each caller. And the compiler may be smart enough to remove unnecessary boilerplate and boundary checks if not necessary. Its 2018. And code must be maintainable and not dirty with tricky checks here and there but its ok for me to drop this patch 
> capstone-calloc: this patch is simply wrong. Apart from the malloc/calloc replacements (which could make sense), the realloc handling is just plain wrong. And that means only one thing: this PR is not necessary, and if it is, let's show a reproducer and fix it the proper way

See asan in travis and coverity. It was another quick fix instead of being field picky on every single caller to ensure the fields were initialized. It just makes the code easier to maintain. And calloc is not that slow compared to malloc to justify filling few fields with 0 instead of the whole struct at once. Also. Modern cpus may do calloc faster than malloc+some00s. But again. Its 2018 :p

**Comment by ret2libc** [comment]
> See asan in travis and coverity. It was another quick fix instead of being field picky on every single caller to ensure the fields were initialized. It just makes the code easier to maintain. And calloc is not that slow compared to malloc to justify filling few fields with 0 instead of the whole struct at once. Also. Modern cpus may do calloc faster than malloc+some00s. But again. Its 2018 :p

As said, this patch is actually wrong. It was writing 0 out of bounds... Which is bad.

>  > sstream-null: there are few cases where you need to just "return NULL"... If there are users of that function that pass a NULL value, they should be fixed, not this function. I think we don't need it. And if we do, this is probably not the right fix.
>
> Thats up to capstone to decide. Imho it makes the api more solid. Use coverity to find out those offended callers

I know we have a different view on this. But I do believe that it does not make the API more solid. SStream is used internally apparently, and if it receives NULL from somebody, it probably means that "somebody" is calling it with the wrong parameters and there's something else which is wrong. Returning NULL in those cases just hides the real root cause.

**Comment by radare** [comment]
Ok if its internal. But modern compilers are able to get rid of such runtime checks by using generic-like techniques. Not with -O0, and thats an unnecessary check. So ok to get rid if u want. It was a quick fix to avoid having to spend time fixing all the callers one by one everytime someone changed capstone. Aka Lazyfix
