### ISSUE TITLE
Unintended sign-extension for 32b PPC to 64b

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#10885]
[Apparently]( https://twitter.com/marcan42/status/1024677435000803328 ), as reported by @marcan, radare2 is sign-extending 32-bit PowerPC addresses to 64 bits, thus breaking all xrefs on targets in the upper half of the address space.

**Comment by radare** [comment]
This is a bug in capstone3. r2 uses capstone from git because v3 is 4 year old.

Please build r2 from git or use the Cutter Appimage build.

We can do an ugly workaround to fix the behaviour of the anal.ppc plugin with capstone3, but this is not the only problem fixed in capstone-v4, like many missing instructions, bad decodings, etc.

**Comment by Maijin** [comment]
@xarkes means we probably need a new release soon ;)
