### ISSUE TITLE
[meson] Shared capstone git repo for different build directories

### ISSUE THREAD

**Issue by MaskRay** [radare/radare2#10935]
`shlr/meson.build:6`

`  capstone_path = join_paths(meson.current_build_dir(), 'capstone')`

capstone is cloned to each build directory. It may be worthwhile to share the git repo for different build directories (I have three build directories: `build` `release` `asan`)

I sometimes mess up the build directory and `rm -r release` and re-execute `meson . release` with appropriate options. If there is something better that I can try?

**Comment by Maijin** [comment]
@ret2libc

**Comment by ret2libc** [comment]
That's something I did short while ago. I realize it's not ideal in some cases... but I did that because capstone is patched and I wanted to be able to test different versions of capstone easily.

We could add a meson option to reuse the `capstone` directory in the source directory (instead of getting it from git).

Just using the source directory, though, you may end up with a branch/commit of r2 that is supposed to use a particular branch/commit of capstone, but because of the cached `shlr/capstone` directory it doesn't.

What do you think?

**Comment by MaskRay** [comment]
A meson option to reuse the `capstone` repository should be great!

**Comment by ret2libc** [comment]
Yep, makes sense. I can work on it.

**Comment by pelijah** [comment]
Ping

**Comment by ret2libc** [comment]
@pelijah it’s already there. Look at meson.options . I’m closing this, if it doesn’t work as expected please feel free to reopen it.
