### ISSUE TITLE
esil mixes register name styles

### ISSUE THREAD

**Issue by jacobrosenthal** [radare/radare2#10980]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macos (modern ie 64bit)
| File format of the file you reverse (mandatory)      | elf
| Architecture/bits of the file (mandatory)            | x86
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 18984 @ darwin-x86-64 git.2.7.0-276-g319e20cea commit: 319e20cea731a033ad339d686e1413730c9da90b build: 2018-08-06__20:25:48

I would expect radare to maintain register naming styles but its mixing in edi rdi, eax rax, etc leading to a lot of noise
```
[0x010578a9]> s 0x01057929
[0x01057929]> pdf
/ (fcn) sym.runtime.closefd 23
|   sym.runtime.closefd (int arg_8h, int arg_10h);
|           ; arg int arg_8h @ rsp+0x8
|           ; arg int arg_10h @ rsp+0x10
|           ; CALL XREF from sym.runtime.getRandomData (0x1028e30)
|           0x01057920      8b7c2408       mov edi, dword [arg_8h]     ; [0x8:4]=-1 ; 8 ; edi=0xffffffff ; rdi=0xffffffff
|           0x01057924      b806000002     mov eax, 0x2000006          ; eax=0x2000006 ; rax=0x2000006
|           ;-- hit0_3:
|           0x01057929      0f05           syscall                     ; 33554438 = close (0xffffffff)
|       ,=< 0x0105792b      7305           jae 0x1057932               ; unlikely
|       |   0x0105792d      b8ffffffff     mov eax, 0xffffffff         ; -1 ; eax=0xffffffff ; rax=0xffffffff
|       `-> 0x01057932      89442410       mov dword [arg_10h], eax
\           0x01057936      c3             ret                         ; rip=0xffffffffffffffff ; rsp=0xffffffff0683eb46
[0x01057929]> 
```

**Comment by NotSoOld** [comment]
It has nothing to do with esil, and you probably have some option for noisy comments enabled.

**Comment by jacobrosenthal** [comment]
Or the code is shit like the last few times I tried to point out problems. Whys it always gotta be hostile with you folks.

I clearly have `asm.emu=1;` on. Why is it duplicate printing `eax=0x2000006` and `rax=0x2000006` when the registers in the code are using eax Thats pointless inappropriate noise.

**Comment by Maijin** [comment]
@NotSoOld there are clearly bug with ESIL in the paste, but there are also bug with anal too, also you don't need to comment every issue if it brings nothing to the resolution.

@jacobrosenthal please don't take everything as an offense btw, many people are non english native speaker and are trying to help the best they can, this often result in unwanted rudeness because of straight speaking.

**Comment by jacobrosenthal** [comment]
@Maijin Fair enough. Apologies @NotSoOld

**Comment by NotSoOld** [comment]
OK, I made some interesting research through debugging. Machine is 64-bit.
- When debugging 32-bit binary, everything is OK.
- When debugging 64-bit binary, if there are operations with 64-bit registers, ESIL prints only r** reg values, which is correct, If there is operation with 32-bit reg (like 'mov eax,0'), ESIL will print both eax and rax values.

I then would like to answer your question:


> Why is it duplicate printing eax=0x2000006 and rax=0x2000006 when the registers in the code are using eax


Because of the specific how 32 bits of 64-bit register are treated (used) in the machine. eax is not only a lower part of rax; if you do, for example, eax = 0, it also sets rax to 0. I googled it, please take a look: https://stackoverflow.com/questions/25455447/x86-64-registers-rax-eax-ax-al-overwriting-full-register-contents
- So, how it applies to ESIL?
Well, if you will do the following:
```
ae -1,rax,=
ae 0,eax,=
ar
```
You will see that rax is now 0xffffffff00000000, which isn't correct for how processors really work (see link above). That's why in the code, when there is 64-bit operation with 32-bit register, ESIL _silently_ adds operation at the end which is ',0xffffffff,name_of_64-bit_reg,&='. So, your 'mov eax,0' in ESIL syntax turns into '0,eax,=' and then into '0,eax,=,0xffffffff,rax,&=' which will truly set eax to 0.
- But why two outputs?
Because each '0,eax,=' and '0xffffffff,rax,&=' will produce its own output (result). First will be 'eax=0', and second will be 'rax=0'.
- What to do:
After inspecting the code, I can tell that it cannot be fixed very easily. Execution goes as follows: opcode is processed and esil string is created; ',0xffffffff,%s,&=' is added to esil string; function for printing is assigned; all esil string is processed and results are printed, so at this step there is no signinficant difference between operations which results should be printed, and operations which results should be suppressed.
- P.S. Maybe you can just treat these double messages as reminder that you encounter 32-bit regs in 64-bit program. :smiley_cat: Otherwise @Maijin we need a huge refactor, maybe adding some parameters into structure which is passed through that code.
- P.P.S. I suppose it becomes a kind of regression after someone realized that we need to change higher part of 64-bit r** registers when doing something with their lower part (as mentioned in the link), so, then regs were corrected correctly, but double messages appeared.

**Comment by radare** [comment]
modifying eax in esil doesnt implies changing the higher part of the register, so if it sets to rax it works as expected, otherwise opcodes like movabs and others that extend the higher bit to the rest and such wont work

**Comment by radare** [comment]
do you have specific instructions that fail this way? because i think thats a problem in the use of esil instead of esil itself

**Comment by NotSoOld** [comment]
Whoops, I see it doesn't work properly. In your paste:
was: `mov edi, dword [arg_8h]     ; [0x8:4]=-1 ; 8 ; edi=0xffffffff ; rdi=0xffffffff`
now: `mov edi, dword [arg_8h]     ; [0x8:4]=-1 ; 8 ; rdi=0x0` _(must be 0xffffffff)_
Can you please try to change line 746 in cmd_debug.c
`esilprintf (op, "%s,%s,=", src, dst64);`
to this
`esilprintf (op, "0xffffffff,%s,&,%s,=", src, dst64);`
and print paste?

> though radare disassembly still references registers by e 

Maybe it's because opcodes in such lines mean that according operations are on 32-bit registers. Or another bug \(o_o)/

**Comment by jacobrosenthal** [comment]
Happily
```
/ (fcn) sym.runtime.closefd 23
|   sym.runtime.closefd (int arg_8h, int arg_10h);
|           ; arg int arg_8h @ rsp+0x8
|           ; arg int arg_10h @ rsp+0x10
|           ; CALL XREF from sym.runtime.getRandomData (0x1028e30)
|           0x01057920      8b7c2408       mov edi, dword [arg_8h]     ; [0x8:4]=-1 ; 8 ; rdi=0x0
|           0x01057924      b806000002     mov eax, 0x2000006          ; rax=0x2000006
|           0x01057929      0f05           syscall                     ; 33554438 = close (0x00000000)
|       ,=< 0x0105792b      7305           jae 0x1057932               ; rip=0x1057932 -> 0x10244489 ; likely
|       |   0x0105792d      b8ffffffff     mov eax, 0xffffffff         ; -1 ; rax=0xffffffff
|       `-> 0x01057932      89442410       mov dword [arg_10h], eax
\           0x01057936      c3             ret                         ; rip=0x0 ; rsp=0x178008

```

**Comment by NotSoOld** [comment]
Still not working properly...
Well, maybe someone can review that situation. There is something with operating on [ ] links, as I guess.

**Comment by jacobrosenthal** [comment]
For what its worth this is perfectly boring golang binary but uploaded on this issue if you wanted to see yourself https://github.com/radare/radare2/issues/10978

**Comment by NotSoOld** [comment]
Strangely (or maybe because I have done it on Linux machine, not on a MACOSX one), I got another - and correct! - output:
```
[0x01057920]> af 0x01057920
[0x01057920]> s 0x01057929
[0x01057929]> pdf
/ (fcn) fcn.0x01057920 23
|   fcn.0x01057920 (int arg_8h, int arg_10h);
|           ; arg int arg_8h @ rsp+0x8
|           ; arg int arg_10h @ rsp+0x10
|           0x01057920      8b7c2408       mov edi, dword [arg_8h]     ; [0x8:4]=-1 ; 8 ; rdi=0xffffffff
|           0x01057924      b806000002     mov eax, 0x2000006          ; rax=0x2000006
|           0x01057929      0f05           syscall                     ; 33554438 = close (0xffffffff)
|       ,=< 0x0105792b      7305           jae 0x1057932               ; rip=0x1057932 -> 0x10244489 ; likely
|       |   0x0105792d      b8ffffffff     mov eax, 0xffffffff         ; -1 ; rax=0xffffffff
|       `-> 0x01057932      89442410       mov dword [arg_10h], eax
\           0x01057936      c3             ret

```
In conclusion, I think @radare can apply my patch with some risks involved, because it will fix your issue about "ESIL duplicates". What 'bout other flaws like one I noticed at the top, I think it's issue with portability or analysis bugs, so it's not my fault. Again, not tryin' to be rude, just want to resolve our problem here, hehe.

**Comment by jacobrosenthal** [comment]
Just an update on where this currently is, @NotSoOld commit appears to fix duplicates in esil but maybe theres some code portability issue?

Theres still a second issue in that the disassembly uses eax register naming while esil uses rax (proper x86 64bit) register naming.. Any thoughts on where I can poke around to fix that? Or f it lets just be consistent and make esil use the eax naming instead.

**Comment by jacobrosenthal** [comment]
@NotSoOld whatever that esil printing bug was, its fine in upstream with your patch applied now shrug
```
|           0x01057920      8b7c2408       mov edi, dword [arg_8h]     ; [0x8:4]=-1 ; 8 ; rdi=0xffffffff
```

**Comment by NotSoOld** [comment]
Awesome! But my patch still needs a review and, I guess, some corrections because it cannot pass Travis tests. However, I don't know what I should correct, so, maybe someone can handle that issue instead.
