### ISSUE TITLE
Visual mode assembler only writes one instruction

### ISSUE THREAD

**Issue by ichung** [radare/radare2#11138]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian Linux x86_64 (inside a VM)
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19186 @ linux-x86-64 git.2.8.0-127-g87a360f8e commit: 87a360f8ed513fb4cda895a4274c34eb15ca9c94 build: 2018-08-18__18:08:43

### Expected behavior

`a` command in visual disassembly mode should overwrite multiple instructions

### Actual behavior

`a` command only changes first instruction

### Steps to reproduce the behavior 

```
$ git clone https://github.com/monosource/radare2-explorations-binaries.git
$ cd radare2-explorations-binaries/tut1-patchme
$ make
$ cp patchme patchme_fix
$ r2 -Aw patchme_fix
> s main
> V
```
In visual mode:
- Press `p` to enter disassembly view
- Press the `a` key
- Type `nop;nop;nop;nop;nop`

Observe that only one `nop` is there rather than 5.  On the other hand, using `"wa nop;nop;nop;nop;nop"` command in non-visual mode works fine.

**Comment by XVilka** [comment]
It is probably because visual mode doesn't quote the command.

**Comment by ret2libc** [comment]
I think it worked time ago.

**Comment by radare** [comment]
Yes this has been working fine always. Didnt tried to reproduce

**Comment by radare** [comment]
cant repro

**Comment by ichung** [comment]
It is still certainly broken for me on master.  Can you please reopen this?

**Comment by radare** [comment]
Define broken. Works for me

**Comment by cryslith** [comment]
Hi, unfortunately this still doesn't work for me.  I didn't point it out before but in order to reproduce you have to use lower-case `a` button and not upper-case `A`.  Only the lower-case one is broken.

@XVilka already pointed out the cause: comparing https://github.com/radare/radare2/blob/da112132c8041d37773c91d7191776c07a8dafc3/libr/core/visual.c#L2445
with
https://github.com/radare/radare2/blob/da112132c8041d37773c91d7191776c07a8dafc3/libr/core/visual.c#L2734
you can see that the latter quotes the command while the former doesn't.  The behavior I see is consistent with that, as everything after the semicolon gets interpreted as a separate command.

Thanks for your time & effort!

**Comment by radare** [comment]
This line should be using the api but adding the quotes can be a workaround for now. Can you submit a PR?
