### ISSUE TITLE
Unable to apply a seek to an interator expression.

### ISSUE THREAD

**Issue by Shaddy** [radare/radare2#11145]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | Ubuntu 18.04 x64
| File format of the file you reverse      | ELF
| Architecture/bits of the file           | x86/64
| r2 -v full    | radare2 2.9.0-git 19168 @ linux-x86-64 git.2.8.0-127-g87a360f8e commit: 87a360f8ed513fb4cda895a4274c34eb15ca9c94 build: 2018-08-19__01:08:52

### Expected behavior

```
[0x00005850]> aa; s @@=`afl~!sym,sub[0]`
[0x00005850]> s=
0x5910 > 0x3e80 > 0x3e90 > 0x5850 > 0x5880 > 0x5910 > 0x5950 > 0xc2c0 > 0x11fd0 > 0x135b0 > 0x14950 > 0x16340 > 0x0
```
### Actual behavior

```
[0x00005850]> aa; s @@=`afl~!sym,sub[0]`
[0x00005850]> s=
0x5850
```

### Steps to reproduce the behavior 

Just open ls (r2 /bin/ls) do a simple analysis `aa` and execute the command:

```
s @@=`afl~!sym,sub[0]`
```

If you do the exactly same command surrounding with brackets it will work:

```
[0x00005850]> aa; s [@@=`afl~!sym,sub[0]`]
[0x00005850]> s=
0x5910 > 0x3e80 > 0x3e90 > 0x5850 > 0x5880 > 0x5910 > 0x5950 > 0xc2c0 > 0x11fd0 > 0x135b0 > 0x14950 > 0x16340 > 0x0
```

**Comment by Shaddy** [comment]
Running just the expression `afl~!sym,sub[0]` throws the right values, didn't knew about ?v, great feature tho.

**Comment by qrux0** [comment]
According docs `@@=` runs some command foreach offset.

So,
```
s @@=\`afl~!sym,sub[0]`
```
runs `s` command, which prints current offset (not seeks for it, just prints).


Maybe @Shaddy wants to use,
```
s $$ @@=`afl~!sym,sub[0]`
```
which do what he wants.

**Comment by qrux0** [comment]
but 
```
s [@@=`afl~!sym,sub[0]`]
```
still looks like some rly interesting bug)

**Comment by qrux0** [comment]
@Shaddy, yep, behavior of `@@=` may be described in this pseudocode

```
for offset in offsets_list:
	r_core_seek(offset)	//temporary seek, without memorisation
	r_core_cmd(YOUR_CMD)
``` 

Now I realized that instead of current address ($$) in expression

```
s $$ @@=`afl~!sym,sub[0]`
```

you can use LITERALLY any address, and it will work same way, for example

```
s 0x0 @@=`afl~!sym,sub[0]`
```

It happens because `s` pushes PREVIOUS address in seek history. In this case it pushes temporary seek from `@@=` loop, so no matter where you will seek as long seek address is valid.

**Comment by qrux0** [comment]
One more thing, about s [@@=\`afl~!sym,sub[0]\`]

Actually it's just because command `s [` works wrong.
Steps for reproduce:


```
r2 /bin/ls
[0x00005430]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x00005430]> s=
0x54f0
[0x00005430]> ss main
[0x00003bb0]> s=
0x54f0
[0x00003bb0]> s [
[0x10102464c457f]> s=
0x54f0 > 0x3bb0
```

This happens because at offset parsing (in our case we have "[") `r_num_get` calls `num->callback` (which is `num_callback` from core.c), which don't handle errors correctly ( https://github.com/radare/radare2/blob/master/libr/core/core.c#L467 ).
