### ISSUE TITLE
Building a complete ROPChain

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#1131]
It would be great if radare2 could generate a complete ROPChain.
- [ ] Identify gadget semantically (likely with ESIL)
  - [ ] move a register `A` into a _register_ `B`
  - [ ] move a register `A` into an _offset_ `B`
  - [ ] syscall
  - [ ] set a _register_ `A` to zero
  - [ ] increment a _register_ `A`
- [ ] Borrow code from RopGadget to generate the ropchain.
#### Sources
- [mona.py](https://www.corelan.be/index.php/2011/07/03/universal-depaslr-bypass-with-msvcr71-dll-and-mona-py/)
- [ROPGadget](https://github.com/JonathanSalwan/ROPgadget/)

**Comment by XVilka** [comment]
@jvoisin please split this in a smaller tasks.

**Comment by EasyHard** [comment]
https://github.com/JonathanSalwan/ROPgadget/ does not Identify gadget semantically. Instead, it just uses regex to match needed parts to execv /bin/sh. 

It should be easy to make a similar implement since radare2 could also searching rop gadget by regex. So I think this may be a good starting point. Maybe I can make a PR of it. How do you think @jvoisin ?

And with ESIL radare2 will be cooler since ESIL supports different arches IIUC. Also ESIL makes it possible to specify other return-oriented-programming codes rather than execv /bin/sh.

**Comment by jvoisin** [comment]
I think I had some PoC that does exactly this, based on <s>stolen</s> borrowed code from ROPgadget. I think it would be more interesting to make a first iteration with ESIL, and to refine it later, since the *grep* thingy won't be really re-usable, will it?

**Comment by EasyHard** [comment]
OK. I am trying to make some PoC of tasks in [Ropchain generator with ragg2
](http://radare.org/gsoc/2016/ideas.html#title_4), so that I can get some sense of them and write a proposal. But I think you are right. ESIL is more interesting and more important in this GSoC  idea.

**Comment by radare** [comment]
isnt all this already done by gsoc?

**Comment by jvoisin** [comment]
I don't think so :/

**Comment by Maijin** [comment]
See META
