### ISSUE TITLE
clusterfuzz-testcase-minimized-ia_fuzz-5639176288993280.dms

### ISSUE THREAD

**Issue by radare** [radare/radare2#11559]
[clusterfuzz-testcase-minimized-ia_fuzz-5639176288993280.dms.zip](https://github.com/radare/radare2/files/2388194/clusterfuzz-testcase-minimized-ia_fuzz-5639176288993280.dms.zip)

**Comment by F3real** [comment]
I tried solving this issue, but I am having trouble reproducing it.

I've statically built radare (sys/static.sh), then I built fuzzer target with:
`CXX=clang++-7 CXXFLAGS="-fsanitize=address -fsanitize-coverage=trace-pc-guard" LIB_FUZZING_ENGINE=/usr/lib/llvm-7/lib/libFuzzer.a RADARE2_STATIC_BUILD=/home/user1/packages/radare2-regressions/fuzz/targets/r2-static make`

and then I tried running it with:

`ASAN_OPTIONS=symbolize=1 ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-7/bin/llvm-symbolizer ./ia_fuzz -detect_leaks=0 clusterfuzz-testcase-minimized-ia_fuzz-5639176288993280.dms`

but in output I don't see any crashes (which is expected I assume), there is just a lot of leak detected which is strange since I set detect_leaks to 0.
Any hints on what I am missing or has this been fixed ?
Output I get:
[out.txt](https://github.com/radare/radare2/files/2441810/out.txt)

**Comment by radare** [comment]
I think the problem is related to the version of llvm/clang

**Comment by F3real** [comment]
@radare which clang version should be used ?

**Comment by radare** [comment]
its fixed in master already
