### ISSUE TITLE
rlist asserts in i commands

### ISSUE THREAD

**Issue by radare** [radare/radare2#11844]
<img width="695" alt="screenshot 2018-10-18 at 02 44 38" src="https://user-images.githubusercontent.com/917142/47124751-cdc94780-d27f-11e8-98fd-cfe365c42a6a.png">

**Comment by davidpolverari** [comment]
Several tests are sensitive to the text output of `i` subcommands. I tried with https://github.com/radare/radare2/pull/11885/commits/1ed1603fb39d02390c5b3de5189d3ff8c2ed83b4 and https://github.com/radare/radare2/pull/11885/commits/3ed23b5071bfe2cb0c565c6c0353b7754a1c12cf with no success because of that.

**Comment by Maijin** [comment]
Why do you add text printing? Just leave it blank but fix the assert

**Comment by radare** [comment]
Imho theres no need to print anything when there are no symbols or so

**Comment by davidpolverari** [comment]
Seems this can be closed because of https://github.com/radare/radare2/pull/11894, right?
