### ISSUE TITLE
PageUp/PageDown do not work in disassembly window in Visual Panels

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#11899]
It supposed to scroll disasm back and forth, but does nothing.

**Comment by Vane11ope** [comment]
it's now actually < and > because J and K are now allocated for resizing now. 

still panels got window mode now so i guess all the manipulation targeting windows should be done in there.

therefore this task should then be

1.windows mode HJKL for resizing
2. normal mode JK should be page scroll

thats it.

**Comment by radare** [comment]
which solution do you propose?

**Comment by radare** [comment]
pls @Vane11ope any feedback on this or moving forward

**Comment by Vane11ope** [comment]
this also is fixed, you can easily check it by just go V! then JK or pgup/pgdn
