### ISSUE TITLE
List strings when io.cache=true

### ISSUE THREAD

**Issue by ITAYC0HEN** [radare/radare2#12102]
### Work environment
Latest version of radare2, multiple operation systems

### Expected behavior
`izz` command to show up to date strings 

### Actual behavior

When open a file on read-only mode, and turning on the `io.cache` settings, any modification to the file won't affect the result of `izz`. This is due to how RBin is built.

I'd expect a way to execute `izz` on the modified file, even when the modifications are not applied (written) to disk.

### Steps to reproduce the behavior 

```
$ echo Hello World! > example.txt
$ r2 example.txt
[0x00000000]> e io.cache=true
[0x00000000]> w Test String!
[0x00000000]> px 16
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  5465 7374 2053 7472 696e 6721 0aff ffff  Test String!....

[0x00000000]> izz
[Strings]
Num Vaddr      Paddr      Len Size Section  Type  String
000 0x00000000 0x00000000  13  13 () ascii Hello World!\n
```

**Comment by radare** [comment]
iz and io.cache and -w have nothgn to do.

iz find strings and caches them at loading time, so they will be always there, even if you modify the file
io.cache - just allows you to write things in a layer on top of io instead of having to open the file in rw

even if you modify the string, iz will keep showing the old string because its cached by RBin,

there are a bunch of ideas to improve the situation of rbinstrings.

* make them 0copy (read the actual string from disk)
* dont make flags from them, otherwise they will be unsync with real strings

you can you /z to search strings again, or you can run  oob to reload the bin info

**Comment by ITAYC0HEN** [comment]
gotcha, `/z` will do. Thanks :)
