### ISSUE TITLE
disassemble an entire executable

### ISSUE THREAD

**Issue by houseofwealth** [radare/radare2#12343]
**Is your feature request related to a problem? Please describe.**
Not really a feature request but not a bug report either, but more of a "how do I do X"

**Describe the solution you'd like**
I am trying to disassemble an entire executable (the same way I might with say IDA Pro). 

**Describe alternatives you've considered**
I tried 
     rasm2 -a x86 -b 64 -d -f foo.exe
but that generated an error message (cannot assemble MZ at line 3)
I also tried radare2 directly with the pD command but that didn't generate anything readable, but rather data which was undisplayable

**Additional context**
Please let me know where I'm going wrong

**Comment by Maijin** [comment]
Greetings,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

I strongly suggest you read the radare2book - https://radare.gitbooks.io/radare2book/content/first_steps/command_format.html as printing disassembly is one of the most basic feature of radare2.

`-a x86 -b 64 -d -f` these flags are useless for your case because PE format is automatically recognized.

Once you have latest version and cleaned/purged trace of older versions, open the file with `r2 file.exe` print disassembly you can just use pd.

If you encounter a bug, use bug report not the feature request template.

**Comment by houseofwealth** [comment]
I downloaded the binary for Windows. Are you saying that isn't the one to use?
```
$ radare2 -v
radare2 2.8.0-git 1 @ windows-x86-32 git.
commit: 653064d30ac2a3035c26cc0cbd394b1b7a9b5d65 build: Sat 07/14/2018__ 8:12:38.88

```
Incidentally this does not seem to have the "r2" command, instead I called "radare2" directly

**Comment by houseofwealth** [comment]
I just wiped the old radare2 and installed radare2-3.1.0 and it still does the same thing as before

**Comment by Maijin** [comment]
Can you paste the output here or take a screenshot?

**Comment by radare** [comment]
R2 is a symlink to radare2

**Comment by Maijin** [comment]
Discussion moved there https://github.com/radare/radare2/issues/12351
