### ISSUE TITLE
ELF: can't load symbols from the linux kernel image

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#1251]
Here is the image:

http://xvilka.me/vmlinux-3.13.0-24-generic 

'is' output is 0 (zero)

**Comment by XVilka** [comment]
@radare so, ages are passing, what should we do with @LemonBoy elf-ng parser? Abandon it? Rebase an polish one more time? Some 3rd way solution?

**Comment by radare** [comment]
I have recently started to read rbin again and ive been thinking in some optimizations and stuff to change, 

But as i said, changes in rbin require time for fuzzing and covfixing, thelemon parser doesnt gives any benefit to r2 because it is incomplete, it is known to crash with some binaries and most of the bugs cant be prooved because there are no tests.

Both elf parsers can coexist in current r2. I have already suggested several months ago to rewrite that parser with a different name to have both in master for proper testing without loosing features or so.

I already said several times i was not going to switch to a new elf parser before the release. And im not going to change it if simple tests just fail.

His codebase looks cleaner, but its incomplete and have several bugs, which the current one does not.

Also, ive got a huge speedup using sdb in rbin for some tests, and i think that sdb can bring several other benefits to rbin, so both parsers will be deprecated soon or late. (Or just taken as base)

**Comment by radare** [comment]
Also, the elf-ng parser cant load a PE file and understand it have a payload in ELF, in fact nobody can do that. Kernels are usually not that easy to handle because of the loader/compressed payloads.

**Comment by radare** [comment]
Anyone tried so far with the latest elf parser in r2-git? there have been several related enhacements

**Comment by XVilka** [comment]
fixed. Though lighter regression test should be added
