### ISSUE TITLE
Kill section.c (iosections)

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#12701]
We need to kill section.c (iosections):

```
$ git grep r_io_section libr| grep -v /io/| grep  -v /include
libr/core/cbin.c:					r_io_section_add (r->io, section->paddr, addr,
libr/core/cbin.c:		r_io_section_apply_bin (r->io, r->bin->cur->id, R_IO_SECTION_APPLY_FOR_ANALYSIS);
pmb:radare2 pancake$
```

**Comment by radare** [comment]
indeed, but i though we had an issue for that already

**Comment by Maijin** [comment]
Actually you're right for this one. I moved the other one for the current release.

Duplicate of #2299

**Comment by Maijin** [comment]
Oh well the other one is super messy so I'll keep this one.

**Comment by radare** [comment]
I have removed ALL the uses of RIOSection except the 2 pending function calls which are needed for RBin to  work, because rbin uses iosection to notify io which maps to raise.. which seems a bit ridiculous and wrong its the last barrier to completly kill iosection. pls  @ret2libc take a look at this so we can discuss for proper rbin fix

**Comment by ret2libc** [comment]
Ok I will.

**Comment by Maijin** [comment]
There is also still:

```
libr/io/desc.c: r_io_section_cleanup (io);
libr/io/desc.c: r_io_section_cleanup (io);
libr/io/io.c:   r_io_section_init (io);
libr/io/io.c:   r_io_section_fini (io);
libr/io/io.c:   r_io_section_init (io);
libr/io/io.c:   bnd->section_add = r_io_section_add;
libr/io/io.c:   r_io_section_fini (io);
```
And ofc sections.c itself to be checked

**Comment by ret2libc** [comment]
done

**Comment by Maijin** [comment]
Amazing!
