### ISSUE TITLE
meson doesn't install "libr_magic.so" when use_sys_magic=true is selected

### ISSUE THREAD

**Issue by david-geiger** [radare/radare2#12768]
Hi,

On Mageia Cauldron when I compile latest radare2 3.2.0 with meson build system and with "use_sys_magic=true" the shared libraries "libr_magic.so, libr_magic.so.3.2.0" are not installed, while using libtool (configure) does it.

Is this normal? or a bug using meson?

If these shared libraries are not installed radare2-cutter fails to build with:

> moc_ColorSchemeFileSaver.o moc_ColorSchemePrefWidget.o moc_EditFunctionDialog.o moc_CutterTreeView.o moc_ComboQuickFilterView.o moc_HexdumpRangeDialog.o   -lr_core -lr_fs -lr_debug -lr_hash -lr_anal -lr_search -lr_egg -lr_crypto -lr_config -lr_bin -lr_io -lr_asm -lr_parse -lr_syscall -lr_reg -lr_lang -lr_cons -lr_flag -lr_socket -lr_bp -lr_util -lpython3.7m -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread   
/usr/bin/ld: Cutter.o:(.data+0x74): undefined reference to `r_magic_version'
collect2: error: ld returned 1 exit status
make: *** [Makefile:727: Cutter] Error 1

Regards,
David

**Comment by radare** [comment]
Cc @ret2libc

**Comment by ret2libc** [comment]
I think this issue should be reported to radare2-cutter project, because on radare2 side we are good IMHO. Indeed I can compile radare2 with `meson -Duse_sys_magic=true build; cd build; ninja` without any issue. Of course, if you use `sys_magic=true`, you do not use the radare2 magic library, but the system one, so `r_magic_version` is not defined (in radare2 code the uses of that var is indeed protected with:
```C
#if !USE_LIB_MAGIC
		{ "r_magic", &r_magic_version },
#endif
```

Something similar should probably be used on cutter too.

**Comment by ret2libc** [comment]
They are 2 separate build systems and it could be they do things slightly different. I believe however it has no sense providing radare2-magic library if you use `--with-sysmagic`, given the two libraries have the same interface.

**Comment by pelijah** [comment]
https://github.com/radare/radare2/blob/master/meson.build#L436
