### ISSUE TITLE
Function cannot be found if basic block is above function entry

### ISSUE THREAD

**Issue by rlaemmert** [radare/radare2#13078]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | voidlinux x86 64
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17284 @ darwin-x86-64 git.2.2.0-476-gf8cf84e06 commit: f8cf84e0653642d9ad34e760e0e56dd81860e799 build: 2018-02-17__11:08:27

If a function has a basic block above the entry of the function the node will not be detected
as part of the function. For example tabbing throught the nodes in graph view will result in 'No function at ...' for the specific node.

### Steps to reproduce the behavior 
https://github.com/radare/radare2-regressions/pull/1696

**Comment by ret2libc** [comment]
I've done a bit of testing and I believe the problem is in `_fcn_tree_probe` and similar functions. They use `fcn->addr`, however I believe they should use `fcn->rb_min_addr`, in a way similar to `rb_max_addr`.

**Comment by radare** [comment]
This is important. Should be milestoned for 3.3

**Comment by ret2libc** [comment]
Yes I can try to work on it. I can't assure it though...

**Comment by radare** [comment]
any updates on this?

**Comment by ret2libc** [comment]
No sorry but I will work on this soon

**Comment by ret2libc** [comment]
Solution could be easy: instead of storing functions in the RBTree and relying on tinyranges, we could just store all basic blocks in the RBTree. By using RAnalBlock, fcn_tree would just become a regular interval tree and you can easily resolve a lot of queries.

However.... the hard part is that basicblocks are modified everywhere without a clean way and every time they are changed in some way, the fcn_tree should be updated. This is not easy right now because the analysis code is a bit of a mess.

**Comment by radare** [comment]
yes, thats why wee dont store the bbs in there, because during the analysis they are modified a bunch of times for splitting them and such, and the fcn/bb storage is slow to reorganize, so it cant be used to store WIP information that is subject to change. its not an easy problem to solve, and its not fault of the bb getting splitted because thats a pretty standard operation

**Comment by ret2libc** [comment]
I don’t mean it’s the splitting the problem. I’m saying that there’s no central function that removes basic blocks or a single function where basic blocks are modified. If this doesn’t work it means that neither by storing functions it can work, since functions info depend on bb info.
