### ISSUE TITLE
Fix `afs` to use `td`/`tl`

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#13451]
Currently `afs` is just a stub. To think how better to implement it - either make an alias for `td` or something else.

**Comment by radare** [comment]
FTR:

* afs right now seems to do nothing, neither shows or sets any function signature
* you can redefine the function signature with `td` by redefining the functioni if we use the same name in the type
* function types cant contain dots. so iits not possible to define signatures for sym.fun.xxx functions
* imho afs. should be an alias for tf. which doesnt exist either, but must display the func signature
* td/tl doesnt works for function signatures, only structs afaik, thats confusing and not consistent.
* to get the current function signature one must use afcf which is kind of confusing because its not related to calling conventions

**Comment by radare** [comment]
* td int main(int argc) # works to redefine main signature

Question: how to do type propagation after any function signature change? imnho we should send a message when this happens

**Comment by sivaramaaa** [comment]
> Question: how to do type propagation after any function signature change?

@radare you can use afta command for propagating type

> imnho we should send a message when this happens

Yup this could be done , so that it's automatic !

**Comment by radare** [comment]
> On 21 Mar 2019, at 17:48, sivaramaaa <notifications@github.com> wrote:
> 
> Question: how to do type propagation after any function signature change?
> 
> @radare you can use afta command for propagating type
> 

Do afta updates the info or duplicates it if done twice? And i think this must be run everytime we change a function signature. But maybe we should do this via hooks when that event is broadcasted
> imnho we should send a message when this happens
> 
> Yup this could be done , so that it's automatic !
> 
Can you work on this issue too?

**Comment by radare** [comment]
ping? can you fix this @XVilka

**Comment by XVilka** [comment]
Yes, I will do it tonight.
