### ISSUE TITLE
Wrong analysis

### ISSUE THREAD

**Issue by radare** [radare/radare2#13501]
reported by @oddcoder 

```
aaa
s 0x4901
v 
```
<img width="441" alt="Screenshot 2019-03-25 at 12 40 03" src="https://user-images.githubusercontent.com/917142/54917015-25d53b80-4efb-11e9-9839-5d0546a3dcb8.png">

[ls.oddcoder.zip](https://github.com/radare/radare2/files/3003046/ls.oddcoder.zip)

**Comment by radare** [comment]
https://asciinema.org/a/9zmXiw4IFOVnejZrQV9exvOo8

**Comment by radare** [comment]
i think the problem is taht the bb is owned by anotehr function so it considers its an external jump. the fix requires more time than -38minutes. moving to 3.5

**Comment by ret2libc** [comment]
This seems the commit that introduces the issue: a404c7706366689f089cd30ea9d6cd4bde2560f5

BTW, with the binary I have for testing, even IDA free (7.1) has the same exact issue :D

**Comment by radare** [comment]
MUAHAH that's why i introduce bugs in r2 sometimes :P to spot the copycats!

**Comment by ret2libc** [comment]
What I found so far: it seems the problem is caused by a wrong jmptable size. The analysis to find out the size of the table is not very precise and it can confuse some immediate numbers for the size of the jmp table. This, in turn, makes the analysis analyze some mis-aligned instructions, breaking everything :/

**Comment by radare** [comment]
i fixed it

**Comment by radare** [comment]
maybe good to add a test

**Comment by radare** [comment]
test added
