### ISSUE TITLE
bin.maxstrbuf or -zzz not working

### ISSUE THREAD

**Issue by B1ttu** [radare/radare2#14580]
Hello Devs,
I got maxstrbuf error in r2
![01](https://user-images.githubusercontent.com/31536160/61390608-a48b2580-a8aa-11e9-9b3e-7c57279f98b1.png)
![02](https://user-images.githubusercontent.com/31536160/61390609-a48b2580-a8aa-11e9-8744-95b5d3b7ecc3.png)
![03](https://user-images.githubusercontent.com/31536160/61390610-a523bc00-a8aa-11e9-8190-6106d555949f.png)

OS : Kali _ Linux _ x64
Version : W29 _ gnome

r2 -v
radare2 3.2.1 0 @ linux-x86-64 git.
commit: unknown build: 2019-03-02__19:36:59

void install radare2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
radare2 is already the newest version (3.2.1+dfsg-5).

**Comment by radare** [comment]
we dont fix bugs in old versions of r2. please install r2 from git before reporting an issue

**Comment by radare** [comment]
fyi: 3.2 is 7 month old which is about 3000 commits away from master

**Comment by B1ttu** [comment]
![04](https://user-images.githubusercontent.com/31536160/61391882-36942d80-a8ad-11e9-9b98-962b34e980f2.png)
 please check this

**Comment by B1ttu** [comment]
Actually ptrace not working.. and i think Kali devs configure your radare2 for Kali Linux and uplad on there server.. that's why in Kali version i got maxstrbuf and in official version.. i got PTRACE error

**Comment by radare** [comment]
ptrace is working this is just a debug message, otherwise you wont see the pid or step or chk the regs after this, i should probably remove this message because its confusing people

**Comment by B1ttu** [comment]
how ptrace working.. if it's said : ptrace (PT_ATTACH): Operation not permitted ??

**Comment by radare** [comment]
if you use -e bin.... you have to assign a value, otherwise its not changing any behaviour. also, searching for strings in memory is not something you may do in debugger, because the allocated memory regions are pretty huge compared to when loading a single binary, it is recommended to use anal.in and make use of the anal.strings instead of the bin.strings option

**Comment by B1ttu** [comment]
Well no change
![05](https://user-images.githubusercontent.com/31536160/61393217-0d28d100-a8b0-11e9-94d1-6c761caec3ee.png)

**Comment by B1ttu** [comment]
Which OS you are using for build radare2 .. I think Ubuntu.

**Comment by radare** [comment]
because it tries to attach twice when doing 'ood' and the 2nd time is not permitted,thaat doesnt happen if you do r2 -d ...  without ood, i dont use linux too much, and this is a linux psecific issue. my main dev platform is macOS

**Comment by B1ttu** [comment]
![06](https://user-images.githubusercontent.com/31536160/61394083-e79cc700-a8b1-11e9-9910-08b700339cba.png)
HERE I GOT SOMETHING WIRED OUTPUT

When i type H its some me add.. but when i type QUIT.. it show me output which i want .. why its happening

**Comment by radare** [comment]
H is not a command, so there's nothing weird at all

Q is quit r2 without asking, so it lets the program to continue, which is also expected and not WIRED at all

you shouldnt use the caps lock in r2land

**Comment by B1ttu** [comment]
Wired bcoz.. after i quit.. its print 
CHECKING LICENSE: AA-A
WRONG

I analysis pid and after i kill r2 .. its show checking AAA-AAA
wrong

**Comment by B1ttu** [comment]
![08](https://user-images.githubusercontent.com/31536160/61395070-17e56500-a8b4-11e9-80c6-318e8cb1f83a.png)
here i debug pid

**Comment by radare** [comment]
thats the program you have been debugging, if you quit without prompting what to do the process continues, so it runs and shows that. if you expect r2 to kill the process when you quit r2 without prompting anything you can open an issue and we can discuss this in a different place, but as i said, Q is the same as q!! which behaves like this. so its expected behaviour

**Comment by B1ttu** [comment]
I make a full video,, which i better to show you

**Comment by B1ttu** [comment]
https://drive.google.com/open?id=1MH-85XfkAUtJqeIqUqw1W8qAF-jN3hAf

here is the video

**Comment by radare** [comment]
Yes, exactly what i tried to explain. this r2 subprocess is a thread that intercommunicates with the top r2 process in order to allow to use the debugging thread from other threads, which was implemented in the ptrace-wrap implementation (theres a configure flag to remove this if its that anoying for you), but its required for Cutter to debug on Linux without blocking the UI.

which is the issue you are trying to show? the debugger in r2 works perfectly fine despite this ptrace error message which you may ignore. but  we should probably fix that to avoid confusing  people

**Comment by B1ttu** [comment]
**which was implemented in the ptrace-wrap implementation (theres a configure flag to remove this if its that anoying for you), but its required for Cutter to debug on Linux without blocking the UI.**

How i do that --^.. please let me know

**Comment by radare** [comment]
I still dont see whats the problem you have despite having an error message that can be ignored because its meaningless.

Cutter have no debugger support. But r2 have this already awaiting for cutter devs to do their part.

About the configure flag just use —help|grep ptrace

**Comment by B1ttu** [comment]
okay
I try
