### ISSUE TITLE
ARM post increment addressing mode not working

### ISSUE THREAD

**Issue by elouet** [radare/radare2#14850]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian (Kali) x86 64
| File format of the file you reverse (mandatory)      |  ELF, raw
| Architecture/bits of the file (mandatory)            | ARM 16
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.1 22570 @ linux-x86-64 git.3.7.1-30-g816f3107a commit: 816f3107ae997e85d60fe632bb436cb667d3084d build: 2019-08-19__14:10:15
### Expected behavior
In ESIL mode, the following ARM opcode should increment r0 in addition to loading 8 bit value to r3
  `ldrb r3, [r0, 1]! 
`

### Actual behavior
No update to r0; the ESIL code shown as replacement is 
`  r0,1,+,[1],r3,=`
which does not seem to imply the post-increment.
### Steps to reproduce the behavior 

 ```
$ r2 -a arm -b 16 - 
[0x00000000]>   wx 10f8013f
[0x00000000]>   pd 1
            0x00000000      10f8013f       ldrb r3, [r0, 1]!
[0x00000000]>   aei
[0x00000000]>   aes
[0x00000000]>   aer ~r0
```

results : `r0 = 0x00000000`
 expected : `r0 = 0x00000001`

**Comment by radare** [comment]
Can you send a pr fixing this esil expression and adding a test? Good catch! Thanks

**Comment by elouet** [comment]
I have found several other problems with ARM (16 and 32 bits mode).
I fixed one of them, but I am a bit reluctant to pull request too often (trying to avoid PR flood).
I am a also wondering if we should not try a more massive approach to ESIL emulation of ARM 
code because at the moment, it seems very partial. On the other hand, that ARM document is currently 7900 pages long... I don't know of any tool / method that would allow a massive check
of (all possible|most) instruction and various addressing modes. Maybe benchmarking ESIL 
against QEMU automatically ? Can we leverage other open source like maybe unicorn ?

**Comment by radare** [comment]
Shouldjnt be hard to make a scriot that runs code in esil and unicorn or real hardwRe and compares register value differences. Some people did that already in the past but theres nothing “official” or so

About performance. Is not one of the main priorities of esil. In fact pif we care about speed we should do JIT.

Also, unicorn is not bug free, but probably more stable because its a copypasta of qemu which is known to work pretty well for arm/thumb, so it should be better good for this case.

Also abuot performance, esil is not as fast as qemu, not because of esil, but because of the io, anal and reg apis. There are a bunch of known optimizations to be done here and there. But i basically lack hands and time to solve them all

We use to support new instructions in the assembker and the emulator as soon as someone needs them.

**Comment by radare** [comment]
I think this issue is fixed already, we can open other issues or PRs to address the other issues
