### ISSUE TITLE
jmp targets flag names not presented

### ISSUE THREAD

**Issue by 00rsiere** [radare/radare2#14976]
function filter in libr/prase/filter.c is responsible for substituting addresses for flag names in jmp/call instructions. Before a flag is replaced, the function calls another function, isvalidflag. If isvalidflag returns true, the address is replaced for the flag name. 

The isvalidflag function returns true if:

1. the flag name contains "main"
2. the flag name contains "entry"
3. the flag name starts with "section."

I believe that it would be beneficial to improve this logic so that flag names would be presented instead of the address in jmp instructions. the isvalidflag function is only called from the filter function - as such, I am unaware of the reason this function is necessary.

Removing this function, or making the function return true would trivially fix the "problem" - but I am not sure what that might break.

**Comment by radare** [comment]
feel free to do a PR also a oneliner reproducer would be good for the testsuite and to clarify the exact issue you are facing, because i dont see which is the flagname you are using that is being skipped

**Comment by ErezI** [comment]
open any binary,
aaaaa
go to a jmp label that shows an absolute address (jmp 0x1f0fa, for example)
change the name of the flag to my_jmp_flag (click d, click n and change flag)
the instruction will still show jmp 0x1f0fa
![setting_flag](https://user-images.githubusercontent.com/11993494/64735922-2e91ec00-d4f2-11e9-9d3f-bc85828970d4.png)
going to the flag address, we can see that the flag was, indeed, set
![flag_shown](https://user-images.githubusercontent.com/11993494/64735935-35206380-d4f2-11e9-8b06-b44d1da3eeb3.png)
after changing the code to return true in function isvalidflag, the flag now can be properly set - as can be seen below
![with_flag](https://user-images.githubusercontent.com/11993494/64735948-381b5400-d4f2-11e9-9114-e479217058af.png)

I will write a PR - I mainly raised this issue to understand if anyone is aware of a problem that may be caused by fixing the current behavior (I did not see anything, but it could be hiding somewhere I am not aware of)

**Comment by 00rsiere** [comment]
open any binary,
aaaaa
go to a jmp label that shows an absolute address (jmp 0x1f0fa, for example)
change the name of the flag to my_jmp_flag (click d, click n and change flag)
the instruction will still show jmp 0x1f0fa
![setting_flag](https://user-images.githubusercontent.com/52822209/64736866-4e2a1400-d4f4-11e9-9c9e-9725d71a4612.png)
going to the flag address, we can see that the flag was, indeed, set
![flag_shown](https://user-images.githubusercontent.com/52822209/64736878-541ff500-d4f4-11e9-93a7-590213afe8e8.png)
after changing the code to return true in function isvalidflag, the flag now can be properly set - as can be seen below
![with_flag](https://user-images.githubusercontent.com/52822209/64736890-58e4a900-d4f4-11e9-8fad-9b2525bcc10c.png)

I will write a PR - I mainly raised this issue to understand if anyone is aware of a problem that may be caused by fixing the current behavior (I did not see anything, but it could be hiding somewhere I am not aware of)

**Comment by radare** [comment]
The name must contain a dot

**Comment by 00rsiere** [comment]
Should have looked more closely at the function, in my mind I had the case for strncmp "section." reversed - any flag such as xxx.yyy will do as is.

This seems fair enough - I'll close the issue
