### ISSUE TITLE
Disassembling 68HC11 code doesn't form functions properly.

### ISSUE THREAD

**Issue by xuulan** [radare/radare2#15013]
I'm trying to disassemble an embedded 68HC11 file. I'm using Cutter (OS X). I can import the file and have it located in memory correctly. However when I try and define functions, it will get as far as a branch and then end the function there. It doesn't follow the branch properly. This also happens with 6809 code. I have disassembled 68000 and 8086 code and the function definition works properly.

I've included the code here, it's for a 68HC11, starting at 0x8000.
[purple_32501.bin.zip](https://github.com/radare/radare2/files/3597970/purple_32501.bin.zip)

**Comment by radare** [comment]
canyou provide a script to reproduce the issue you are refering? the file is smaller than 0x8000 and i dont get which part is m68k and which part is x86 in here, also specify which version of r2 you are using and such

**Comment by xuulan** [comment]
I guess I should be more clear. The code is only 68HC11, when I was referring to 68000 and 8086 it was for other files, not this one. I was trying to show that I'm using the same process for other files where Cutter worked properly. 
Version 1.9.0
Using r2-3.8.0
Based on Qt 5.12.1 (Clang 10.0 (Apple), 64 bit)
I don't have a script but here is the process:
Open file (purple_32501.bin)
Analysis enabled, use virtual addressing, import de-mangled symbols.
Advanced options:Architecture M680x, CPU 6811
Bits, endianness kernel, format all auto
Load bin offset 0x0000
Map offset 0x8000
Locate to 0x8000 (clra instruction)
Add Function here (at 0x8000)
The function stops at 0x8022 (bra $8027)
I assume you've unzipped the file. Size according to Cutter is 32.8 kB

**Comment by radare** [comment]
the issue is now fixed, but the analysis plugin is far from being perfect, see the commit i fixed the problem and improve it while you go. Basically what i found is that:

* no ESIL support for m680x (just construct the strings out of the capstone info)
* opex (aoj~{}) is empty (broken json)
* many other instructions miss basic analysis info

This is the first binary i see for m680x, so that's why the support for this arch was pretty basic. do you think we can ship it in the testsuite? or there are legal issues for distributing it?

**Comment by radare** [comment]
btw i have added a test case for this bugfix in db/anal/m680x

**Comment by radare** [comment]
btw i have added a test case for this bugfix in db/anal/m680x

**Comment by radare** [comment]
also i have fixed the broken json in aoj~{}
