### ISSUE TITLE
r2 -d and spaces in filenames

### ISSUE THREAD

**Issue by Susanne588586** [radare/radare2#1814]
in debug mode, r2 can has no like spaces. :)

```
$ r2 -e io.cache=true -A -d  foo\ bar
PID = 13279
pid = 13279 tid = 13279
r_debug_select: 13279 13279
p/debug_native.c:1534 debug_init_maps: /proc: No such file or directory
p/debug_native.c:1534 debug_init_maps: /proc: No such file or directory
r_io_open_nomap: Unable to open file: ./foo
r_io_open_nomap: Unable to open file: ./foo
pid = 13279 tid = 13279
 -- That's embarrassing.
[0x00000000]>
```

**Comment by Cwningen** [comment]
I think this bug comes from the way dbg:// url are created. The program and arguments are joined with spaces as separators. Later when parsing the url to build argv, the second part of the program name becomes the first argument. The dbg:// url should be escaped or encoded.

The function r_str_argv used to parse the command seems to support escaping already. I see a r_str_escape function but it does not escape the same characters.

**Comment by radare** [comment]
You can use rarun to do that and avoid that issue, and get several other goodies. But feel free to fix that.. But bear in mind that paths can contain spaces too..

To use rarun with r2 you can use r2 -e dbg.profile=rarun.profile -d --

Or just r2 -d rarun2 profile

**Comment by Cwningen** [comment]
How do you avoid that with rarun? There will be spaces in rarun arguments too.

I'd like to fix it but it will need to change the syntax for dbg://, and that will affect several part of the program.
I have seen them in radare2.c and io_debug.c, are there other places? Can the user type them somewhere?

I imagine several ways to modify the uri:
- quoting every arguments (including argv[0]) and escaping quotes and backslashes `dbg://"foo bar" "argument with spaces" "argument with \"quotes\"" "windows\\path"`
- escaping the spaces and backslashes `dbg://foo\ bar argument\ with\ spaces argument\ with\ "quotes" windows\\path`
- percent-encoding (only spaces, or anything that can be reserved: spaces, quotes, slashes?) `dbg://foo%20bar argument%20with%20spaces argument%20with%20%22quotes%22 windows%5Cpath`

Or anything you would prefer.

**Comment by radare** [comment]
Rarun configuration profile uses a different rule for each argument. You can even set ar srgument with yhe contents of a file or the output of an execution of a program.

The percent encoding is problematic because the uriencoding verifies the character set (not in r2, but other implementations do) and tends to fail on parsing on non-r2.

For quotes or backslashes thats a task of the shell, it already does that for you. Maybe not in windows, but any posix shell does that.

**Comment by Cwningen** [comment]
Okay, I did not know about passing the arguments in a file. It is not very practical but it is a workaround.

I proposed the percent encoding because it is standard for uri (but separating parts of the uri with spaces is not) and I thought it would be better for interaction with the rest of the world. The escaped strings are more readable by the user. That's why I wanted to know where and how there are used. There are interractions with other programs? with the user? or only with the io plugin?

There is no shell used here. The arguments come from argv, they are encoded in the dbg uri, which is parsed by the io debug plugin and then the arguments are passed to execvp. The issue is that there is a loss of information (the correct separation of arguments) during the dbg uri encoding.

**Comment by Cwningen** [comment]
I found some problems with r_bin_load_io_at_offset_as_sz. This function tries to guess the binary filename from desc->name. The current code uses the first part of the string until the first space.

I was first patching that on my linux laptop and I saw that desc->name was the command line so I used r_str_argv to get the proper binary name.

Testing on windows now, desc->name contains the path to the binary. It is not the same plugin, it was "debug" (uri in dbg://) on linux, it is now w32dbg.

Should desc->name be the same across different plugins? If they are plugin specific, shouldn't the plugin be responsible for loading the binary or, at least, providing the binary path? Is there any documentation on radare2 internals?

**Comment by Susanne588586** [comment]
r2 -e io.cache=true -A -d  foo\ bar
p/io_debug.c:325 fork_and_attach: execv: Permission denied
PID = -1
r_io_open_nomap: Unable to open file: dbg://./foo\ bar
r_debug_native_map_get: No selected pid (-1)
Cannot open 'dbg://./foo\ bar' for writing.

do I do something wrong?
