### ISSUE TITLE
Breakpoints memory on access

### ISSUE THREAD

**Issue by jjdredd** [radare/radare2#198]
I'd like to have memory breakpoints for memory ranges of various sizes.

**Comment by jjdredd** [comment]
you mean drx works fine, while dmp fails sometimes?

**Comment by radare** [comment]
drx works fine on linux, windows at least, the dmp should be working too, but i didnt reviewed recently

**Comment by radare** [comment]
This can be now implemented using stepinto and esil emulation to detect when an instruction is accessing a specific memory address.

**Comment by jjdredd** [comment]
this could have been done w/o esil

**Comment by radare** [comment]
Yes. this can be done with `dm` or `drx` as i have already pointed out. but both techniques depend on the debugger backend. the support for esil is totally arch and OS independent

**Comment by jjdredd** [comment]
you'll have to change page permissions anyway and esil wiki page says it's arch dependent (at least because of registers)

**Comment by radare** [comment]
no, you can just do stepinto and analyze the instruction with esil to
determine if its accessing the given address , which is 5 lines of C or
so. and can be emulated with `dsue`

**Comment by jduck** [comment]
Do we have tests for this stuff?

**Comment by radare** [comment]
Yes. Three kind of them:

* based on esil, evaluates expression and chrcks if it modifies a specific sddress, otherwise step
* dm to change the memory map protections
* dx - only for x86 atm, modifies the hw debug registers to handle those situations

**Comment by jduck** [comment]
The core request of this issue is "access breakpoints on memory ranges". That does not seem to be implemented, so perhaps closing this issue is premature.

However! It seems very difficult to implement more than what exists already. How would someone specify what to do once such a breakpoint is hit? As @radare said, you can already change page permissions with "dm". Even if we did that for the user, how would they know what offset was accessed (let alone what instruction)?

In general, I think it's really hard to design/implement something like this in an interactive debugger. I support closing this ticket for now as WONTFIX. As always, pull requests welcome =)

**Comment by radare** [comment]
you can identify which instruccion accessed that mem range with assessed debugging with dsue or other esil-helpers for the debugger. Hardware breakpoints are working (on x86), an should be implemented for other archs as well. that would solve the problem

it is possible to run commands on breakpoint hit, a guy sent a pr on that recently (<1month) and it was already possible before with dbC. so you can make conditional breakpoints already or even mark them as tracepoints.

debugging is not my main priority as i have tons of other things to manage and code. but other people may help on this. and we should also enable and add more tests. as always :)

so imho this issue is fixed with dsue, would be nice to implement an esil-helper for the memory map protection thing, its pretty simple because all the primitives are implemented and will work on all platforms:

- drop perms to page
- continue exec
- on exception check the esil of the instruction where it stopped to see if its accessing the specific memory we want to break
- repeat until death

this would be like a fast version of the dsue because dsue steps into, and this thing can be done in maybe 50 lines or so. which other options do you think we have to do the same thing?
