### ISSUE TITLE
Support underscore character in the project names 

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2012]
Project name currently can't contain underscore '_' character.

**Comment by radare** [comment]
I was thinking in using b64 to encode project names and this way avoid issues with encodings and other special chars that may fuckup paths and such. But or 99% of cases, plain ascii should be fine. And yep. Underscore shiuld be supported. Any other mossing char? I have to verify which chars are valid.. Because it should be using the util/name filtering function which is the same as flags use
