### ISSUE TITLE
Color Ascii Art Graphs 

### ISSUE THREAD

**Issue by radare** [radare/radare2#2091]
Now the lines are colorized but there are still some things to be done to support full color on graphs, this issue aims to track all the related TODOs:
- [x] Colourize nodes: user defined
- [ ] Colourize nodes that has been traced (like in the webui)
- [x] Permit colour disassembly (ANSI strings broke rconscanvas)
- [x] Fix the layout (avoid overlapped nodes)
- [ ] Make lines smarter to avoid be over the nodes
- [x] Make colours configurable using the RCons palette (ec ..)
- [x] Bring back the old lines style (configurable)
- [x] Add support for utf-8 https://github.com/radare/radare2/issues/1675 (likely in [canvas_line.c](https://github.com/radare/radare2/blob/master/libr/cons/canvas_line.c))
- [x] Optimize `sort_attrs()` and `attr_at()`

**Comment by r0nk** [comment]
Many will doubtfully notice that the colors are quite slow, this is due to the terribad algorithms I used to search and sort. If anyone is interested in making them faster, the offending functions are attr_at() and sort_attrs() in libr/cons/canvas.c, those two functions account for 90% of time spent when rendering.

**Comment by radare** [comment]
isnt this already done?

**Comment by Maijin** [comment]
@radare Not yet :D

**Comment by Maijin** [comment]
(See META)
