### ISSUE TITLE
Improve 't' commands

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2101]
- [x] Add ability to load big header files using the **to** command
- [x] Rename **Vt** to **Vf**
- [x] Add **Vt** for visual mode for types
- [x] Add tests to avoid regressions radare.today/types
- [x] WebUI for the types view/removal/modification

**Comment by radare** [comment]
Define big header

**Comment by XVilka** [comment]
this one https://github.com/snare/ida-efiutils/blob/master/behemoth.h

**Comment by radare** [comment]
I've noticed that #include directives try to load the file in the current directory instead of the same path where the main include was living. (fixed in git).

As long as we need:

* Preconfigured #define directives (usually defined by the compiler)
* Specify the include path order

We can probably define this in a single .h in user's home, or loaded from a cfg. directive. Any suggestion on this?

**Comment by XVilka** [comment]
@radare using the cfg. is better, imho. (And probably support for the list of directories in this directive).

**Comment by radare** [comment]
What about closing this issue or just reassigning it for 1.0 ? loading big headers is not going to happen for 0.9.9

**Comment by monokles** [comment]
started working on a web ui panel for types

**Comment by jvoisin** [comment]
Awesomely-super-duper-great!

**Comment by Maijin** [comment]
WIP closing this
