### ISSUE TITLE
`ag` doesn't work for a function defined with `af+`

### ISSUE THREAD

**Issue by Tyilo** [radare/radare2#2108]
Prints a graph of the basic blocks (working as expected):

	$ r2 test_bin
	[0x00000000]> e asm.arch=msp430
	[0x00000000]> s 0x4b66
	[0x00004b66]> af
	[0x00004b66]> ag

However this prints an empty graph (wtf?):

	$ r2 test_bin
	[0x00000000]> e asm.arch=msp430
	[0x00000000]> af+ 0x4b66 0x186 foo
	[0x00000000]> sf foo
	[0x00004b66]> af
	[0x00004b66]> ag

You can work around this by analyzing the function first, before defining it:

	$ r2 test_bin
	[0x00000000]> e asm.arch=msp430
	[0x00000000]> af @ 0x4b66
	[0x00000000]> af+ 0x4b66 0x186 foo
	[0x00000000]> sf foo
	[0x00004b66]> ag

However this is clearly inconsistent.

**Comment by radare** [comment]
This function contains 0 basic blocks. Thats why the graph is empty. Swe afb+

**Comment by radare** [comment]
Also, af+ is not suposed to be used after af

**Comment by Tyilo** [comment]
So if I know there is a function from address 0x1000 and 0x1200 and I want to mark it with `af+`, I will also have to manually find every basic block and mark them?
Seems like something radare2 should do for me.

**Comment by radare** [comment]
yes you have to do this by hand, because if you want r2 to do this for you yo just use the default code analysis of r2 `af`.. we can probably add another command .. af2? to get a length as argument, and analize a function forcing a specific size, and showing a warning for all the basic blcoks that will be created outside (and not creating them), but this will create inconsistencies with the edges

**Comment by Tyilo** [comment]
How adding `ab` for analyze blocks? It would take a range and find the basic blocks inside it.

**Comment by radare** [comment]
thats what `af` does, but without controlling the range. and limiting the range will happen that there will be nodes with broken edges and chopped blocks.

btw, there's a2f. which is a different algorithm for analizing code, and several anal. variables taht can be used to tune the analyzer. are you doing `af` by hand because the analysis is wrong?

**Comment by Tyilo** [comment]
I misunderstood how flags and functions were handled by r2. Using just `f` and `af` I achieved what I wanted to.
