### ISSUE TITLE
rasm2 bound missing

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#2121]
rasm2 does not decode the 'bound' instruction. Tried with x86 and x86.nz:

```
$ rasm2 -b32 -a x86.nz  -d '62'
disassemble error at offset 0
.byte 0x62 1
$ rasm2 -b32 -a x86.nz  'bound'
Cannot assemble 'bound' at line 3
invalid
$rasm2 -b32 -a x86  'bound'
Couldn't assemble instruction (bound)
Couldn't assemble instruction (bound)
Couldn't assemble instruction (bound)
Cannot assemble 'bound' at line 3
invalid
```

example from ndisadm:
00000010  625C7830          bound ebx,[eax+edi*2+0x30]

**Comment by radare** [comment]
s/decode/encode/.

Also, this instruction parsing is hard and the example you provide is wrong. Do x86.olly supports it? You can always use x86.nasm or x86.gas for such cases

**Comment by VisualPrankDude** [comment]
ok, x86.nasm works:

```
rasm2 -b32 -a x86.nasm  "bound ebx,[eax+edi*2+0x30]"
625c7830
```
one last question: why have so many x86.* and not just one ?

**Comment by radare** [comment]
Because none of all the plugins is perfect. X86 is hard, and willing not to depend on external programs makes gas/nasm/fasm not an option. Olly is gpl and 32bit only, but is small and pretty complete. X86.nz is the most complete standalone assembler for intel, supports some 16, 32 and 64. And .new is the last addition which supports few instructions and 32bit only, but the code is cleaner and easier to maintain.

**Comment by VisualPrankDude** [comment]
ok, then I will skip future issues, but we could make a mapping instruction to x86.* plugin.

Thanks.

**Comment by radare** [comment]
This will require much work, testing and maintainance and i dont think it benefits too much. It will be better to focus on enhacing the current ones or just use olly for 32 bits or nasm for 64 if you have it installed. Adding new instructions in the .nz assembler is very easy. Ive been implementing the instructions that are more used and ive needed somehow, do you need bound? If so, open an issue for it :)
