### ISSUE TITLE
Symbol name is percent-encoded when using rabin2 with json output

### ISSUE THREAD

**Issue by Cwningen** [radare/radare2#2169]
```
$ rabin2 -sj a.out | jq . | grep getchar
      "name": "imp%2egetchar"
$ rabin2 -s a.out | grep getchar
vaddr=0x00400c90 paddr=0x00000c90 ord=015 fwd=NONE sz=16 bind=GLOBAL type=FUNC name=imp.getchar
```
Why is it percent-encoded? JSON supports backslash escaping and only needs it for " and \\.

**Comment by Cwningen** [comment]
And strings are encoded in base64.
```
$ rabin2 -zj hello 
{"strings":[{"vaddr":1520,"paddr":1520,"length":13,"size":14,"type":"ascii","string":"SGVsbG8sIHdvcmxkIQA="}]}
$ rabin2 -z hello 
vaddr=0x004005f0 paddr=0x000005f0 ordinal=000 sz=14 len=13 section=.rodata type=a string=Hello, world!
```

**Comment by radare** [comment]
yeah i think that we should use base64 in all the strings coming from the binary. just because urlencoding is binded to the character encoding, and can raise exceptions if the constructed binary value is not recognized as a valid char (see javascript or python). base64 will just do that right, but base64 is not readable by humans.. thats why i choosed urlencoding there. mainly because symbol names are stored as flag-compatible strings, which doesnt support weird chars in them.

we should decide if use base64 everywhere or not, just for consistence. but i would prefer to avoid it in case the string is json-compatible, but its a problem to have strings in multiple different encodings..

**Comment by Cwningen** [comment]
I understand that strings may need encoding as they can contain any byte. I thought that characters in symbols were limited, but looking at some documentation on ELF, I see nothing, they are only non-null bytes. I guess the limitation comes from programming languages limitations, and someone could decide to use non-ascii characters in symbols with some hacking.

Maybe the percent encoding should be used only on non-printable or non-ascii characters (and the reserved characters " and \\).

**Comment by radare** [comment]
I think \x was also problematic because of the charset encoding. Symnames can be fuzzed. So they can contain nonascii chars. Also, go uses the middle-dot, for example

**Comment by radare** [comment]
as long as json is going to be consumed by serious programming languages and not silly humans we can asume all strings must be base64. this change will affect the webui. everybody is happy with this?

**Comment by pwntester** [comment]
Im ok with that, just let me know when you apply the change and I will fix webui accordingly

**Comment by jpenalbae** [comment]
The proper way to go is probably to stick with JSON standard http://json.org/ using "\u four-hex-digits" for any non ascii printable characters.

```javascript
> JSON.stringify({test: 'string \x00\x0f test'})
'{"test":"string \\u0000\\u000f test"}'
```

**Comment by Cwningen** [comment]
A pure JSON solution would be good but the \u escaping is for UTF-16 character and you need to know the encoding used in the binary to make the proper conversion.

**Comment by radare** [comment]
json and js are utf16, that’s why \x is not valid option here. the encoding shuoldnt affect here. in fact the heap spraying tools use that syntax to encode binary data.

i have pushed a commit with that change. please try

**Comment by radare** [comment]
Done by @pwntester and @trufae
