### ISSUE TITLE
Pc show what will be saved in the project script

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2250]
Currently the command `Pc` is not implemented. This command is supposed to show what would be saved in the project script. This is an easy task

**Comment by radare** [comment]
im not sure if we should implement this command, because we are moving to sdb, so the data cant be printed to stdout..

maybe just a command to show statiicall info like this:

current flags: X  project flags : Y
timestamps of projectfile, current time
etc..

but not under Pc. i would choose just `P` or `Pi`

feel free to remove `Pc` from the help list and the TODO eprintf.
