### ISSUE TITLE
Invalid flag name 'hit0_xxxxxxxx /E searching non esil expressions

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2283]
morn,

does esil expressions have spaces? If not, one could filter these:

r2 -d /bin/ls
[0xb773e840]> e asm.esil=true
[0xb773e840]> /E cmp eax,123
Segmentation fault (core dumped)
=> core dump unusable

[0x7f336ae72d80]> e asm.esil = true
[0x7f336ae72d80]> /E cmp rax,123
=> OOM killer

r2 -v
radare2 0.9.9-git 7437 @ linux-little-x86-32 git.0.9.8-1089-gade2945
commit: ade2945617f41b96f8edfe5f75c9b496cf1810c9 build: 2015-04-01

**Comment by radare** [comment]
cant reproduce. esil expressions do not support spaces

**Comment by zonkzonk** [comment]
that proposal is about filtering spaces, because no esi expression contains spaces ...

**Comment by radare** [comment]
but why that segfault?

**Comment by zheyuwu** [comment]
I think the problem is that `/E` will call ` __cb_hit` at every address in search range.
So there will be lots of hit messages stored in memory buffer and exhaust the system memory
which cause OOM killer(on my x64 machine) or segfault.

But my question is why `/E` logs hit message at every address as long as the esil is parsed successfully and gets a number. Shouldn't it only log hit message when finds the matched esil expr in the binary?

Below command will cause me OOM
```
r2 -d /bin/ls
e asm.esil=true
/E 123
```
Generated lots hit logs
```
....
0x7f5c66a305c4 0 hit0_422964
0x7f5c66a305c5 0 hit0_422965
0x7f5c66a305c6 0 hit0_422966
0x7f5c66a305c7 0 hit0_422967
0x7f5c66a305c8 0 hit0_422968
0x7f5c66a305c9 0 hit0_422969
0x7f5c66a305ca 0 hit0_422970
[0x7f5c669c9190]> 
```

**Comment by zonkzonk** [comment]
http://sprunge.us/QRZW

**Comment by radare** [comment]
If the esil result is different to xero is considered a hit. So this doesnt looks like a bug to me

**Comment by zonkzonk** [comment]
still in 663d135cfc0e5cde9365f48b8777e7c37718584a (r2 -d /bin/ls)
