### ISSUE TITLE
remove RIOSection (section.c)

### ISSUE THREAD

**Issue by condret** [radare/radare2#2299]
RIOSection is just some kind of RIOMap in functionallity. So, i think we should discuss about removing it to make things easier

**Comment by XVilka** [comment]
May be even storing all that information in the SDB would be awesome.

**Comment by radare** [comment]
We can probably tag the maps to be segments or sections and as long as we
know the associated fd to determine the source of it we can list the
sections of each bin from io. (From the loader point of view)

The way this info is stored doesnt matter a lot right now. In fact using a
struct is better for now because it allows better design. In sdb we should
use json or array with some accessors.

**Comment by condret** [comment]
currently i'd prefere not using sdb to store RIOMap, because the order in the list provides priority. This might be not so easy in sdb, i'm not sure

**Comment by radare** [comment]
Priorities in sdb can be done with arrays, but keeping the structs for now is fine for now.

**Comment by condret** [comment]
@radare aren't sdb-arrays just lists?

**Comment by radare** [comment]
Yes, for priorities u want ordered lists, which can be done with that
