### ISSUE TITLE
Unifying analysis commands

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#2403]
What about creating an "analyse as much as possible the binary in a single command" command, like `aa`?

**Comment by radare** [comment]
`aamap`

**Comment by XVilka** [comment]
we need also `aaaaa!!!` command to perform full-featured analysis with a guidance for a new user.

**Comment by radare** [comment]
All in uppercase. Screaming. And a lowercase exclamation mark like this:

AAAA!!1!1!

No srsly, what about aaa

**Comment by XVilka** [comment]
`aaa` looks perfect, something like 'analyse absolutely all' vs just an 'analyse all'

**Comment by radare** [comment]
The problem here is the order of execution of the analysis commands that may result in some problematic analysis. Thats why they are splitted. In fact aa is suposed to do the minimum approach and we can add some eval vars to run some or other.

Theres a bug that sometimes we loss the function names that must be fixed too

**Comment by Maijin** [comment]
Isn't that possible to store another info in the analysis result that say which fct has been detected with a specific aa* command like. fcn.0040ea00.cs <= This one is found by aac and aas. fcn.0040ea00.c <= This one is found by aac only ? Or somewhere else to be able to says ok I've runned aaa but now I see aat detection is not correct so using a command I can "hide" all aat detection but keep the other one ?
