### ISSUE TITLE
Wrong place for a context menu on a right click

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2429]
In the webui right click does bring up the browser context menu in most cases, the r2 menu is only available when right clicking at the correct location.

**Comment by radare** [comment]
I said many times that switching between two modes shouldnt be done with only the keyboard. Focus can be tricky, and i have suggested adding a button, but actually its only possible in the context menu when rightclicking in the offset.

But for tablets phones, this is really problematic, first because that button is really small and spawning the context menu is tricky, and second because theres no hw keyboard to fire those keys.

**Comment by jvoisin** [comment]
@pwntester : What about a "menu" button?

**Comment by XVilka** [comment]
@pwntester ping?

**Comment by pwntester** [comment]
If this is just for switching modes, I already added a switch button. Im not sure it makes a lot of sense to put a menu button somewhere since the context menu is contextaware and the menu would be something fixed. What is you idea for the menu button? what actions? where to place it?

**Comment by radare** [comment]
Ok to close it
