### ISSUE TITLE
Hang in 'aac'

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#2597]
With this fuzzed binary [hangbinary | uploaded via ZenHub](https://files.zenhub.io/555ca2696777ff675d24016c) happens the following. 

https://asciinema.org/a/5rsf10apgp0w3i3f6neg737fe

The issue I think is in `cmd_anal_calls` 

```
while (addr < addr_end) {
		r_io_read_at (core->io, addr, buf, sizeof (buf));
		if (r_anal_op (core->anal, &op, addr, buf, sizeof (buf))) {
			if (op.size<1)
				op.size = minop; // XXX must be +4 on arm/mips/.. like we do in disasm.c
			if (op.type == R_ANAL_OP_TYPE_CALL) {
	//			eprintf ("af @ 0x%08"PFMT64x"\n", op.jump);
				r_core_cmdf (core, "af@0x%08"PFMT64x, op.jump);
			}
		} else {
			op.size = minop;
		}
		addr += op.size;
	}
```

`r_anal_op` write in op.size 0 or 1 and then the loop will iterate one by one up to 385877888 times. I don't know if there is a way to know to abort this.

**Comment by radare** [comment]
If finding an invalid instruction it disassembles byte per byte, which is probably ok for x86, but problematic for arm/sparc/mips.. also, i understand that this is going to be an issue because of the addr_end which is bigger than the file maybe? using pread we can determine if the address has been allocated or not.

I would like to have a field in RAnalPlugin to specify the minimum instruction size and its alignment, which will be necessary for proper disasm alignment recovery from invalid instructions. Maybe this should be provided by RAsmPlugin. and used by RCore.disasm and all the analysis loops.

**Comment by radare** [comment]
In this code, this is used by the `minop` variable, but this should be probably reviewed in depth with the target file you provide

**Comment by radare** [comment]
In this code, this is used by the `minop` variable, but this should be probably reviewed in depth with the target file you provide.

Also, bear in mind that this information should be overridable by the user using anal hints or global configuration options.

**Comment by radare** [comment]
It's fixed with an error message that complains about section size being bigger than file size. This will require manual interaction to resize the section for example. But it's ok for now to close the issue
