### ISSUE TITLE
Local and args comments

### ISSUE THREAD

**Issue by grandemk** [radare/radare2#2650]
The local and args auto renaming comes with a decimal offset to ebp which is presented like this:
```
; var int local_5 @ ebp-20
````

But all the offsets in command are in hexadecimal
````
 mov byte [ebp - 0x29], 0xf3
```

local comments should be in hexadecimal for consistency
(This behavior is specific to the webgui, visual mode and normal mode use hex offsets)

**Comment by radare** [comment]
not really, the visual mode also shows locals in decimal, mainly because it specifies an aligned sequential name, which imho is way more readable than the hex approach of IDA, which is in hex, and doesnt really specifies the maximum amount of variables, which are aligned in the stack, also the current approach, specifies which of those vars are packged into a single word. This allows to easily identify arrays and other unaligned data types in the stack.

iirc, visual and webui shuold use the same syntax. we can parametrize this naming by a config var if you prefer the hex output. but imho this is better for the reasons i have exposed above

**Comment by grandemk** [comment]
I think we are talking about two different things. I'm talking about the ebp-0x26 part in this example:
In Visual Mode and iirc:
; var int local_9_2    @ ebp-**0x26**
; arg int arg_3        @ ebp+**0xc**
In webui:
; var int local_9_2 @ ebp-**38**
; arg int arg_3 @ ebp+**12**

I also like the naming of the variables, I don't think there is a need of a config option for these names, because the local_9_2 scheme is better than just a number anyway.

**Comment by radare** [comment]
Ok, i get the point, so its just a display issue in the delta, not the naming itself.

**Comment by grandemk** [comment]
Yes that's it :)
