### ISSUE TITLE
size in i/r with -d

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2862]
mrrn,

size is -1 with i and with r in debug mode.

```
ls -l /bin/ls; r2 -c 'i~size'  -d /bin/ls
-rwxr-xr-x 1 root root 118392 May 14 16:08 /bin/ls
Process with PID 17066 started...
PID = 17066
pid = 17066 tid = 17066
r_debug_select: 17066 17066
Using BADDR 0x400000
Asuming filepath /bin/ls
bits 64
pid = 17066 tid = 17066
size     0xffffffffffffffff
 -- Already up-to-date.
[0x7f50c37f8d80]> r?~dis
| r          display file size
[0x7f50c37f8d80]> r
-1
[0x7f57c0364d80]> q!
```

Greetings
--zlul

**Comment by radare** [comment]
it's not invalid, when debugging there are no file sizes, because there's no file at all, its just a huge memory address space that can be allocated/deallocated/remapped/overalpped/... -1 is the expected size. maybe we can just not show the size when its UT64_MAX to avoid this "ugly" output. and show a warning with 'r'
