### ISSUE TITLE
Graph '0'-'9' keys should jump in graph mode to the nth call

### ISSUE THREAD

**Issue by radare** [radare/radare2#2907]
Like VVX#

**Comment by ret2libc** [comment]
After discussing with @crowell and @Maijin , I think I will probably implement this with multi letters shortcut instead of numbers from 0 to 9, because of some issues related to the graph. In particular, visual mode does a "linear" disassembly, so an ordered sequence of numbers make sense, but it's meaningless in the graph. Moreover, multi letters is useful because you can have a lot of calls/jumps in a single function, but we don't want to parse again and again the whole graph every time you move in it, only to update the shortcuts.

So, I'm going to add a 'g' command in the graph mode that accept a sequence of letters and jumps to it.

**Comment by radare** [comment]
I would just show/obey the numbers of the current basic block, otherwise ull have to use a prefix key with input or trash the current non-numric keys

**Comment by radare** [comment]
You can also recalculate those numbers by redrawing node contents.. This will make it slower, but at least it will be just 1 keystroke like in visual instead of >3

**Comment by ret2libc** [comment]
Done
