### ISSUE TITLE
des command doesn't work if opened in non-debugging mode

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3028]
```
r2 /bin/ls
[0x004048c5]> des 1
 pc 0x00000000 -> 0x004048c5
Step failed
```
```
r2 -d /bin/ls
[0x7f88d8d81cd0]> des 1
0x7f88d8d81cd0  rsp,rdi,=
REG READ rdi
REG READ rsp
REG WRTE rdi 0x7ffcbd2341e0
```

**Comment by radare** [comment]
We should just report an error, what defines if running in debugger or not is the cfg.debug for the frontend and the io.debug field of the current io plugin . Theres also the debughandle plugin which specifies can be used even when the io is not the debugger for emulation with other backends. So that flexibility makes it harder to see. So in general. The user says with cfg.debug which is set by r2 -d and -D if he is debugging or not

**Comment by Maijin** [comment]
`dh esil`
