### ISSUE TITLE
Plugin (package) manager for the radare2

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3042]
I think a lot of people tired of compiling bokken dependencies, searching where is the yara plugins for the radare2, and still remember the easy to use `npm`, `pip`, `cabal`, `opam`, etc.

Here I'm suggesting to take some supersimple package/dependedncies manager and make it 'official', to just type 'r2pm install yara3' or 'r2pm update bokken'.

One of the possible options is to make fork of the [clib](https://github.com/clibs/clib) for example.

Please discuss.

**Comment by radare** [comment]
The idea lgtm. It can be based on slpm. I already wrote several pkg managers in the past. And if people likes to have over 9000 pkgmanagers in his systems this can be useful for them.

But maybe bokken should be packaged in pip

**Comment by jvoisin** [comment]
> I already wrote several pkg managers in the past

You're so pancake ♥

**Comment by radare** [comment]
For example: https://github.com/radare/slpm

**Comment by crowell** [comment]
let's call it `RPM` to just cause even more shit and naming collisions.

**Comment by radare** [comment]
i added sys/yara3.sh.. what about having a set of scripts in sys/plugin/yara3 ... to install, uninstall, list, etc we want to be able to install plugins in your home directory or system-wide. we should have a central repository for plugin descriptors and let the user specify new sources and such.

**Comment by jvoisin** [comment]
Or shall we just use scripts, and bundle them all by default?
Or some option in a makefile?

**Comment by radare** [comment]
maybe we can implement this pkgmanager in nodejs or python and make it installable and upgradeable via pip or npm. This way we can also get the benefit of installing multiple versions of r2 in a single command on any platform. something like this:

sudo npm install -g r2pm
r2pm install radare2-git
r2pm install yara
r2pm search decompiler
r2pm upgrade
r2pm list  # list installed packages

…

this pkgmanager can be implemented in shellscript without much difficulty, but maybe making it available via npm or pip will allow users to easily install r2 in their systems without having to mess with specific system pkgmanagers or so.

we can also distribute that r2pm as a standalone script, but another good of pip/npm is that user will be able to upgrade it or have differnt versions installed.

what do you think? pkg management is a mess, mainly because everybody thinks the rest are flawed, and they can do a better one, or just one that abstract others, etc. we are falling into the same issue. just be careful

**Comment by XVilka** [comment]
This looks interesting too https://github.com/tmux-plugins/tpm

**Comment by radare** [comment]
Another option would be to implement r2pm within r2, expose an API and such, but for that simple task i would prefer a shellscript, the only problem here is portability, shellscripts make window users sad.
