### ISSUE TITLE
Trace disassembly not being displayed

### ISSUE THREAD

**Issue by shitsecurity** [radare/radare2#3075]
Hi,

I can't seem to view the disassembly of a trace like in the pic:

![teh trace disasm](http://radare.today/content/images/2015/Apr/tracing.png)

My env: Fedora 22 x86_64 / Debian Jessie x86_64, latest r2 from git installed via sys/install.sh.

What i'm doing:

```
r2 -d /bin/ls
e asm.trace=true
e dbg.trace=true
e asm.tracespace=true
s main
db 0x00402990
dc
dsu 0x004029ba
```

I believe the expected behavior is to see the disasm between 0x00402990 and 0x004029ba.
I guess it's worth noting that `at` displays the addresses of the traced instructions.
`atd` displays `TODO`.

```
[0x00402990]> at
0x7f6bc7c84c80 size=1 count=1 times=1 tag=0
0x00402991 size=2 count=2 times=1 tag=0
0x00402990 size=2 count=3 times=1 tag=0
0x00402992 size=2 count=4 times=1 tag=0
0x00402994 size=2 count=5 times=1 tag=0
0x00402996 size=3 count=6 times=1 tag=0
0x00402998 size=1 count=7 times=1 tag=0
0x0040299b size=1 count=8 times=1 tag=0
0x0040299c size=2 count=9 times=1 tag=0
0x0040299d size=7 count=10 times=1 tag=0
0x0040299f size=3 count=11 times=1 tag=0
0x004029a6 size=9 count=12 times=1 tag=0
0x004029a9 size=8 count=13 times=1 tag=0
0x004029b2 size=2 count=14 times=1 tag=0
[0x00402990]> atd
TODO
```

I also tried tracing using breakpoints:

```
r2 -d /bin/ls
e asm.trace=true
e dbg.trace=true
e asm.tracespace=true
s main
db 0x00402990
dbte 0x00402990
db 0x004029ba
dbtd 0x004029ba
```

`dbt` displays:
```
0  0x7fc5c8fafc05  0  map._usr_lib64_ld_2.21.so.r_x+64517
1  0x7fc5c8627806  96  r10+7306374
2  0x7fc5c862a21a  80  r10+7317146
3  0x7fc5c85e75fb  48  r10+7043707
4  0x7fc5c85e7695  48  r10+7043861
5  0x00404274  16  main+6372
6  0x7fc5c8fa93d4  176  map._usr_lib64_ld_2.21.so.r_x+37844
7  0x7fc5c8fa9b1f  48  map._usr_lib64_ld_2.21.so.r_x+39711
8  0x7fc5c8fa93d4  160  map._usr_lib64_ld_2.21.so.r_x+37844
9  0x7fc5c8fa9b1f  48  map._usr_lib64_ld_2.21.so.r_x+39711
10  0x7fc5c8fa9fb0  240  map._usr_lib64_ld_2.21.so.r_x+40880
```

`at` doesn't display anything.

Is viewing the disassembly of a trace even supported in the current master?

**Comment by radare** [comment]
yes, all the stuff you mention is supported

$ r2 -d ls

e dbg.
e asm.indent=true
e asm.trace=true
e asm.flagsinbytes=true
100ds   # to step into 100 instruction

the indentation depends on the analysis, not the tracing information, i have added a new variable (asm.indentspace) to specify how many spaces you want to use to indent every level. it was hardcoded to 4 before that change.

Also, i have implemented the ‘TODO’ for atd. you will need to prefix the command with a dot, in order to get the disasembly.

about performance, i’ll address some bottlenecks soon, just need to find time to focus on this.

when you are tracing it means that the debugger will record every time the process returns back the control to the debugger (waitpid), if you run ‘dc’ to continue execution you’ll get no traces at all. use tracepoints or just step into to get the tracing information recorded.


hope this helps, let me know if you have more ideas to make tracing better in r2.

**Comment by shitsecurity** [comment]
Kudos for the quick fix, thanks!

Manually stepping works great:
```
r2 -d /bin/ls
db main
dc
e dbg.trace=true
5ds
at
.atd
```

Tracepoints don't toggle the tracing (e dbg.trace=true) mode though:

Toggle to true fail:
```
r2 -d /bin/ls
e asm.indent=true
e asm.trace=true
e asm.flagsinbytes=true
db main
db main+0xf
dbte main
dbtd main+0xf
dsu main+0xf # hit main breakpoint
dsu main+0xf # hit main+0xf breakpoint
at # nothing, expected trace from main to main+0xf
```

Toggle to false fail:
```
r2 -d /bin/ls
e asm.indent=true
e asm.trace=true
e asm.flagsinbytes=true
db main
db main+2
dbtd main+2
dc # hit main breakpoint
e dbg.trace=true # start tracing
5ds
at # traced over main+2 ignoring set dbtd, expected trace from main to main+2
```

**Comment by radare** [comment]
You have to manually toggle it. is this issue fixed for you?

**Comment by radare** [comment]
ping?

**Comment by shitsecurity** [comment]
Sorry for the delay, was afk for a day. Yeah, issue's fixed, closing ticket.

If i can make a suggestion, add some sort of temporary warning that dbte, dbtd, etc don't actually do anything, so people won't waste time trying to get them to work. Also some info about dbg.trace = true and ds tracing would be nice in the official docs.

Thanks again. Best of luck, radare's looking really good!
