### ISSUE TITLE
pd 0 should print 0 instructions

### ISSUE THREAD

**Issue by radare** [radare/radare2#3084]
pd 0 != pd

**Comment by radare** [comment]
Same for `pd`, `px` and many others.

**Comment by Maijin** [comment]
@crowell your patch broke a lot of test

**Comment by radare** [comment]
Please add tests for this. Also, confirm that pd without argument uses blocksize instead of 0

**Comment by jsmnsr** [comment]
The fix provided by @crowell appears to fail those tests because r_num_math will return 0 for all string arguments to p with ascii characters such as what is in the callflag test unit. The if (l == 0 test) { goto beach; } will then catch all instances of p where the parameter to p is '0' or an alphabetical string.

I would like to help fix this issue but I am looking for some guidance regarding the best way.  Should r_num_math return something other than 0 when an ascii string is provided? Should we prevent the call to r_num_math in the case of alphabetical characters?

**Comment by radare** [comment]
No. Absolutely no. Nummath uses a callback to determine the value of alphanumeric words . Those are resolved by core from the flagnames and others.  Both solutions are wrong.

**Comment by radare** [comment]
@maijin can you reference @crowell commit here?

**Comment by Maijin** [comment]
His broken patch is already reference see before ?

**Comment by Maijin** [comment]
ping @jsmnsr

**Comment by jsmnsr** [comment]
I will get a chance to work on this issue some more tomorrow.

**Comment by jsmnsr** [comment]
So is this a problem with num_callback as it is implemented in core?

**Comment by radare** [comment]
No. It is a problem on how is used the argument of pd when calling the disasm loop

**Comment by jsmnsr** [comment]
when the argument of pd == "0" i go to beach. Does this sound like an adequate fix? The failing tests pass now.

**Comment by radare** [comment]
not the argument == “0”, doing this should be the same:

pd 1-1


and the same for flags. this is.. if the result of r_num_math (core->num, input+2); is 0 but input is not “” then goto beach;
