### ISSUE TITLE
Cheat Searching

### ISSUE THREAD

**Issue by radare** [radare/radare2#3086]
Radiff2 should be able to find which words or bytes has changed between two files. Those files can be just heap dumps from a running application. And we need a simple way to find the differences between those two snapshots that match a specific change:
- 1 -> 2
- "foo" -> "bar"

Restrictions like alignedness for keywords should be included, because only aligned values (%4) will be valid addresses for storing numbers or strings.

The implementation of this feature must be available in radiff2, but also inside r2 integrated with the `dms` commands to handle memory snapshots from the debugger.

**Comment by poliva** [comment]
It will be useful to be able to list all offsets whose value has increased or decreased a certain amount, similar to MAME's debugger `cheatnext` command, for example: `cheatnext -,1` will show all offsets whose value has decreased by one (useful when searching for the lives offset in a game, take two snapshots one before and one after being killed, the offset pointing to the number of lifes will decrease its value by one in this example). Being able to specify ranges instead of fixed values will also be nice and useful for game rom hacking.

**Comment by CoolOppo** [comment]
@poliva Take a look at [scanmem](https://github.com/scanmem/scanmem) for a FOSS utility that does what you're looking for.

**Comment by cmhe** [comment]
Also take a look at [Cheat Engine](https://github.com/cheat-engine/cheat-engine). Its in Pascal, but at least has a huge feature set to take some ideas from. Scanmen/GameConqueror is a reimplementation of it, because Cheat Engine runs only native on Windows.

For example it would be great to be able to search for unknown values first, and than limit the number of results by searching for changes. And maybe even support implementing custom types for applications that run within some kind of virtual machine (scripting languages, etc.).

Additionally it would be great to be able to search for multiple values (and changes) in parallel.

But maybe this kind of feature set warrants a new search command?

**Comment by radare** [comment]
from mame:

<img width="544" alt="screen shot 2016-07-28 at 16 40 11" src="https://cloud.githubusercontent.com/assets/917142/17216694/f8c76a48-54e1-11e6-881d-874f3b5bbff6.png">

**Comment by radare** [comment]
This can be done with /x and cx. maybe we dont need any other command of feature.

```
/v 7   # finds 07000000
```
Continue playing the game until we loss a life.
Then compare all the resulting hits with cx to see if it has changed:

```
cv 6 @@ hit0* # will show which hits are now 6 instead of 7
```

**Comment by radare** [comment]
We can now do this too: `?v $$ @@/v4 7`. i think we can close this issue already,
