### ISSUE TITLE
gdb backend can't handle '-d /path/to/file'

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3145]
- [ ] gdb backend can't handle '-d /path/to/file'
  E.g. if run

```
gdbserver localhost:1234 /bin/ls
r2 -D gdb gdb://localhost:1234
```

it starts from the valid address:
`[0x7fffff7ddbc80]>`
But if I add `-d /bin/ls`
it starts from the invalid address:
`[0x000000000]>`
- [ ] Also add the capability to be able not to specify -D gdb each time

**Comment by radare** [comment]
-d is for local debugging. Thats why it fails

**Comment by radare** [comment]
We should define a better approach for debug and emulation backends. Mainly because the debugger can handle them all. 

When you set pass -D gdb it is defining it as a debug plugin of choice. Same as dh command.

Before navajas congress i want to. Implement the esil and unicorn debugger backends. So maybe its a good time to review all this to avoid confusions like this

**Comment by radare** [comment]
Should be fixed already
