### ISSUE TITLE
question: new inverted scroll

### ISSUE THREAD

**Issue by crowell** [radare/radare2#3196]
IMO the new inverted scroll from commit 6f4c06c0e5ff529dce474c0c34931c4c5ed8ac01 makes the ascii graph mode unusable. it inverts scrolling from the rest of everything, especially the h/l horizontal moving.

this should be reverted, anyone else agree or am i alone here?

**Comment by ret2libc** [comment]
They shouldn't have been inverted. There is the option graph.invscroll to
change that thing. That commit wasn't necessary @radare
Il 31/ago/2015 03:26, "Jeffrey Crowell" <notifications@github.com> ha
scritto:

**Comment by radare** [comment]
Oh i though this config var wasnt merged. The idea is that if u press j the disasm must go up and show whats under the current offset. Same as in the disasm mode. I switched that in purpose for testing and having some quick feedback

**Comment by ret2libc** [comment]
@crowell graph.invscroll = true solve the issue?

**Comment by crowell** [comment]
ret2libc: yes it does fix it, but I think it should be the default

**Comment by ret2libc** [comment]
I don't really know. I've been using the new scrolling for a while with the graph.invscroll options, so i'm used to it. I'm not sure there's really a right way for that, it's like the natural scrolling vs the normal one.

I set the graph.invscroll in my radare2rc so far. 

Of course, it wasn't necessary to invert the behaviour because it was already possible to get this same result with that var. I agree to revert the commit just to don't change things too much.

**Comment by radare** [comment]
Yeah i should change that var instead of changing the code. But i think current behaviour makes more sense. but well. its something users must test and expose their feelings with it. But for me 'h' means left, which is moving your eyes to the left of the graph. and 'H' means also left: move the node to the left.

we can asume that we are changing the position of all the nodes if we make 'h' move the graph to the right. that would be something like moving the canvas to the left, instead of moving our eyes. as long as hjkl doest modifies the graph i understand this action as something immutable for the paper we are manipulating with the printed graph, but, when we use uppercase we are modifying the position of one node. so it must follow that logic.

my 5c

**Comment by ret2libc** [comment]
Can we close it? We have the graph.invscroll var that should invert the behavior for any preference...

**Comment by radare** [comment]
Yes
