### ISSUE TITLE
bin_strings buffer is too big

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3262]
https://github.com/radare/radare2/blob/master/libr/bin/bin.c#L253

Why this limit? Is it really necessary?
For example I have a binary with a lot of strings and I cannot find some strings in the binary.

**Comment by radare** [comment]
it is necessary because right now every string found is allocated again, instead of pointed out to the real string, and its also flagged, so it adds too much memory usage for something is not going to be really used, and will make r2 unusably slow. 

Maybe we can set this size configurable by the user.

**Comment by radare** [comment]
Maybe, after sdbizing rflags, this can be optimized enough to be usable, but load time of the bin will be increased

**Comment by ret2libc** [comment]
why is the string allocated again?

**Comment by radare** [comment]
For the flag name at least. And because contents of flags are cached sometimes.

With latest asm.esil.anal thing (copyright pending) we can resolve strings in disasm quite better. Mainly for arm code. But this info is not exposed statically for the xrefs. Because this should be done in aae.

This way we can ignore loading the strings in rbin. And just let them be analyzed by the analysis engine when they are referenced.

Thats why im not sure why we should find strings when loading a bin. Because the user is always able to do that search/list after that by hand.

**Comment by ret2libc** [comment]
What about looking for strings lazely, only the first time they are requested? In this way the loading time will be shorter. Anal can resolve itself the strings it finds in the disasm.

Also it would be cool to have those things done in background by another thread.

**Comment by radare** [comment]
see r2 -t

**Comment by radare** [comment]
Can we have a test case for this thing? no need to get it into the r2r for size reasons

**Comment by ret2libc** [comment]
Eheh I can't find anymore the binary I had problem with :P

**Comment by ret2libc** [comment]
@radare This is already solved by adding an option to specify the Max size, isn't it? Can we close the issue?

**Comment by radare** [comment]
Yes
