### ISSUE TITLE
Error building master branch

### ISSUE THREAD

**Issue by Bl4ckb0ne** [radare/radare2#3423]
Hi, I got this error from the radare2-git in the AUR repo (on archlinux)

``` sh
/home/simon/GitClone/radare2/libr/..//libr/anal/p/anal_x86_cs.c:378:8: error: ‘X86_INS_CLWB’ undeclared (first use in this function)
   case X86_INS_CLWB:
```

Am I missing something or the latest commit fucked it up?

**Comment by XVilka** [comment]
This is because r2 git 'master' supports more modern capstone ('next') branch, which is not packaged on the most systems, so radare2 downloads the specific (well-tested) commit from this branch and builds it inside itself. So removing `--sys-capstone` or so flag from the AUR package for the radare2 will help. This is a not issue of the radare2 itself. Please send this message to the maintainer of fix the package by yourself.

**Comment by radare** [comment]
This should be guarded by an ifdef to check the capstone major/minor versions.

**Comment by radare** [comment]
it should be fine now
