### ISSUE TITLE
Reduce the number of (pedantic) warnings

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#3481]
We've got some continuous integration jobs for radare2 launched upon every commit, and [one of them](http://ci.radare.org/job/radare2-pedantic/) is using the compiler flag `-pedantic`.

It would be great to decrease a bit the number of warnings that it generates ;)

**Comment by Maijin** [comment]
Is this build  used or even read anyway?

**Comment by jvoisin** [comment]
Not really, but it helps tracking down how much our codebase sucks.

**Comment by tigertoes** [comment]
To begin with I'm slowly going to work my way through the low hanging fruit - unused args and other similar related easy wins to start with - #5739 is the first PR of what might be many more to come based on your feedback.

**Comment by Maijin** [comment]
@tigertoes If you could kill the remaining of list (see libr/includes/list.h) in profit of r_list that would be cool :)

**Comment by XVilka** [comment]
Check also results of http://ci.radare.org/job/radare2-scan-build/ - it returns sometimes a bit different warnings.

**Comment by tigertoes** [comment]
@Maijin Thanks, I'll take a look at that after I fix my crap attempt in sdb.
@XVilka I've got scan-build running locally and its output seems to match the CI server's.

**Comment by oddcoder** [comment]
@tigertoes if you are really interested in fixing this kind of issues
you can go with `sys/clang-analyzer.sh`
really powerfull and helpfull 
it will also list warnings in nice html format :)

**Comment by tigertoes** [comment]
@oddcoder Thank you, I found that earlier and I am using a mixture of it and `scan-build ./config CFLAGS+=-pedantic && scan-build -o . make` to pick things apart, as well as using the CI output from the pedantic and scan-build jobs. If there's some particular parts of the codebase you think I should focus my attention on that are fairly straightforward, please let me know.

**Comment by radare** [comment]
see sys/clang-analyzer.sh

**Comment by radare** [comment]
can we close this?

**Comment by jvoisin** [comment]
[650]( http://ci.radare.org/job/radare2-scan-build/clangScanBuildTrend/ ) bugs :D

**Comment by radare** [comment]
any link to see them?

**Comment by jvoisin** [comment]
Just clic on any point

**Comment by radare** [comment]
i dont know how the mouse works. pls provide link

**Comment by jvoisin** [comment]
[here]( http://ci.radare.org/job/radare2-scan-build/1274/clangScanBuildBugs/ )

**Comment by radare** [comment]
404

**Comment by tigertoes** [comment]
`http://ci.radare.org/job/radare2-scan-build/$recent_build_number/clangScanBuildBugs/` ([for example](http://ci.radare.org/job/radare2-scan-build/$recent_build_number/clangScanBuildBugs/ ))

**Comment by radare** [comment]
Ive read the whole list of pedantic warnings of today's master and i think that it's ok to close this issue, the warnings are the following:

* Use variable arguments in CPP macros not being ISO (meh, every single C compiler supports that)
* Enums are 32bit wide (not an issue for any modern compiler afaik (CAN BE FIXED WITH static const ut64 ..)
* Data precision lost caused by assuming 32bit defines
* function pointers cant be assigned to void* (srsly?) dataptr == codeptr in all GP machines
* void*+x is not valid, should be casted to (ut8*) (FIXED IN SDB)
* {} without context - not an issue for any compiler

/libr/asm/arch/xtensa/gnu/xtensa-modules.c:3805:33: error: zero or negative size array 'funcUnits'

im fixing the most important ones and ill close the issue after this

**Comment by radare** [comment]
I think we can close this now. not all pedantic warnings are fixed, because that will require some really bad code, and all compilers it is not an issue what's left.
