### ISSUE TITLE
Fix DES

### ISSUE THREAD

**Issue by condret** [radare/radare2#3499]
thanks to @flanfly we now have a des implementation, that can be used for avr-esil, but it does not always meet the specs. We need to fix that.

**Comment by radare** [comment]
Rhash and rcrypte definitively need some love :)

**Comment by condret** [comment]
we put it in utils, because i was not sure if anal can access crypto, and the plugin-handling in crypto looks like a huge TODO

**Comment by radare** [comment]
ive fixed the static build introduced by the avr-des thing

**Comment by ninjahacker** [comment]
Is there a reason this can't be pulled from something that is already heavily tested and known to work like openssl?

**Comment by radare** [comment]
All crypto algos in r2 has been ripped from other projects that are already tested.i just enforce the code to be readable. Standalone and easily reusable by cleaning up the code and such. Also the length of the code matters, and the cose must be pure C because managing inline assembly and other stuff can result in portability problems.

The main idea behind the r2 project is to maintain a reusable and clean code without external dependencies, but opening the door to support faster or alternative implementations in plugins.

Also. We should have tests to ensure those implementations are correct. And this should be the first thing to have before blindly "fixing des"

**Comment by radare** [comment]
Is this going to happen in a week?

**Comment by flanfly** [comment]
Unlikely

**Comment by Maijin** [comment]
that is very sad.

**Comment by radare** [comment]
Justin Biever is crying right now

**Comment by radare** [comment]
ping

**Comment by flanfly** [comment]
Pong. When will be the next r2 release? I may have a chance to look into this either next weekend or the one after that.

**Comment by XVilka** [comment]
@flanfly it's scheduled to May 23. Btw you can see the milestones here: https://github.com/radare/radare2/milestones

**Comment by radare** [comment]
ping????

**Comment by radare** [comment]
anyone is gonna do this before the end of this week?

**Comment by radare** [comment]
dropping milestone as long as nobody seems t obe interested or willing to fix that

**Comment by wargio** [comment]
I'll fix it asap.

**Comment by radare** [comment]
DES FOR ESIL PLS :D

**Comment by wargio** [comment]
Is there a [regression] test for this bug? so i can reproduce and verify the output of my fix?
