### ISSUE TITLE
rethink ascii-art graph commands

### ISSUE THREAD

**Issue by radare** [radare/radare2#3504]
to move to the basic block of that address

**Comment by ret2libc** [comment]
Just use VVo. 'o' is for that purpose, not 'g'. 'g' is just for shortcuts written in the comments of the disassembly. With 'o' you can go to whatever address you want.

**Comment by radare** [comment]
We should make the VV graph view to work differently:

* 'p' 'P' should rotate between different print modes, like in visual, but adapted to the graph. 
  * debug view (show registers + stack on top) show backtrace?
  * show comments or not
  * show esil or not
  * minigraph
* 'o' and 'O' should goto shortcut or offset .. in visual VO toggles esil .. umf
* 'g' and 'G' should scroll top/down of the canvas like in visual, or just page down/up

please discuss

**Comment by ret2libc** [comment]
I really like the 'p'/'P' commands to rotate between different modes. But I'd also like to keep 'o' for "Goto Offset" because it is consistent between visual and graph and it's one of the command everybody uses more. Now, given that we can't have every char with the same semantic both in visual and in graph mode, I'm not sure about 'g'/'G' because i think we can reuse those chars for more used commands (like 'g' as it is now, for "Goto shortcut"). Also, I don't want to rename 'g' as 'O' because it would require to press shift and it's too slow to be a "shortcut" :P So, my proposal is:

* 'p'/'P' to rotate between different modes as you said.
* 'c' will be used in the future to have a cursor inside a node, like it is in visual mode
* 'o' is for "Goto offset" like it is in visual mode
* 'g' is for "Use shortcut" (we may want to use another char for this, but it would be better to have a lowercase letter)
* 's'/'S' can be used for step/step over (instead of 'z'/'Z') so we will be consistent with visual mode.
* use 'page up'/'page down' to scroll top/down of the canvas. This is not consistent with visual mode, but I also think it isn't one of the thing you usually do in the graph.

**Comment by Maijin** [comment]
Yes definitely agree on "because it would require to press shift and it's too slow to be a "shortcut""

**Comment by radare** [comment]
R2 is not emacs

**Comment by crowell** [comment]
capital letters is a long way off from esc, meta, alt, ctrl <key>, there are already lots of a/A f/F in visual mode...

**Comment by Maijin** [comment]
who speaks about ctrl/meta/alt and ctrl????

**Comment by jvoisin** [comment]
I'm quite sure that @radare was trolling, and you fell for it.

**Comment by radare** [comment]
@ret2libc agree with all those proposals as they are in sync with the current ones in visual. and make change because we are no longer using WASD for moving

**Comment by radare** [comment]
I would like to preserve the 'C' to toggle colors, like in visual. We can maybe use ';' to toggle comments?

Also, i miss a disasm mode in pP with "offset+opcode", looks like asm.bytes variable is ignored, we should probably honor some vars from the user.

In normal visual, the help message says:
```
 r        browse anal info and comments
```

Which is wrong. and in VV this seems to be a redraw. Which looks good to me.

I will try it more and suggest some more changes.

**Comment by ret2libc** [comment]
* C to toggle colors is ok
* ';' to toggle comments is ok imo, as long as when we will implement the cursor inside nodes, ';' will also add comment to a line, like in visual mode
* "offset+opcode" i think i've implemented it. it should be the second print mode
* L for refreshing is ok
* ```ec``` and ```e``` commands: imo for this we should take a better/more general approach. I was thinking about using a publish/subscribe model for env vars, so that we can register a list of callbacks and when that particular var changes, our callback will be called. In this way we can respond to 'ec' command and also to all 'e ...' commands that changes color, comments, bytes, ecc.

**Comment by radare** [comment]
L for refreshing is not ok because we have r and L is part of HJKL

**Comment by radare** [comment]
This subs/callback model is done in rconfig. Also in sdb. And i guess everything can become too bloated in some cases. But it can be useful in some situations. The same when having multiple clients or tasks running in background. The ui (and the webui) need to get notifications to update the affected frames

**Comment by ret2libc** [comment]
Ah right! So we can keep 'r' for refreshing the graph, ok?

Seems like you can have only one getter/setter for each rconfignode in the current implementation, but you may want to have multiple listener to the same event in some cases. In that way you can also handle easily multiple clients/background tasks.

BTW, I will change C for colors and ';' for comments, then we can close this issue, can't we?

**Comment by radare** [comment]
Yep. Make those changes and close the issue :) lets go for the next ones. Fix segfaults and enhace pfd
