### ISSUE TITLE
Add support for punycode encode/decode

### ISSUE THREAD

**Issue by radare** [radare/radare2#3512]
https://nodejs.org/api/punycode.html

I think there was another issue related to this but i cant find it now

**Comment by lionaneesh** [comment]
I am willing to work on this one. Do we implement this in rahash2?

**Comment by radare** [comment]
this must be done libr/util/punycode.c but i think it will be more useful to have it in the r2 shell (and | or) rax2, not rahash2

**Comment by radare** [comment]
We can probably take the code from here https://github.com/bnoordhuis/punycode

but i cant get this thing to work. first its using uint32 arrays for input strings .. when the maximum value set is 0xfc, so bytes should be enough. but even after converting that array i cant get a single emoji converted..

**Comment by radare** [comment]
@lionaneesh are you on this?

**Comment by radare** [comment]
The signature we should use must be like this:
```
R_API char *r_punycode_encode(const char *src);
R_API char *r_punycode_decode(const char *src);
```

**Comment by Maijin** [comment]
@P4N74 ^

**Comment by P4N74** [comment]
I am almost done with this. Two things are remaining: 1) the decode function is not working for half the test case. 2) run it in r2 shell (this won't take much time).

**Comment by radare** [comment]
try with valgrind, maybe there are some oob reads/writes.

also, if the tests are not passing does it means that library is buggy? (i though that when i was testing it)

**Comment by P4N74** [comment]
I compared the algorithm with the one given in https://tools.ietf.org/html/rfc3492 so as far as I can tell, it's not buggy. The problem is coming after converting the code to utf8 instead of utf16. Though there might be some other changes required which I will have to look up on.

I didn't understand the valgrind stuff about oob reads/write. Infact I don't know about it.

**Comment by radare** [comment]
just run your code with valgrind and see if there’s any warning

**Comment by radare** [comment]
see http://llvm.org/svn/llvm-project/llvm/trunk/lib/Support/ConvertUTF.c <http://llvm.org/svn/llvm-project/llvm/trunk/lib/Support/ConvertUTF.c>

**Comment by radare** [comment]
i would prefer not to depend on libiconv :)

**Comment by P4N74** [comment]
@radare there is a minor bug in the library we are ripping the code from. I don't know how https://github.com/bnoordhuis/punycode/blob/master/test-punycode.c#L86 ain't giving error even though the 16 character is actually 249 (0xf9) in decimal instead of 252 (0xfc). I checked it using a simple printf statement. Please confirm this so that I can understand whether the library is buggy or my modification is causing the error.

**Comment by P4N74** [comment]
Never mind, I have fixed the bug in decode and updated the PR :)
