### ISSUE TITLE
Finding addresses in a binary with fork

### ISSUE THREAD

**Issue by eQu1NoX** [radare/radare2#3524]
When I open up a process that forks in the debugger, something strange happens. It does not seem to analyze/pick up entry point properly.

```bash
$ cat test.c
#include <stdio.h>


int main(int argc, const char *argv[])
{
  if (fork()) {
    printf("one");
  }
  else
    printf("anotehr");
  return 0;
}
$ gcc -o test test.c
$ r2 test
 -- Find wide-char strings with the '/w <string>' command
[0x00400490]> aa
[0x00400490]> afl
0x00400490  42  1  entry0
0x00400460  6  1  sym.imp.__libc_start_main
0x0040057d  63  4  sym.main
0x004004c0  41  4  sym.deregister_tm_clones
0x004004f0  57  4  sym.register_tm_clones
0x00400530  28  3  sym.__do_global_dtors_aux
0x00400550  45  4  sym.frame_dummy
0x00400630  2  1  sym.__libc_csu_fini
0x00400634  9  1  sym._fini
0x004005c0  101  4  sym.__libc_csu_init
0x00400418  26  3  sym._init
0x00400470  6  1  fcn.00400470
0x00400450  6  1  sym.imp.printf
0x00400480  6  1  sym.imp.fork

# Now something strange happens
$ r2 -d ./test
Process with PID 2186 started...
Attached debugger to pid = 2186, tid = 2186
Debugging pid = 2186, tid = 2186 now
Using BADDR 0x400000
Assuming filepath /usr/bin/./test
bits 64
Attached debugger to pid = 2186, tid = 2186
 -- Now featuring NoSQL!
[0x7f9e605992d0]> aa
Cannot find function 'entry0' at 0x00401708
[0x7f9e605992d0]> afl
```

**Comment by radare** [comment]
radare is a low level debugger. (again)

this means that you start debugging BEFORE the binary is loaded in memory.

run `dcu entry0` before that `aa`, but i would recommend you to use aaa or aac, or any other analysis that works better for that case. but anyway, thats unrelated tot he problem.

Also, if you have dbg.forks enabled, the debugger will stop in the fork if you run `dc`. so you can just catch that place. otherwise you can just perform a proper analysis of fork, find backrefs and analyse the parts that are using it with aar, /r or pd~fork.

PD: i guess you are using r2 from git? can you specify platform at least? or arch?

**Comment by eQu1NoX** [comment]
Thanks for your reply. A few points.

1. r2 from git, x64 is used.
2. Perhaps we can change documentation on https://github.com/radare/radare2/wiki/Migration-from-ida-or-GDB ? It maps "set follow-fork mode" in gdb to "dcf ; dp". Maybe we can change that to [4].
3. 
```bash
$ r2 -d ./test
Process with PID 2511 started...
Attached debugger to pid = 2511, tid = 2511
Debugging pid = 2511, tid = 2511 now
Using BADDR 0x400000
Assuming filepath /usr/bin/./test
bits 64
Attached debugger to pid = 2511, tid = 2511
 -- This is an unacceptable milion year dungeon.
[0x7fb9827372d0]> dcu entry0
Continue until 0x00401708
oneDebugging pid = 2511, tid = 1 now
[0x7fb982432309]> aaa
Cannot find function 'entry0' at 0x00401708
Cannot determine xref search boundaries
```

4. I tried doing the following as you suggested and it works, thanks.
```
e dbg.forks=1
dc
```
