### ISSUE TITLE
use all cores in /sys/install.sh (make -j 8 for example)

### ISSUE THREAD

**Issue by condret** [radare/radare2#3536]
i don't do shellscripts very often, so i'm not sure if this is possible.

**Comment by XVilka** [comment]
probably determine it on the fly with 
```
grep -c "processor" /proc/cpuinfo
```
command, that's only for Linux though...

**Comment by condret** [comment]
i now how you can determine the number of cores in windows, but only in c

**Comment by crowell** [comment]
Also nproc

**Comment by jvoisin** [comment]
Just use `make -j`

**Comment by jjdredd** [comment]
```
If the  -j  option  is given without an argument, make will not limit
the number of jobs that can run simultaneously.
```

Sounds  overkillish and oomish.

**Comment by crowell** [comment]
No this is a terrible idea make -j can bring your system to a halt

**Comment by crowell** [comment]
make -j $(nproc+1) is usually what it recommended.

**Comment by CoolOppo** [comment]
you mean `make -j $(nproc)+1` right? or am i wrongo

**Comment by radare** [comment]
This is already done

**Comment by radare** [comment]
The nproc+1 rule is like swap=ram*2 rule. Both were invented when the pentium pro ruled the world. Nowadays it makes no sense to follow those rules. Mainly because almost every processor have 2 cores, so you end up having to do nproc*2.. But thats not true for arm, etc etc. so as long as every arch performs different is better to keep a sane value like the current hardcoded -j8

**Comment by radare** [comment]
You can fix this with hardware

**Comment by radare** [comment]
About how to get the amlunt of cpus is something useless. As explained in my prev reply. Every os provides this info different. And each cpu model and arch responds diferent. And the build system also, doesnt paralelixes in all situations because there are some blocker steps that halt that performance a bit.

Do not try to mess with c code to determine the number of cpus. Just use MAKE_JOBS or use the default -j8 provided by sys/build.sh

**Comment by jjdredd** [comment]
imho 8 is too much for default

**Comment by radare** [comment]
@jjdredd my current machine have 6 cores with hyperthreading, which means i can spawn 12 threads. Setting up more tasks than the ones supported by the hardware is not really a performance problem. It only takes some more memory. And well. if -j8 is making your raspberrypi fail (which is not even happening) you can override this value with the MAJE_JOBS environment.

**Comment by condret** [comment]
Hello!

 

You have a new message, please read <http://miglas.valsts.lv/equality.php?6xye>

 

lukas-runas@gmx.de

**Comment by condret** [comment]
Hey,

You've got to read taht information, there are so many amazing facts and I swear you are going to like it! Just read it here <http://aim.caspergroup.us/lnihy>

Speak to you later, lukas-runas@gmx.de

**Comment by radare** [comment]
Omg condret not again

**Comment by condret** [comment]
Hi,

Since our last conversation I've  been looking for that stuff and  I found it at last!  Take a look  here  <http://fact.ondernemenmetkleur.org/lnwev>

Be well, lukas-runas@gmx.de
