### ISSUE TITLE
assembling instructions containing '#-'

### ISSUE THREAD

**Issue by mrmacete** [radare/radare2#3698]
Encountered this issue while developing the assembler for BPF arch, but it may affect other archs using '#' char to declare immediate values, the problem is the following:

```
[0x00000000]> pa ld #-1
Cannot assemble 'ld' at line 3
[0x00000000]> "pa ld #-1"
Cannot assemble 'ld' at line 3
[0x00000000]> `pa ld #-1`
Cannot assemble 'ld' at line 3
[0x00000000]> 
```

It seems that '#' char acts as a comment, **when it is not followed by a digit**, while this works:

```
[0x00000000]> pa ld #69
0000000045000000
```

same behaviour also using the 'waf' command reading instructions from a text file.

Actually, in the failing case, the plugin's assemble function receives a char*buffer which terminates at the position of '#'.

**Comment by radare** [comment]
quote the whole line like “pa ld #-1” or just use a decent syntax like I did for arm and others dropping all those useless chars that only complicate the parser :)

**Comment by mrmacete** [comment]
mmm... quotes seems to not solve the problem. yeah i could go for a #-less syntax, it is not copy-and-paste safe for the user, though :/

**Comment by radare** [comment]
oh right. because the # is handled by rcore.cmd and rasm.assemble… you should drop that syntax from the disassembler too. so it will be copypaste friendly. 

i would prefer assemblers disassemblers in r2 not to have those chars in there, because they just collide with r2 command syntax (as wel well as rasm one, and many others one).

so i wuld suggest you to make this change, but it makes sense to handle negative numbers after ‘#’ in the assembler. you can fix this here:

(libr/asm/asm.c line 565)

      ptr = strchr (ptr_start, '#'); /* Comments */
      if (ptr && !R_BETWEEN ('0', ptr[1], '9'))
                 *ptr = '\0';

can you send a pr after testing the fix it with your assembler?

it should be just checking if ptr[1] != ‘-‘ in the same if line

**Comment by mrmacete** [comment]
sure! ;)
