### ISSUE TITLE
Fix asm.bbline

### ISSUE THREAD

**Issue by radare** [radare/radare2#3739]
* [x] fix reflines when bbline=true
* [x] blocks are not correctly splitted

**Comment by ret2libc** [comment]
Not utf8 related...

**Comment by radare** [comment]
utf8 is part of the problem, just try it

**Comment by ret2libc** [comment]
<img width="479" alt="screen shot 2015-11-23 at 15 58 09" src="https://cloud.githubusercontent.com/assets/562321/11339743/36e885dc-91fb-11e5-8f35-a1d17c273b3d.png">
<img width="494" alt="screen shot 2015-11-23 at 15 58 26" src="https://cloud.githubusercontent.com/assets/562321/11339749/3be610fe-91fb-11e5-9fe4-aeb33aae9891.png">

Problems are still there with and without utf8

**Comment by jjdredd** [comment]
I think the issue is in redundant "---" line at bbline delimiter "|". It disappears in ascii case.

**Comment by jjdredd** [comment]
I'll make a patch later today to illustrate my point.

**Comment by jjdredd** [comment]
btw nice colors @ret2libc

**Comment by jjdredd** [comment]
https://github.com/jjdredd/radare2/commit/36b52d9d1f62cba9020bfe81a435dd020ef66c30

here's a demo:

**without** the patch:

![r2_pic_wo_patch](https://cloud.githubusercontent.com/assets/4748239/12013143/bfbe4d14-accd-11e5-87f3-883ab0045ffd.png)

**with** the patch:

![r2_pic_wpatch](https://cloud.githubusercontent.com/assets/4748239/12013144/c94927f0-accd-11e5-8b1f-9c99ec53341a.png)

**Comment by jjdredd** [comment]
if it solves at least a part of the problem i'll make a pr

**Comment by ret2libc** [comment]
Does it fix also the splitting in blocks? Or only the refline?

**Comment by jjdredd** [comment]
only reflines, I didn't understand the second issue.

**Comment by radare** [comment]
I see ascii art better than utf8. @ret2libc

**Comment by radare** [comment]
Send pr plz

**Comment by ret2libc** [comment]
I keep seeing things wrong here.
With utf8=false:
<img width="1280" alt="screen shot 2016-01-02 at 19 20 45" src="https://cloud.githubusercontent.com/assets/562321/12075646/5d5a05ce-b186-11e5-860a-830c784ca304.png">
(you can see there is the '\' char in the fcn reflines instead of '|'. Moreover just after 0x1000011f0, there is a missing '|' in the reflines)
With utf8=true:
<img width="1280" alt="screen shot 2016-01-02 at 19 20 51" src="https://cloud.githubusercontent.com/assets/562321/12075648/6b4f4e3c-b186-11e5-9904-19a3cc787a3c.png">
(you can still see the missing '|' in the reflines)

Also, some basic blocks are not split in the right way. For example, the basic block at 0x1000011a1 has the '|' before, while the basic block at 0x1000011a6 has the '|' after.

**Comment by ret2libc** [comment]
This was fixed a while ago
