### ISSUE TITLE
issue with pfv in mach?

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#3771]
Step to reproduce

```
macbook:r2 alvaro_fe$ r2 -nn /bin/ls
 -- prove you are a robot to continue...
[0x00000000]> pfv.mach0_
pfv.mach0_header    pfv.mach0_cmd_0     pfv.mach0_segment   pfv.mach0_cmd_1
pfv.mach0_cmd_2     pfv.mach0_cmd_3     pfv.mach0_cmd_4     pfv.mach0_cmd_5     pfv.mach0_cmd_6
pfv.mach0_cmd_7     pfv.mach0_cmd_8     pfv.mach0_cmd_9     pfv.mach0_cmd_10    pfv.mach0_cmd_11
pfv.mach0_cmd_12    pfv.mach0_cmd_13    pfv.mach0_cmd_14    pfv.mach0_cmd_15    pfv.mach0_cmd_16
pfv.mach0_cmd_17
[0x00000000]> pfv.mach0_header
[0x00000000]> pf.mach0_header
     magic : 0x00000000 = 0xfeedfacf
   cputype : 0x00000004 = 0x01000007
cpusubtype : 0x00000008 = 0x80000003
  filetype : 0x0000000c = 0x00000002
     ncmds : 0x00000010 = 18
sizeofcmds : 0x00000014 = 1800
     flags : 0x00000018 = 0x00200085
[0x00000000]>
```

There is a test in r2r (inside `t/cmd_pf`) but to me it seems wrong 

```
macbook:pe alvaro_fe$ r2 ch22.exe
 -- SHALL WE PLAY A GAME?
[0x00404f3e]> e asm.bits=32
[0x00404f3e]> s 0x80
[0x00000080]> pfv.pe_nt_image_headers32.optionalHeader.dataDirectory[5].virtualAddress
0x00004550Sat May 29 12:09:36 20109882873160Register (null) does not exists
```
There should be space between `0x00004550` and `Sat ..` , `2873160` and `Register`

**Comment by jvoisin** [comment]
@Hyask Do you want to take a look at it?

**Comment by Hyask** [comment]
Yep, sure, I'll take a look during the week!

**Comment by radare** [comment]
Awesome! 👍

**Comment by Hyask** [comment]
I've no way to make some test with MacOS, but your output seems correct to me.

Your problem with `pfv` is that you use `pfv` (lol), that displays only the value, and is useful for scripting, not really for humans.

iirc, it does not display in the same buffer, that's why you see nothing, but try ```echo `pfv.mach0_header` ```. 
I've tried with a random mach0 file, and it correctly displays that value, but this is awkward for a human, since it display all the values like this: `0xfeedfacf0x010000070x800000030x000000021115360x00000085`... 

As I said, the utility of `pfv` comes when you need to get a particular offset|value|other stored in a binary, in a r2 script...

Concerning the test, you're trying to display a structure that is not loaded. The test adds the `-nn` argument when invoking r2, which gives `r2 -nn ch22.exe`. This loads the binary structures in r2 when launching. Otherwise, you can load it manually with `pfo pe32`.

Skia
