### ISSUE TITLE
ELF: no imported functions identification

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3774]
On this binary: https://github.com/ctfs/write-ups-2015/tree/master/nuit-du-hack-ctf-quals-2015/reverse/clark-kent r2 fails to correctly identify imported functions. 
This is probably because the binary doesn't have section header information.

**Comment by ret2libc** [comment]
test added https://github.com/radare/radare2-regressions/commit/a97cc46458f7ba49872ddbe9a247894061f45621

**Comment by ret2libc** [comment]
@alvarofe The tests main_nosect works great! But I will add another test about this issue, because on the binary clark-lent (https://github.com/ctfs/write-ups-2015/tree/master/nuit-du-hack-ctf-quals-2015/reverse/clark-kent) it doesn't work :( do you have any idea why?

**Comment by alvarofe** [comment]
With the binary main_nosect we were not parsing the the program header and extracting sections such as `rel.plt` and `rela.plt` that are later used on `get_import_addr`. To address that I incorporated `get_sections_from_phdr` (though the interpreation of DT_JMPREL and so it's not very clear on the code that I added because of I am not able to interpret it correctly yet it seems). If you go to 2-12 in [ELF format](http://www.skyfree.org/linux/references/ELF_Format.pdf) you will see the meaning of each field.

I faked a little bit the meaning of them to fix the `main_nosect` test thinking that that interpreation will be the correct. But the new binary uses DT_PLTREL to specify that use `DT_REL` entries so a section `.rel.plt` should exist but in this case there is no such section causing a failure in the function `get_import_addr`.

I should review more closely `get_sections_from_phdr` and interpret correctly each field.

**Comment by radare** [comment]
Ok

**Comment by alvarofe** [comment]
Reading a little more about this 

```
DT_RELA
This element holds the address of a relocation table, described in Chapter 4. Entries
in the table have explicit addends, such as Elf32_Rela for the 32-bit file class or
Elf64_Rela for the 64-bit file class. An object file may have multiple relocation
sections. When building the relocation table for an executable or shared object file,
the link editor catenates those sections to form a single table. Although the sections
remain independent in the object file, the dynamic linker sees a single table
```

```
DT_PLTREL
This member specifies the type of relocation entry to which the procedure linkage
table refers
```

i think my workaround is not bad since as i understand this the loader merge `.rel` and `.rela` sections and interpret it as `Elf_(Rel)` or `Elf_(Rela)` according to `DT_PLTREL`. Therefore, if `DT_PLTREL` is `DT_REL` we should find `.rel.plt` section and if we don't have that section just use `.rela.plt` and read from it `Elf_(Rel)` entries and the inverse is applied with `DT_PLTREL == DT_RELA`

This can be proven wrong until @ret2libc find a new binary ;). In that case reopen this issue or open a new one. At least we know where to look and what code improve.

I will add the latest one to r2r to make sure it will not be broken in the future.

If there is not any inconvenient i will close this issue

**Comment by radare** [comment]
awesome! :)

nice catch. we shuold add some more tests to handle this case.

thanks

**Comment by ret2libc** [comment]
Thanks a lot ;) sounds good, I will try it soon

> Il giorno 09 dic 2015, alle ore 19:35, radare <notifications@github.com> ha scritto:
> 
> awesome! :)
> 
> nice catch. we shuold add some more tests to handle this case.
> 
> thanks
>
