### ISSUE TITLE
Setup clang-format for radare2

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#3811]
After I read this [BoringSSL](https://www.imperialviolet.org/2015/10/17/boringssl.html) i set up vim to use clang-format https://github.com/alvarofe/dotfile/commit/020a5d8d706919fb8d17101d68f7b79285b8b213. I extracted the info from the  file that exist inside r2 repo but I changed the `ColumLimit` to 78. I think we should fix this and apply it throughout the source code. 

I suggest testing different configurations and discuss to come up with the better that fits our requirements. 

```
Language: Cpp
MaxEmptyLinesToKeep: 1
SpaceBeforeParens: Always
SpaceInEmptyParentheses: false
BasedOnStyle: LLVM
ContinuationIndentWidth: 8
IndentCaseLabels: false
IndentFunctionDeclarationAfterType: false
IndentWidth: 8
UseTab: Always
IndentCaseLabels: false
ColumnLimit: 78
BreakBeforeBraces: Attach
BreakBeforeTernaryOperators: false
AllowShortIfStatementsOnASingleLine: true
AllowShortCaseLabelsOnASingleLine: true
AllowShortFunctionsOnASingleLine: Inline
AllowShortLoopsOnASingleLine: true
```

**Comment by jvoisin** [comment]
Why are you not using [vim-plug]( https://github.com/junegunn/vim-plug ) like normal people instead of maintaining your modules by hand :/

**Comment by jvoisin** [comment]
Why `Language: Cpp`?

**Comment by alvarofe** [comment]
http://clang.llvm.org/docs/ClangFormatStyleOptions.html

Language: Cpp is used for C,Cpp, Objective-C and so there is not C option there

**Comment by alvarofe** [comment]
I never heard of `vim-plug` :( I use pathogen instead. I will check it out

**Comment by radare** [comment]
your clang-format keeps bugging the same problems as the one i pushed in doc/clang-format. In fact the reason for not using column=78 is because it chops function definitions which is really bad for grepping function signatures and that fuckups my workflow.

Maybe we can just write a script that runs clang-format and then tweaks a bit the output to fit our needs, i dont think clang-format is gonna be ready for us anytime soon. and if we fix that in master distros will keep using old versions.

Also, the root problem of that clang-format is that when a line exceeds the width it wraps the line and the next one starts right after the parenthesis of the above line, when this happens, if a function have many parameters you'll get a column of one word by line.

Also there are other wrong indentations like this:
```
-	row = malloc (w + 1);
+	row = malloc (w+1);

**Comment by radare** [comment]
```
+		row[0] = roundcorners ? '\'' : corner;
```

**Comment by radare** [comment]
i have pushed a sys/indent.sh which fixes some of those issues, we can probably start defining a handmade whitelist of files that must be indented because we know they are properly indented using this script.

```
$ sys/indent.sh
Usage: indent.sh [-i|-u] [file]
 -i - indent in place (modify file
 -u - indent in place (modify file
```

**Comment by radare** [comment]
Here's another problem with clang-format
<img width="397" alt="screen shot 2015-12-08 at 11 58 44" src="https://cloud.githubusercontent.com/assets/917142/11654064/258e9994-9da3-11e5-9ab8-73a875bc9026.png">

**Comment by radare** [comment]
you can just add a key map to run this script on the currently loaded file, thats pretty easy to do, just one line in the vimrc.

you can use ctags or cscope if you like. im just too lazy because

* i have to update the databases pretty frequently
* grep is more than enough all the time
* i always forget the keys to use ctags from vim
