### ISSUE TITLE
Local symbols not flagged

### ISSUE THREAD

**Issue by radare** [radare/radare2#3852]
As discussed in https://twitter.com/chaosdatumz/status/677034975447748609

**Comment by ChaosData** [comment]
For reference, I was using the level01 binary from http://io.smashthestack.org/ (`scp level1@io.smashthestack.org:/levels/level01 ./` [level1:level1]). (It has also helped with a few other ones.) This particular binary is mostly hand-coded assembly, so the "functions" it has don't really have proper function preludes and likely aren't otherwise being picked up during analysis (nor `aap` [though I assume that it would probably do the trick if they had them]).

```
$ rabin2 -s level01
[Symbols]
vaddr=0x0804809f paddr=0x0000009f ord=005 fwd=NONE sz=0 bind=LOCAL type=NOTYPE name=fscanf
vaddr=0x080480bc paddr=0x000000bc ord=006 fwd=NONE sz=0 bind=LOCAL type=NOTYPE name=skipwhite
vaddr=0x080480c3 paddr=0x000000c3 ord=007 fwd=NONE sz=0 bind=LOCAL type=NOTYPE name=doit
vaddr=0x080480d3 paddr=0x000000d3 ord=008 fwd=NONE sz=0 bind=LOCAL type=NOTYPE name=exitscanf
vaddr=0x080480dc paddr=0x000000dc ord=009 fwd=NONE sz=0 bind=LOCAL type=NOTYPE name=YouWin
vaddr=0x08048103 paddr=0x00000103 ord=010 fwd=NONE sz=0 bind=LOCAL type=NOTYPE name=exit
vaddr=0x0804810f paddr=0x0000010f ord=011 fwd=NONE sz=0 bind=LOCAL type=NOTYPE name=puts
vaddr=0x08048080 paddr=0x00000080 ord=012 fwd=NONE sz=0 bind=LOCAL type=NOTYPE name=main
vaddr=0x08049128 paddr=0x00000128 ord=013 fwd=NONE sz=0 bind=LOCAL type=NOTYPE name=prompt1
vaddr=0x0804914d paddr=0x0000014d ord=014 fwd=NONE sz=0 bind=LOCAL type=NOTYPE name=prompt2
vaddr=0x0804919d paddr=0x0000019d ord=015 fwd=NONE sz=0 bind=LOCAL type=NOTYPE name=shell
vaddr=0x08048080 paddr=0x00000080 ord=016 fwd=NONE sz=0 bind=GLOBAL type=NOTYPE name=_start
vaddr=0x080491a4 paddr=0x080491a4 ord=017 fwd=NONE sz=0 bind=GLOBAL type=NOTYPE name=__bss_start
vaddr=0x080491a4 paddr=0x080491a4 ord=018 fwd=NONE sz=0 bind=GLOBAL type=NOTYPE name=_edata
vaddr=0x080491a4 paddr=0x080491a4 ord=019 fwd=NONE sz=0 bind=GLOBAL type=NOTYPE name=_end

15 symbols
$ rabin2 -sr level01
fs symbols
f sym._start 0 0x08048080
f sym.__bss_start 0 0x080491a4
f sym._edata 0 0x080491a4
f sym._end 0 0x080491a4
```

The script (https://gist.github.com/ChaosData/99454931b5afa838f65b ; it really is just a hacky `python -c` one-liner put in a file) I wrote can totally lead to weirdness with real things as it doesn't even look at the bind value. Though my own version now dumps everything into "losym.xxx". Based on what you need, I'm not sure if it's a proper solution to try and put them into a local symbol flagspace or use separate prefixes for them.

What's your take on this? You mentioned that local symbols were "causing some problems with object and arm elfs." Can you elaborate a bit? Duplicate names for different addresses or symbol/flag pollution of some sort?

**Comment by radare** [comment]
Related https://github.com/radare/radare2/issues/3684

**Comment by radare** [comment]
Added tests https://github.com/radare/radare2-regressions/commit/017172fa915d4e677ee8860a70cd954ba5f31c93

**Comment by radare** [comment]
i have added another test in the midflags script for the antidisasm trick thing

**Comment by radare** [comment]
@alvarofe why didyou closed the pr? :D
