### ISSUE TITLE
Add command to find missing edges in function graph

### ISSUE THREAD

**Issue by radare** [radare/radare2#4024]

**Comment by ret2libc** [comment]
What do you mean that they are "wrongly generated"?
If the analysis is correct and the basicblocks are connected, then there is a bug in `graph.c` somewhere, in the part that creates the graph from the anal info.
If the code of the graph is correct, then there is a bug in the analysis.

So i don't see how a new command can help in either of these cases. I think that the problem is very likely in the analysis :P

If you create manually some functions you should also connect them by using analysis commands, not graph commands.

**Comment by radare** [comment]
yeah, the thing is not having bugs in the graph generation. but yeah, there's no real use case for end users i guess..

**Comment by ret2libc** [comment]
Can you show me an example where the graph fails but the analysis is right? Or just a case where the graph is wrong(missing edges and so on)

**Comment by radare** [comment]
yep just a random case. i dont have a reproducible case.
