### ISSUE TITLE
Read/write memory by blocks in remote debug engine (GDB)

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4038]
Currently, for operations like scrolling in visual mode, or single stepping, via GDB protocol, it requests memory readings byte-by-byte, this is one of the reasons it is so slow.

**Comment by radare** [comment]
Iirc it does reads in blocks of 4096 bytes. Maybe im wrong...

**Comment by XVilka** [comment]
I can attach the log. It supposed to use blocks, but...

**Comment by radare** [comment]
r_io can do reads at any size, the io plugin can do another thing internally, so it is possible that maybe r2 requests a 4 byte read, but io-gdb is internally doing a 4096 byte read. but from what i’ve seen it looks like the main bottleneck is in the poll() performed in libgdbr, because it needs to wait 250ms on every read in order to not miss any packet.

**Comment by XVilka** [comment]
I'll attach the log of the GDB reads once I'll get an access to Linux machine

**Comment by radare** [comment]
ping

**Comment by XVilka** [comment]
http://xvilka.me/example23.txt - it shows scrolling in `r2 -a avr -D gdb gdb://localhost:1212` attached to simulavr.

**Comment by XVilka** [comment]
This is what @SrimantaBarua is doing, from what I understood.

**Comment by radare** [comment]
Yep

**Comment by SrimantaBarua** [comment]
Right now gdb reads in blocks limited by max packet size specified by gdbserver. If gdbserver doesn't specify max packet size, default is 16 bytes (for something like simavr). So if reads of 1-2 bytes are happening, that is because radare wants to make small reads. This will be solved by io caching.

**Comment by radare** [comment]
Isnt 16 too small? I guess that combined with noack it shouldnt be a big issue but i assume this is a way to be safe. Maybe having an =! Io system command to get and set that packet size

**Comment by SrimantaBarua** [comment]
It probably is. I only did 16 because in [#7692](https://github.com/radare/radare2/pull/7692) you had limited memory read size to 8. But yes, having it configurable makes sense

**Comment by XVilka** [comment]
I agree on adding an option. May be just do something like `e dbg.gdb.pktsz = 1024`? Instead of inventing commands.

**Comment by radare** [comment]
Io plugins cant access eval vars. Better to just use the io-system interface for this

**Comment by SrimantaBarua** [comment]
Or maybe `e dbg.pktsz` with a callback that sets something like `core->io->pktsz`

**Comment by XVilka** [comment]
@SrimantaBarua @radare this is exactly what I meant

**Comment by XVilka** [comment]
@SrimantaBarua so what you decided to do with that?

**Comment by SrimantaBarua** [comment]
Now I think it's actually better to use the IO system with =!. I hadn't read @radare 's comment properly and yeah, it will be messy to access the IO plugin on setting the config var. Will send fix by tonight

**Comment by SrimantaBarua** [comment]
Ref #7961

**Comment by XVilka** [comment]
@SrimantaBarua so can be this safely closed? Or there are some missing pieces?

**Comment by SrimantaBarua** [comment]
I'd say it can be closed
