### ISSUE TITLE
list syscalls in from binary?

### ISSUE THREAD

**Issue by JohnDoe1234123** [radare/radare2#4042]
Hey,

how to list all syscalls from a given binary? 

Joe

**Comment by radare** [comment]
Not sure what you mean but /c syscall will help i guess.

Then if u want to get which system call is used on every syscall instruction you'll need to enable asm.emu and collect the value of rax at that point.. Which can be done with pd and ~.

If u need something more specific write an r2pipe script that performs this stuff instead of the oneliner im suggesting

**Comment by Maijin** [comment]
`dcs*` : trace all syscalls (strace)
?

**Comment by l4l** [comment]
That's need bin launch and just list called syscalls @Maijin

**Comment by condret** [comment]
you can't list all syscalls used by the bin only from information taken from static analysis. U need execution or emulation for this. ````int 0x80```` how do you know the value of eax at that instruction, without using emulation or exectution?

**Comment by nwmcsween** [comment]
This is actually quite possible and has been done here: http://www.springer.com/cda/content/document/cda_downloaddocument/9783319279978-c2.pdf?SGWID=0-0-45-1545170-p177846884

**Comment by Maijin** [comment]
It's already implemented.

**Comment by Maijin** [comment]
Use | /s                      search for all syscalls in a region (EXPERIMENTAL)
