### ISSUE TITLE
Incorrect emulation of rep stosq

### ISSUE THREAD

**Issue by sushant94** [radare/radare2#4421]
Binary: Ubuntu 14.04 /bin/ls
Instruction: rep stosq qword [rdi], rax
ESIL:
Offset: 0x407435

| REGISTER | GDB | ESIL |
| --- | --- | --- |
| rcx | 0x18 -> 0x17 | 0x18 -> 0x18 |
| rdi | 0x61c0c0 -> 0x61c0c8 | 0x61c0c0 -> 0x61c0c0 |
| rip | 0x407435 -> 0x407435 | 0x407435 -> 0x407438 |

**Comment by condret** [comment]
i'm not sure, but the esil should be something like this:
````
0,rcx,==,$z,zf,=,zf,?{,BREAK,},rax,rdi,=[8],8,rdi,+=,rcx,--,LOOP
````

**Comment by radare** [comment]
can you test again? cc @skuater

**Comment by radare** [comment]
PING anyone is alive?

**Comment by radare** [comment]
can you sahre an example about this issue in r2 commands?

**Comment by SrimantaBarua** [comment]
The issue is that in struct `RStrBuf`, it's hard-coded as `char buf[64];`. The esil for `rep stosq` and similar are I think correctly generated.  `rep stosq` -
```rcx,!,?{,BREAK,},rax,rdi,=[8],df,?{,8,edi,-=,},df,!,?{,8,edi,+=,},rcx,--=,rcx,?{,5,GOTO,}```
But they exceed 64 characters. So they are stored in `char *ptr`. But during emulation, esil only checks `char buf[64]`.
We could either extend `buf` to ~80 chars, or change esil emulation so that it checks if `ptr` is NULL and if not then emulates `ptr` instead of `buf`. So which would be a better solution?

**Comment by radare** [comment]
cc @skuater we need tests here

**Comment by skuater** [comment]
At moment the best solution is check at emulation if ptr is NULL and emulate from ptr, as you comment.
@SrimantaBarua can u fix this?

**Comment by SrimantaBarua** [comment]
Sure, will do

**Comment by SrimantaBarua** [comment]
I think someone already fixed this. Added a test [here](https://github.com/radare/radare2-regressions/pull/756) anyway, in case one wasn't already written.

**Comment by Maijin** [comment]
Cool thanks !
