### ISSUE TITLE
How to extract instruction operands data?

### ISSUE THREAD

**Issue by AriEi4** [radare/radare2#4456]
Hi,

I'm working with r2pipe in order to programatically extract instructions' data from a function.  Is it possible to extract data about the operands of an instruction? (Similar to GetOperandValue / GetOpType in IDA)

I'm iterating the 'ops' list in 'pdfj' command and there is no operand data there.

Thanks!

**Comment by radare** [comment]
should be in cmdj(“aoj”).val. i have pushed a commit that fills .val for more instructions, if you find any that its missing please send a PR or provide a list.

thanks

**Comment by radare** [comment]
There's no optype in RAnalOp, mainly  because this information was stored in RAnalValues before.. but this resulted in a lot of unnecessary memory allocated when doing the analysis.

**Comment by radare** [comment]
There's some more room for discussion and improvment here. because this implies exposing the entire detailed information found in capstone to the outer world. and maybe we can just do this generic for all capstone disassemblers, but not for the other ones.

**Comment by manizzle** [comment]
radare2 0.10.2-git 10897 @ linux-little-x86-64 git.0.10.1-444-g8ba4c5b
commit: 8ba4c5b959cb6ea6031d99ad04d8979e9cabe64d build: 2016-04-09
[manizzle@alexandria radare2_]$ r2 /bin/ls
 -- Enhace your graphs by increasing the size of the block and graph.depth eval variable.
[0x004049d0]> aoj
[{"opcode": "xor ebp, ebp","prefix": 0,"addr": 4213200,"bytes": "31ed","size": 2,"type": "xor","esil": "ebp,ebp,^=,$z,zf,=,$p,pf,=,$s,sf,=,0,cf,=,0,of,=","refptr":0,"cycles":1,"delay":0,"family":"cpu"}]
[0x004049d0]> 


I do not see any operand types at all, xor seems to be a common instruction I would think

**Comment by radare** [comment]
Nobody said the issue was fixed or this thing already done. The problem is not just for xor, but to cover all possible combinations of arguments for all the instructions of all the arghitectures without having to make this a complex struct .. And this id at the end what the disassembler running behind uses internally, and in some cases (capstone) this is accessible via api.

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
after thinking a while on this i think that the best way to solve this problem is by making the cs2json conversion in a new field of the RAnalOp, this way we will use a JSON parser and we may nest the whole instruction information inside the aoj output in a way that its easy to work with.

that string may be generated when ESIL is requested. so it will not slowdown the analysis.

**Comment by radare** [comment]
RAnalOp.opex added in 9c870ef165adb13d7f9add7f112a5962ad15098a... now we need to extend the anal plugins to expose this information. which should be quick because i already have some PoC code that can be copypasted

**Comment by Maijin** [comment]
Done.

**Comment by manizzle** [comment]
w00t <3

**Comment by radare** [comment]
See https://twitter.com/radareorg/status/840276665607565313

Ill be adding more archs durin the weekend
