### ISSUE TITLE
Issue trying to build python binding of radare2

### ISSUE THREAD

**Issue by benquike** [radare/radare2#4461]
I cloned the latest code and tried to build the python binding by running
`sys/python.sh`

My machine is running ubuntu 15.10 on 64-bit an intel processsor
But it did not failed with the following error in compiling.

r_core_wrap.cxx:7397:25: warning: statement has no effect [-Wunused-value]
   r_list_iter_free(self);
                         ^
r_core_wrap.cxx: In function ‘bool RFlag_unset_name(RFlag*, char*)’:
**r_core_wrap.cxx:8679:38: error: ‘r_flag_unset_name’ was not declared in this scope**
  **return r_flag_unset_name(self, name);**
                                      ^
r_core_wrap.cxx: In function ‘bool RFlag_unset_off(RFlag*, long long unsigned int)’:
r_core_wrap.cxx:8682:37: error: ‘r_flag_unset_off’ was not declared in this scope
   return r_flag_unset_off(self, addr);
                                     ^
r_core_wrap.cxx: In function ‘RFlagItem* RFlag_set(RFlag*, char*, long long unsigned int, int)’:
r_core_wrap.cxx:8688:43: error: too few arguments to function ‘RFlagItem* r_flag_set(RFlag*, const char*, long long unsigned int, unsigned int, int)’
   return r_flag_set(self, name, addr, size);
                                           ^
In file included from /usr/include/libr/r_anal.h:20:0,
                 from /usr/include/libr/r_debug.h:5,
                 from r_core_wrap.cxx:3213:
/usr/include/libr/r_flags.h:92:18: note: declared here
 R_API RFlagItem *r_flag_set(RFlag *fo, const char *name, ut64 addr, ut32 size, int dup);
                  ^
r_core_wrap.cxx:8689:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
r_core_wrap.cxx: In function ‘bool RFlag_unset_off(RFlag*, long long unsigned int)’:
r_core_wrap.cxx:8683:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
r_core_wrap.cxx: In function ‘bool RFlag_unset_name(RFlag*, char*)’:
r_core_wrap.cxx:8680:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
... r_core.so

**Comment by Maijin** [comment]
Did you check r2pipe prior bindings ? Much more simple to use and fit almost all the common use case.

See usage here https://github.com/radare/radare2-bindings/tree/master/r2pipe/python

to install `pip install r2pipe`

**Comment by radare** [comment]
are you using latest r2 from git? otherwise you will need to download the same version of r2 for the radare2-bindings tarball

**Comment by benquike** [comment]
Sorry for the wrong operation.

I am using the latest r2 from the repo.

**Comment by benquike** [comment]
@Maijin What is the difference between python binding and r2pipe?

**Comment by Maijin** [comment]
```
import r2pipe
r2 = r2pipe.open("/bin/ls")
print(r2.cmd("pd 10"))
print(r2.cmdj("pdj 10")) #json
r2.quit()
```
r2pipe is very simple, easy to ship/build for user (is in pip)....

**Comment by benquike** [comment]
@Maijin I want to use it to build other tools.
I want to know what is the exact difference between the 2 of them, e.g, what is missing in r2pipe, etc

**Comment by radare** [comment]
Confirmed bug and fixed issue.

also, this is an issue for radare2-bindings, not radare2.

run make again and it should work now. but yeah, for 90% of the things you want to do, r2pipe is easier to learn, use and run :)

**Comment by Maijin** [comment]
if there is a bug in bindings, well you're f**, r2pipe is just pipe to command line which is much more tested, and also, is much easy to find bugs via r2pipe... There is lot of argument in favour of r2pipe.

**Comment by radare** [comment]
there are 3 python bindings right now:

* r2pipe
* swig
* ctypes

r2pipe is just a wrapper for r_core_cmd(), it spawns or connects to an r2 session and runs commands and returns the output. As long as many commands have json output you can use cmdj() that will return a native object for the langauge you use. from my tests, this is way faster than using the swig bindings because the data serialization and ffi are really expensive. and json parsers are WAY faster.

swig, (using valabind) full automatically generated bindings using the vapi definitions of most of the native C api of libr. the r2 libraries. This have sometimes some issues because of missing apis (not much maintained, because most work is done in core) so you will probably find some double frees or other random crash issues depending on version of swig, r2, python , … but it works and its quite handy to integrate with other tools. The APIs should be enhaced to make them more adapted to the language.

ctypes: automatically generated bindings using valabind, but targetting ctypes instead of swig. this bindings are much faster to generate and maintain and run than the swig ones. but they are not as complete as the swig ones because the ctypes backend of valabind is not much maintained.

r2pipe requires no maintainance, and it will help you in most of the usecases you want. but it will be great to have more people using the other native bindings, so it will be useful in order to identify which apis from core are causing problems with the bindings to rename, refactor or reorganize them to make the apis easier to use.

**Comment by benquike** [comment]
Got it. Thanks.

**Comment by benquike** [comment]
@Maijin @radare 
One thing to confirm: what r2pipe does is just pass the command to r2 and return the result as a string or json object?

**Comment by Maijin** [comment]
cmd return result, cmdj return json, you obviously need to pass a json command like pdj or aoj see

```
import r2pipe
r2 = r2pipe.open("/bin/ls")
print(r2.cmd("pd 10"))
print(r2.cmdj("pdj 10")) #json
r2.quit()
```

Just try it, pip install r2pipe, take literally 5min

**Comment by benquike** [comment]
I tried.
It is easy to use in ipython.

But I have another querstion: how are the json objects encoded?

**Comment by Maijin** [comment]
Seen this https://github.com/radare/radare2-bindings/blob/master/r2pipe/python/ipython.py

For json I don't get the question. just use json.loads(cmdj..

**Comment by Maijin** [comment]
and also this https://gist.github.com/Maijin/73ed5fdb97f1b818702a see how easy it is to build cool stuff

**Comment by benquike** [comment]
My question was that if I use cmdj to ask r2 to execute a command for me, I would get an json object, right?

How is that json object encoded? i.e, what fields does the returned object contain?

**Comment by radare** [comment]
you can use .cmd() to get the output of the command. and .cmdj() to parse the json from the output directly. the command you execute must be in “json” mode, otherwise the json parser in cmdj wil fail.

see for example the output of those commands:

 ij~{} 
aoj~{}
...

**Comment by benquike** [comment]
I am not sure whether I understood you correctly or not.
If we use r2pipe python binding, we can ask radare2 to execute some command whenever we want to it to do something for us. But we do need to parse the returned results by ourselves, am I right?

**Comment by benquike** [comment]
@Maijin @radare I am been investigating on this for a while, but still not found the answer I want.
I want to use the binary(including ELF, PE, MachO) and get any related information related to this file and then parse the machine instructions contained in this file using the capstone APIs.

Could you please give me some suggestions?
