### ISSUE TITLE
Show flags (as labels) in pds

### ISSUE THREAD

**Issue by radare** [radare/radare2#4499]
Useful for full .text disasm-summaries

**Comment by Maijin** [comment]
@mrmacete probably wants to tackle this if not already done^

**Comment by mrmacete** [comment]
I'm adding this feature, is what it looks like:
<img width="547" alt="screen shot 2017-05-05 at 01 28 10" src="https://cloud.githubusercontent.com/assets/4139069/25728889/2c7b607e-3132-11e7-9ee5-d34dff14d4a3.png">
<img width="490" alt="screen shot 2017-05-05 at 01 27 22" src="https://cloud.githubusercontent.com/assets/4139069/25728905/390ebdfe-3132-11e7-9c55-d49b945bf0aa.png">

Is this good ?

**Comment by radare** [comment]
this is from the first reference of the string, not taken from esil emulation, right?

looks good so far +1 can you show the screenshot without the patch?

**Comment by mrmacete** [comment]
The strings you see are because `asm.emustr=true`, this is an iOS binary from r2r.

Here is the same without the patch:

<img width="497" alt="screen shot 2017-05-05 at 11 03 00" src="https://cloud.githubusercontent.com/assets/4139069/25739542/99b17f16-3182-11e7-9af2-4201d7c75b7b.png">
<img width="557" alt="screen shot 2017-05-05 at 11 03 25" src="https://cloud.githubusercontent.com/assets/4139069/25739548/9fc7fb5a-3182-11e7-887c-b0905972a848.png">

**Comment by Maijin** [comment]
What about this one @radare @mrmacete

**Comment by radare** [comment]
Its already done. They honor asm.flags

**Comment by Maijin** [comment]
Then close

**Comment by Maijin** [comment]
closed*
