### ISSUE TITLE
Quotation marks in V; terminate the comment unless escaped

### ISSUE THREAD

**Issue by neobrain** [radare/radare2#4547]
Trying to add a comments that includes quotation marks (`"`) in visual mode using the `;` key will not properly insert the given comment, but instead chops off all letters starting from the quotation mark.

The issue can be worked around by escaping the quotation marks in the comment, but it would be nice if this were done automatically.

Obligatory asciinema: https://asciinema.org/a/5e7qedl7lsg22nzr9209iph76

**Comment by nadavco1** [comment]
Hey neobrain,

I'm an opensource newbie looking to contribute by solving some simple issues, at least for now...
I'm also new to radare2, so it will take me some time to settle down...
Can I help with this issue?

Thanks,
Nadav

**Comment by Maijin** [comment]
yes, fix it.

**Comment by neobrain** [comment]
Thanks!

**Comment by nadavco1** [comment]
wait, what?
I thought I'm assigned for that issue as Maijin commented above...
As I said I'm new to open source, can someone explain how issues assignment works?
If someone gets an OK to fix an issue, how come someone else takes the job and fix it himself?
How can I make sure that next time my work won't be for nothing because someone else fixed it before I did and the issue was closed before I commited my fix?
Thanks

**Comment by crowell** [comment]
Sorry about that, just saw the notification in my email and pushed a fix without checking the issue

**Comment by nadavco1** [comment]
No worries crowell.
I just want to learn for the next time - what's the procedure of assigning an issue?
Thanks

**Comment by Maijin** [comment]
Just do like you did, say you're doing it in the issue 👍

**Comment by nadavco1** [comment]
Thanks guys, see you around
