### ISSUE TITLE
Error in `rahash2 -x` argument

### ISSUE THREAD

**Issue by P4N74** [radare/radare2#4642]
Running command `rahash2 -E xor -S key -x 5c` gives error: `'\x' expected.`

The error seems to be generated from function `r_str_unescape` in `/libr/util/str.c`.

**Comment by NaveenBoggarapu** [comment]
The problem seems to be with using `r_str_unescape`, escaped version of same function might fix the problem.

As a quick fix, I have tried replacing `hashstr_len = r_str_unescape (hashstr);` with `hashstr_len = strlen (r_str_escape (hashstr));`

It is working, but yet to check if this breaks anything else.
