### ISSUE TITLE
Invalid anal free

### ISSUE THREAD

**Issue by AndrewMarumoto** [radare/radare2#4702]
https://github.com/radare/radare2/blob/master/libr/anal/anal.c#L209

get_reg_profile in xtensa (https://github.com/radare/radare2/blob/master/libr/anal/p/anal_xtensa.c#L630) returns a char* from the data segment rather than the heap, resulting in
```*** Error in `/usr/local/bin/r2': free(): invalid size: 0x00007ffff6297080 ***```

**Comment by radare** [comment]
*facepalm*

The bug was in the xtensa plugin not in anal api... It must return an strdup. Revert this hack because it will cause leaks.

**Comment by AndrewMarumoto** [comment]
Ha, so I was right about that, crowell :P

**Comment by radare** [comment]
i have push -f and also, the way to go should be to remove all the get_reg_profile callback and just implement the set_reg_profile, which is the new callback that is suposed to deprecate the getter one. i just didnt finished the transition because i was busy at the time but the getter paradigm was causing problems in some situations.
