### ISSUE TITLE
Different results when using a FLIRT file between r2 and IDA

### ISSUE THREAD

**Issue by AriEi4** [radare/radare2#4716]
Hi,

I'm using the vc32rtf signature file in IDA and in r2 (load with zF command) on some files.
Sometimes the results are too different - the amount of  functions, the names and the worst part - r2 detects some functions as library functions, although IDA detects it as user functions. 

for example - Here is a sample of Stuxnet vulnerability:
http://www.filedropper.com/9e392277f62206098cf794ddebafd2817483cfd57ec03c2e05e7c3c81e72f562
Example of  the wrong detection - the function at address 0x10006338 detects in IDA as 'sub_10006338', but in r2 - 'flirt.___crtMessageBoxW'.

Thanks for the help.

**Comment by radare** [comment]
are you using r2 from git? (0.10.3-git) which analysis level are you running? do you have autoname option enabled?

**Comment by AriEi4** [comment]
Using the git version, with the default analysis level and autoname enabled.

**Comment by radare** [comment]
disable autoname

**Comment by AriEi4** [comment]
Ok, i got the exact same results with and without the autoname.

**Comment by jayint3z3r** [comment]
Here's the same file from another issue since the other download isn't working. http://puu.sh/oDA6E/75a93859d9.bin

From my analysis, the byte pattern and CRC match up, however as the "references" part of the signature matching is not finished, the problem might be that the reference to one of the two functions is not there. Since radare2 does not deal with this, it just uses the byte pattern and marks the function as what it is not.

Here is from the tree file given by the tool that comes with IDA to read the sig files:
```
E8........8365FC00833D........008BD80F858E:
                    0. 04 9013 0169 0000:___crtMessageBoxW (REF 0016: ?pfnMessageBox@?1??__crtMessageBoxW@@9@9)
                    1. 04 9013 0169 0000:___crtMessageBoxA (REF 0016: ?pfnMessageBox@?1??__crtMessageBoxA@@9@9)
```

I highlighted the matching byte pattern in the photo here: http://puu.sh/oDBem/ca9686e84f.png

**Comment by XVilka** [comment]
@jroimartin may be you can check this one

**Comment by XVilka** [comment]
@AriEi4 is this still a case? There were a lot of changes in this code since. Please retest it.

**Comment by AriEi4** [comment]
I guess we can close it.
