### ISSUE TITLE
Create r2bb as a busybox replacement

### ISSUE THREAD

**Issue by radare** [radare/radare2#4894]
This is easy and kinda handy for embedded systems. r2 already implements many basic unix commands. maybe it's time to create a single main to call them all and create symlinks ala busybox

**Comment by jduck** [comment]
FWIW, I'm not a fan of programs putting symlinks in my system without asking permission or other explicit interaction. I think the android radare2 installer did this and I was not happy about it :-/

I prefer to call "busybox <utility name> <args>" instead. If I do go the symlink route I would put them somewhere outside of the default path and modify my path to override for one session.

Otherwise, neat idea!

**Comment by radare** [comment]
dupe of https://github.com/radare/radare2/issues/6143
