### ISSUE TITLE
Patches in radare2 did not take effect when restart

### ISSUE THREAD

**Issue by cx9527** [radare/radare2#4990]
Hi! I patched some instructions in radare2, i've already turned on the writable option`r2 -d -w ./a`. But the changes did not take effect when i restart radare2.

![2016-05-24 21 29 19](https://cloud.githubusercontent.com/assets/6133787/15505562/9be1d386-21f6-11e6-9d5b-2c007e3443f7.png)

![2016-05-24 21 32 59](https://cloud.githubusercontent.com/assets/6133787/15505698/216f960a-21f7-11e6-8a07-93d868b9f83c.png)

Is there anything i missed? Or i should dump it to file manually?

**Comment by radare** [comment]
you are debugging, all the changes done in the debugger doesnt apply to the disk file. mainly because they dont neceessary need to be the same, and they can even be different (packers, etc) . you dont need to use -w when debugging, because debugger baceknds allows to write by default. otherwise you will not be able to set breakpoints or such

**Comment by radare** [comment]
so this is expected behaviour

**Comment by cx9527** [comment]
So, rapatch is the only way to patch the disk file? Is there any way to patch it in the runtime?

**Comment by XVilka** [comment]
@cx9572 use 'w?' commands to save the content.

**Comment by radare** [comment]
you are already patching it at runtime. rapatch is just an easy way to write patches, but the only thing you have to do is just r2 -w file and patch stuff in there. 

if you modify the memory of the process this will not be relfected to disk

**Comment by cx9527** [comment]
@radare Thanks a lot! It works!

**Comment by Maijin** [comment]
or use oo+
