### ISSUE TITLE
`rahash2.exe -a base64 -s "qwe"` return nothing

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#5007]
```
~/radare/radare2/radare2-w32-0.10.3
$ ./rahash2.exe -a crc32 -s "qwe"
0x00000000-0x00000002 crc32: f7d4a193
~/radare/radare2/radare2-w32-0.10.3
$ ./rahash2.exe -a base64 -s "qwe"

```

**Comment by radare** [comment]
Base64 is not a hash. You must use -E instead of -a. But thats right, it must show a warning at least or handle the encoding plugins with -a too

**Comment by radare** [comment]
ping? what do you think we should do here?

**Comment by Maijin** [comment]
```
Available Hashes:
  md5
  sha1
  sha256
  sha384
  sha512
  crc16
  crc32
  md4
  xor
  xorpair
  parity
  entropy
  hamdist
  pcprint
  mod255
  xxhash
  adler32
  base64
  base91
  punycode

Available Crypto Algos:
  rc2
  rc4
  rc6
  aes-ecb
  aes-cbc
  ror
  rol
  rot
  blowfish
```

Change this so xor, base64, base91 and punycode are located under "Available Crypto Algos:"

@P4N74 ?

**Comment by radare** [comment]
Maybe use it like in rasm2... All of them can be considered for encoding, so use -a for them. And then use -d to decode, this will make it less confusing and we will be able to kill -E and -D

**Comment by P4N74** [comment]
@radare so should I kill -E option and instead add -a for all the encryption irrespective of hashes/crypto algos? And replace -D with -d?

**Comment by radare** [comment]
I think its a reasonable change. What others do think about it? Is there any conflict with other options?

**Comment by P4N74** [comment]
There won't be any such conflicts as `-d` option is currently not used and no other such option is used for encryption except for -a and -E. Implementation won't take much time, so I will wait for others to comment on what a proper fix should be. Temporarily I can fix the -L output to show the xor, base64, base91 and punycode in available cryptos. Should I fix it (-L for now) or wait and create a proper fix later (1-2 days)?

**Comment by radare** [comment]
I think we can do all the changes in a single pr. Lgtm

**Comment by crowell** [comment]
uh, b64 and friends are not crypto algorithms...

On Sat, May 28, 2016 at 12:53 PM, radare <notifications@github.com> wrote:

> I think we can do all the changes in a single pr. Lgtm
>
> > On 28 May 2016, at 18:50, Rakholiya Jenish <notifications@github.com>
> wrote:
> >
> > There won't be any such conflicts as -d option is currently not used and
> no other such option is used for encryption except for -a and -E.
> Implementation won't take much time, so I will wait for others to comment
> on what a proper fix should be. Temporarily I can fix the -L output to show
> the xor, base64, base91 and punycode in available cryptos. Should I fix it
> (-L for now) or wait and create a proper fix later (1-2 days)?
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/radare/radare2/issues/5007#issuecomment-222318217>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAlnYFDmTtm320TaXTcBB_Tj31sBXMhUks5qGHMBgaJpZM4ImqGb>
> .
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by radare** [comment]
We all know, this will be noted in the -L output. But its anoying to differenriate crypto algorithms, encoders, checksums, and base converters into separated flags.

**Comment by P4N74** [comment]
@radare I am starting to work for combining everything into `-a`

**Comment by radare** [comment]
awesome! thanks!

**Comment by P4N74** [comment]
Since for `-a` option, the correct hash algorithm is checked based upon power of 2 and for crypto, the algorithm is checked based upon `strcmp`, I am not getting good ideas to make it work. Two options I am able to think is:
1) add power of two's for all crypto algorithm in https://github.com/radare/radare2/blob/master/libr/include/r_hash.h#L82-L103
2) compare hashing algorithms similar to crypto algorithm (using `strcmp`).

Both seems bad to me since in 1) it would become a blunder by making hash and crypto into one file and for 2) it would be rewrite of some of the part (might be more also, not sure). I think I can either try changing base64, base91 and punycode to hashing part or update the `-L` as @Maijin suggested.

Need help.

**Comment by radare** [comment]
I would go for 2, but the reason why hashes are checked this way is because you can specify more than one.. Which seems "useful" at first, but theres a clear limitation because we will never be able to have more than 64 hash algorithms.

Sounds reasonable the change. I think users will appreciate the simplicity of this. Even if we know that encoders != checksums != crypto. All those things are basically black boxes that get some input with optional parameters and output another stuff.

But those differences must be noted in rahash2 -L specifying the prameters required and type of algorithm for each plugin.

Also rahash2 doesnt makes hashes pluggable. This is another restriction we should get rid at some point in the future. So it will be possible to write crypto algorithms in any scripting language or reduce build size when not needed.

**Comment by radare** [comment]
ping

**Comment by P4N74** [comment]
Thanks for reminding. Last time I worked on it, I was somewhere in middle of multiple changes and then forgot to complete it. Will try to fix this in this milestone itself.

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
moving to 0.10.5?
