### ISSUE TITLE
Better names of vars/functions for native bindings

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#5066]
To provide uniform naming through all conventional bindings for radare2:

```
r_core.i:92: Warning 314: 'print' is a python keyword, renaming to '_print'
r_core.i:324: Warning 314: 'from' is a python keyword, renaming to '_from'
r_core.i:329: Warning 314: 'from' is a python keyword, renaming to '_from'
r_core.i:584: Warning 314: 'import' is a python keyword, renaming to '_import'
r_core.i:1981: Warning 314: 'del' is a python keyword, renaming to '_del'
r_core.i:1652: Warning 453: Can't apply (RAsmOp *OUTPUT). No typemaps are defined.
r_core.i:1657: Warning 453: Can't apply (RAsmOp *OUTPUT). No typemaps are defined.
r_bin.i:109: Warning 314: 'import' is a python keyword, renaming to '_import'
```

**Comment by radare** [comment]
Those are hints that are already filtered in valabind, and they differ depending on the language. You will find more of those when building for other languages.

**Comment by XVilka** [comment]
I know, but valabind renaming those, but people would need to use renamed members or types, which is hard to figure if they'll use radare2 headers as reference. So I'm suggesting to find names that wouldn't be keywords in main supported languages.

**Comment by radare** [comment]
Yep. Since the begining i tried to make r2 apis to be as much consistent with valabind as possible to ease the automatic bindings and avoid using confusing forms like unions and use getters and setters as much as possible to shadow the raw access to the underlying structs and avoid using keyword names that can conflict with other languages than C.

This is part of the refactoring to be done in the apis that i was planning after 1.0, but if anyone wants to help on that we can slowly do that and improve native bindings before

**Comment by XVilka** [comment]
Not this time. Hopefully during GSoC/RSoC.

**Comment by radare** [comment]
i think we can close this already, its a known thing and those warnings come from valabind, which spits those warnings

**Comment by radare** [comment]
and we should probably update those warnings, this ones are so much from 2016
