### ISSUE TITLE
Wrong asm.bits when using -A -d

### ISSUE THREAD

**Issue by monosource** [radare/radare2#5192]
And also when forcing with `-b 32`, apparently: http://asciinema.org/a/dvaa45uxt9ipp1gtqsvc5yjue

Analysis works just fine if I don't open with `-d`, and `asm.bits` is correctly set to 32.

EDIT: [test.zip](https://github.com/radare/radare2/files/326091/test.zip)
Forgot to add binary, silly me.

**Comment by radare** [comment]
Can you provide information about the system, binary, etc... Because i guess that you are trying to do that on a fat binary that contains 32 and 64 bit segments. Also i doubt that you want to run the analysis in the debugger. Mainly because accessing the memory on a remote process is way slower than reading the local heap.

I never understand why people wants to analyze the whole program unless theres some need for automated static anaysis. Because all the other needs can be solved with simpler commands that run much faster and return better results. I wrote a blogpost about it

But anyway, this seems like a bug

**Comment by monosource** [comment]
> Can you provide information about the system, binary, etc.

The binary is very simple (see original post, which I've edited to add the binary).
```
$ file test 
test: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=323597f770b655917150a52dc29ba03a71a5800d, not stripped
```
```
$ stat test
  File: ‘test’
  Size: 5028      	Blocks: 16         IO Block: 4096   regular file
Device: 801h/2049d	Inode: 9830459     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/monosource)   Gid: ( 1000/monosource)
Access: 2016-06-21 20:31:45.800290085 +0300
Modify: 2016-06-21 19:32:52.000000000 +0300
Change: 2016-06-21 20:31:36.172809416 +0300
 Birth: -
```
```
$ uname -a
Linux bluefin 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
```
```
$ r2 -v
radare2 0.10.4-git 11673 @ linux-x86-64 git.0.10.3-280-gdb28a0b
commit: db28a0b20d122f87f2067d40201e087e54390301 build: 2016-06-21
```

> I never understand why people wants to analyze the whole program unless theres some need for automated static anaysis.

From a performance standpoint, in this binary's case, it isn't an issue. Analysis is almost instant. I mainly do analysis since it adds useful flags which can be used with the debugger (instead of writing addresses all the time). However, I understand your point entirely.

**Comment by radare** [comment]
I guess that the debug target bits is not populated at the moment of -A . As a workaround you can run aa right when you have the prompt. You can also try -caa to see if that fixes the issue. This is probably because of the last refactorings in radare2.c 

Please confirm those methods and ill push a fix when i get a chance

**Comment by monosource** [comment]
```
r2 -b 32 -d ./test
```
followed by `aa` at prompt, same result as before.

Same goes for `r2 -b 32 -caa -d ./test`.

**Comment by radare** [comment]
moving to 0.10.5 i had no time to check this issue for today's release

**Comment by radare** [comment]
can you confirm if this is fixed now?

**Comment by monosource** [comment]
Yes, it's fixed. Thanks a lot!
