### ISSUE TITLE
r2ed race with -S

### ISSUE THREAD

**Issue by Susanne588586** [radare/radare2#5609]
with r2 editor using unsafe temporary files, it is possible to overwrite files as user,
though it seems not a problem, if you don't have a shell.

```
,touch /home/s/.login
,ls -l /tmp/r2ed\?\?\?\?\?\? 
lrwxrwxrwx 1 s s 15 Aug 25 14:51 /tmp/r2ed?????? -> /home/s/.login
,ls -l /home/s/.login
-rw-r--r-- 1 s s 0 Aug 25 14:51 /home/s/.login
,echo q|/usr/local/bin/r2 -Sqc"-" /bin/ls
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...
Vim: Finished.
,stat /home/s/.login
stat: cannot stat ‘/home/s/.login’: No such file or directory
```

wat do?

**Comment by crowell** [comment]
if you already have a shell, you can do much worse... I can't really think of any reason to change the behavior

**Comment by Maijin** [comment]
@crowell well `r2 -S` is supposed to be sandbox mode I think that's the issue here.

**Comment by Maijin** [comment]
Can you create an asciinema @Susanne588586

**Comment by radare** [comment]
I think thats the second issue we get about this thing this week

The -S sandbox flag ONLY affects the shell. Not the commands you pass in the commandline. It is suposed to be used to restrict the user to do silly stuff and the user is not the one suposed to spawn that r2 session because if he does he already have a shell which have no restrictions.

You can solve this by using -e cfg.sandbox=true . This will set the sandbox before the r2 prompt appears and restrict the - command you inject in the argv

**Comment by Maijin** [comment]
ah ok it's this again
