### ISSUE TITLE
ihex:// is broken

### ISSUE THREAD

**Issue by radare** [radare/radare2#5756]
Files: [ex3.4.zip](https://github.com/radare/radare2/files/470901/ex3.4.zip)

```
$ avr-objdump -I ihex -O binary ex3.4.hex ex3.4.bin
$ r2 ihex://ex3.4.hex
```
<img width="1082" alt="screen shot 2016-09-14 at 00 19 17" src="https://cloud.githubusercontent.com/assets/917142/18493446/e8542f62-7a10-11e6-9719-fc42484ad006.png">

**Comment by killabytenow** [comment]
I have tested it and I think that this behaviour is absolutely normal:

One is a complete ELF file (ex3.4.elf: ELF 32-bit LSB executable, Atmel AVR 8-bit, version 1 (SYSV), statically linked, not stripped)

While the other file is a raw ROM hexdump without symbols, relocation table and other bells and whistles. So the hexdump and radare analysis must be different!

In the other hand raw dissassemble seems the same. I have been comparing both dissasemblies by hand from offset 0x00000 -interruption vector table- to address 0x000003fe) and they are the same.

Please note that it is also critical to set the option -a avr when invoking radare2 on an hex file,because by default r2 assumes that we are working with an HEX file por x86.

IMHO I think it is not a bug

**Comment by Maijin** [comment]
@Darkkey

**Comment by radare** [comment]
try it yourself and you'll see that the code makes no sense. its not just about elf vs raw

**Comment by killabytenow** [comment]
Why does it not have sense? Because the jmp at offset 0? this is the interrupt table... it is normal? Once is executed the first jmp, it jumps to main at 0x8e and clears the SREG, configures the stack (out 3e, 3d), etc... it seems a normal AVR program. I've not read all code, but it the first twenty instructions are meaningful.

**Comment by Maijin** [comment]
![image](https://cloud.githubusercontent.com/assets/1408600/18585107/3d91012a-7c15-11e6-9305-788bb6b68240.png)
@Darkkey

**Comment by Darkkey** [comment]
I've recheck everything and think that somehow between 5th Sept and 16th Sept it was fixed. So now working, sorry for raising panic, my bad.

**Comment by radare** [comment]
i think nobody touched anything related to ihex during this range of time, but anyway nice to hear that

**Comment by Maijin** [comment]
OSOM!
