### ISSUE TITLE
sys/ios-cydia.sh failing with no error

### ISSUE THREAD

**Issue by Carlinho89** [radare/radare2#5776]
Hi, I'm trying to build radare2 for my iPhone6s. I can install normally radare2 with the 'sys/install.sh' on my Mac.

I'll attach a copy of the log.
[ios-cydia_log.txt](https://github.com/radare/radare2/files/475123/ios-cydia_log.txt)

I can't see where the error is..

**Comment by radare** [comment]
just grep for “error:”

it fails trying to compile the debugger backend because you dont have the mach include files for iOS. in fact nobody does because apple doesnt provides them for so long. so just grab the ios-include.tar.gz and uncompress it inside the sys subdirectory. the build system will take care of it and override the system ones.

you can also pass —witohut-debugger


this is the error message you are having:

In file included from p/native/xnu/xnu_debug.c:21:
/Applications/Xcode8/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk/usr/include/mach/mach_vm.h:1:2: error: 
      mach_vm.h unsupported.
#error mach_vm.h unsupported.
 ^
