### ISSUE TITLE
reference rabin2 -h in i? and viceversa

### ISSUE THREAD

**Issue by radare** [radare/radare2#5880]
As suggested by @gozes on [Twitter](https://twitter.com/gozes/status/781290769449492482)

**Comment by radare** [comment]
Should be fixed by 6a7f728950196c91de78ea5a0a2108079a72a4f2 let me know if it's not clear enough yet

**Comment by gozes** [comment]
to clarify I was not only referring to rabin2 alone but to all the tools that come with r2( rax2, rasm2, rafind2, ragg2 etc). Basically if anything that the individual can do that can also can be accomplish in r2 shell by a command should be reference. that would make radare2 a little bit easier to learn because if you know how to do something with one of the tools that comes with r2 then you know, or can easily look it up on the man page for that tool, how to do the same thing inside r2 shell.

**Comment by Maijin** [comment]
Well you got the model, I think this is simple enough you can do a Pull-request for this no?

**Comment by gozes** [comment]
@Maijin I can but I don't know all the mappings yet, I'm still learning r2. However, if someone can explain the logic of the commands or guide me, I can jump on IRC any time, I am more then happy to do it. :smiley: actually, I am more then happy to go over all the docs and clarify, from the point of view of someone learning r2,  things that maybe unclear or hard to understand and fix them but for that i will need someone that knows r2 better then me so that they can "explain" to me and I can fix it on the docs

**Comment by Maijin** [comment]
@radare just posted the model for i? and rabin2:
https://github.com/radare/radare2/commit/6a7f728950196c91de78ea5a0a2108079a72a4f2 
Still need to do same with rax2 and ??? ; rahash2 and ph?, p=? ;  radiff2 and C? ; rafind2 and / ;...

**Comment by Maijin** [comment]
The goal of the issue can be you look at the command and find equivalence:
1) You train yourself
2) You improve doc
