### ISSUE TITLE
Printing disassembly with unreasonably large N takes forever

### ISSUE THREAD

**Issue by viraptor** [radare/radare2#6044]
`pd` doesn't treat very large `N` as invalid and goes into a long loop that cannot be broken due to simple accidents.

For example:

```
// wanted to run:
pd @some_flag
// accidental run:
pd some_flag
// which is equivalent to:
pd 0x009dd7d5
```

`pd` still tries to do its job and cannot be stopped with <ctrl+c> during this process. Killing radare is the only way I see to resolve it.

version 0.10.6

**Comment by Maijin** [comment]
And what if you actually want to print this amount of bytes? Normally it should ask you if you want to display it with a y/n. I don't see problem here

**Comment by viraptor** [comment]
The problem is that it doesn't ask me if I want to display that much information.

Unless you're actually trying to be unfriendly to users, I'd expect at least one of following:
- <ctrl+c> actually stopping that process
- warning that this is probably not what you want (or the standard "this will produce at least 10344405 lines, do you really want that)

Essentially, making me kill radare and lose my work so far == bad.

**Comment by Maijin** [comment]
It should ask you, this looks like a regression

**Comment by Maijin** [comment]
[0x100001174]> pd 1000000
Do you want to print 1000219 lines? (y/N)

**Comment by Maijin** [comment]
That's what I got

**Comment by radare** [comment]
rcons prompts you before printing all this stuff when the output is huge, but the problem is that r2 will do the operation first, this is reading all this huge amount of memory without prompting.

its a common mistake for newcommers.. so maybe we should extend that prompting to io too, not just cons…

**Comment by radare** [comment]
nope its been always like this

**Comment by viraptor** [comment]
This is a problem for me mainly in conjunction with other issues like https://github.com/radare/radare2/issues/6038 For example:
```
pd @some_f<tab>
// autocompleted to:
pd some_flag
<enter>
// oh well, time to pkill radare2 again
```
it would be great if it r2 either checked that beforehand (pd will obviously print at least N lines), or allow breaking long io commands with `<ctrl+c>`

**Comment by radare** [comment]
@some_f is wrong way to use the @ operator. i recommend you to add a space after it, bascially because there are several @ modifiers see ?@? for help

pd some_flag is also a bad way to use that, unless you use flags for length. i guess its a matter of get used to type the commands properly, but i understand some newcomers may be confused by the syntax.. but i dont wanna break working functionalities just because you can pass any number as parameter and consider this something wrong.

What I would prefer is to better handle ^C across all r2 instead of limiting the experience or doing workarounds for every single command that handles an arbitrary value as argument.
