### ISSUE TITLE
remove ht.c from radare2

### ISSUE THREAD

**Issue by lowlyw** [radare/radare2#6049]
just use the version in sdb, it's more correct.

**Comment by radare** [comment]
we didnt upgraded sdb yet because it breaks 20 tests, the ht is not behaving as it was doing before yet. and ret2libc and me plan to rework on that ht still for some time, i dont think we can stabilize it for 1.0

**Comment by radare** [comment]
in fact we should be able to switch just the ht.c and drop the ht64 and it should work fine, without updating sdb, because the pending feature for this hashtable is to allow keys to be sorted. we can handle this into SdvKv holding another RListIter. so it should be in theory quick to do, but im afraid of the regressions or problems that can come later. Mainly because i dont have much time and i dont see anyone else with the mood

**Comment by alvarofe** [comment]
there is another issue
