### ISSUE TITLE
Fix issue with ELF parsing

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#6179]
There is a binary in r2r

**Comment by enovella** [comment]
Hi alvarofe && r2 buddies,

As already discussed over the IRC chat with you guys, it seems that radare2 does not interpret properly an ELF binary which has been dumped from memory at runtime by using `GDB`. The reason of opening this issue is due to that` Ida Pro v6.9.160222` makes a pretty decent auto-analysis and code recognition. Note that some warnings are popped up when loading the binary into Ida Pro. The result in Ida Pro is plenty of code, symbols and strings identified. 

When analyzing with radare2 the same dumped ELF binary (header is kinda "corrupted"), the command `aa` performs an analysis, which provides no code, no strings no sections. This is odd and unthinkable because the header looks like an ELF binary. Hopefully, we can figure out how to solve this issue.


The ELF binary is an ARM32 shared library dumped at the following offsets:
```
765ad000-765b0000 r-xp 00000000 b3:19 955        /system/lib/libmemalloc.so
765b0000-765b1000 r--p 00002000 b3:19 955        /system/lib/libmemalloc.so
765b1000-765b2000 rw-p 00003000 b3:19 955        /system/lib/libmemalloc.so
```

The library I am sharing is a merged binary with all the chunks dumped from memory. 
[libmemalloc-dmp-mem-gdb-0x765ad000_0x765b2000.zip](https://github.com/radare/radare2/files/586846/libmemalloc-dmp-mem-gdb-0x765ad000_0x765b2000.zip)

Cheers mates,
  @enovella_

**Comment by enovella** [comment]
Hi again,

it seems fixed but newly messed up.


```
[14:41 user@reverse Downloads] > r2 -v
radare2 1.0.2 12950 @ linux-x86-64 git.1.0.2-5-g0deb096
commit: 0deb096ea7657bcfea9b5a41a026388c1b2a1e75 build: 2016-11-12
[14:41 user@reverse Downloads] > r2 libmemalloc-dmp-mem-gdb-0x765ad000_0x765b2000.bin 
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings
 -- Do not try to sploit that binary - that's impossible. Instead, only try to realize the truth: there is no binary.
[0xfffffffffffffffe]> aaa
[Cannot find function 'entry0' at 0xfffffffffffffffe(aa)
[x] Analyze all flags starting with sym. and entry0 (aa)
[ ] 
[aav: Cannot find section at this address
aav: Cannot find section at this address
[x] Analyze len bytes of instructions for references (aar)
[Oops invalid rangen calls (aac)
[x] Analyze function calls (aac)
[ ] [*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan))
[0xfffffffffffffffe]> afl
[0xfffffffffffffffe]>
```

**Comment by radare** [comment]
i dont think considering entrypoint at address 0 is good at all, is this a memdump because stuff in memory gets messed up compared to disk

**Comment by enovella** [comment]
Hi,

Indeed, it is a memdump from memory (`/proc/$pid/maps`). What I cannot find it is an easy way to handle these ELF-like files. Amongst the r2 versions I have tried with, the behavior is unpredictable.

Am I missing something? Is r2 doing okay then?

Cheers,
  edu

**Comment by radare** [comment]
Well, r2 can always do better, but for this case i see lot of really messed up section information. So i don't see how can we improve on that without ignoring all the info in the headers. did you tried with other tools like ida/hopper/objdump? because from my tests its even worst in other tools

**Comment by radare** [comment]
and 0.10.2 was listing the symbols and not 1.0.2 ? uhm then thats a regression

**Comment by enovella** [comment]
As said in my first post, I was working with` Ida Pro v6.9.160222`, which makes a decent auto-analysis. I have not tested others though.

**Comment by alvarofe** [comment]
closed when added test

**Comment by alvarofe** [comment]
test added

**Comment by enovella** [comment]
Tested here and works O.K. now ;)
