### ISSUE TITLE
Wrong AVR analysis for RJMP

### ISSUE THREAD

**Issue by radare** [radare/radare2#6187]
Reproducer:
```
$ r2 -qa avr -s 0x141c -c 'wx 0ac0;ao' malloc://8K
address: 0x141c
opcode: rjmp 0x1432
prefix: 0
id: 0
bytes: 0ac0
val: 0x00000000
ptr: 0x00000000
refptr: 0
size: 2
type: jmp
esil: 1074,pc,=
jump: 0x00000432
fail: 0x0000141e
stack: null
family: cpu
```

cc @killabytenow

**Comment by radare** [comment]
the pr is red and the solution is wrong as i stated in the irc

**Comment by Maijin** [comment]
ah sorry, I thought it was github bug ;)

**Comment by killabytenow** [comment]
This is because you are using the default AVR arch, which is ATmega8 with a 12 bit PC pointer. If you change to a 16 bit PC arch you can obtain the "desired" answer:

r2 -qa avr -s 0x141c -c 'e asm.cpu = ATmega1280; wx 0ac0;ao' malloc://8K
address: 0x141c
opcode: rjmp 0x1432
prefix: 0
id: 0
bytes: 0ac0
val: 0x00000000
ptr: 0x00000000
refptr: 0
size: 2
type: jmp
esil: 5170,pc,=
jump: 0x00001432
fail: 0x0000141e
stack: null
family: cpu

I think it is a disasm bug, not an anal bug.

**Comment by radare** [comment]
the disassembler should be in sync with the analysis, so the disassembler should also chop to 12 bit addressing.

**Comment by killabytenow** [comment]
It should chop to the choosed CPU arch, not to 12 bits. There is also something that I think it is a bug too: when option -a avr is set, the default value for CPU should not be x86, for god's sake.

**Comment by radare** [comment]
isnt x86 a 12bit avr? :O

**Comment by killabytenow** [comment]
yes, it is the black sheep of the avr family, but everyone try not to talk never about this in public forums. We have enough sharing a dinner with it on christmas.

**Comment by radare** [comment]
see https://github.com/radare/radare2/commit/3e3f098413aaf0645d62bb4996c2b3f49cc1aae4

**Comment by Maijin** [comment]
So what's next closing this ?

**Comment by radare** [comment]
Maybe a pr from @killabytenow?

**Comment by radare** [comment]
afaik @killabytenow is working on a fix right now
