### ISSUE TITLE
Visual Mode and vim 

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#6202]
morrn,

is it possible to have ed like syntax in visual mode, so I could go like :255 to jump to this position?
setting e scr.pager to vim doesn't use vim on this machine.

Greetings
--zlul

**Comment by radare** [comment]
you can do that already in visual… well in fact it looks like a regression because some time ago typing a number without anything else was considered a seek. so :123 was a valid command. dunno when this changed :? and i guess that there are no tests for that.

i dont think you can use vim as a pager. but having :123 implemented in r_cons_less seems desirable, as well as integrating `nl` in there with a toggler key

**Comment by radare** [comment]
works if it starts with '0x'. so if you type :0x0+312 it will work

**Comment by radare** [comment]
you also have the 'g' key to seek
