### ISSUE TITLE
r_core_anal_esil_fcn usefulness?

### ISSUE THREAD

**Issue by ninjahacker** [radare/radare2#6451]
I was looking into doing better on ARM analysis, and I came across two functions: r_core_anal_esil_fcn and r_core_anal_esil.

r_core_anal_esil_fcn is called from r_core_anal_fcn when anal.esil is set. But r_core_anal_esil_fcn doesn't appear to do anything. Then there is r_core_anal_esil which appears to really do analysis using esil. So is this a mistake? Should r_core_anal_fcn really call r_core_anal_esil? Or should r_core_anal_esil_fcn be implemented? It seems like the simple trick is to use the 'aaef' implementation inside of r_core_anal_esil to make r_core_anal_esil_fcn into a useful function. Am I missing something? 

Thanks!

**Comment by alvarofe** [comment]
There is a TODO inside `r_core_anal_esil_fcn` so I think is not implemented. 

```
		// TODO: Implement the proper logic for doing esil analysis
```

**Comment by ninjahacker** [comment]
Yes, true. I'm just wondering if I'm missing something since ESIL analysis is done elsewhere. Why can't we just hijack that? Or is there something special that needs to be done here?

**Comment by radare** [comment]
currently there are multiplke analysis loops. esil makes no sense to do it in the same static analysis loop because you need proper function boundaris to perform correct recursive code emulation to resolve all refs properly. so we just experiment with different commands and loops to find best results on different targets and slowly add them to the defaults when properly tested.

if you have any idea/proposal just send a pr to improve that :)

**Comment by alvarofe** [comment]
r2 is for experimentation, PoC and fun before to pass the stuff to production/approval aka pancake

**Comment by ninjahacker** [comment]
Yeah, I'll see what I can do. Right now I'm pretty close to finishing the LDR/STR esil implementation for ARM. It's pretty nuanced. A ton of cases to consider to get it right. Each of which obviously need a regression test! Ugh!

**Comment by radare** [comment]
Awesome! Good job!

**Comment by Maijin** [comment]
Can we close this @ninjahacker or?
