### ISSUE TITLE
turn off the garbage speaking in the WI

### ISSUE THREAD

**Issue by razorfish-sl** [radare/radare2#6604]
Do i really need a continual message about posting to facebook , or some grandfather in WW2 ?

may be better to clean up some of the bugs, than have such crap in a disassembler

**Comment by radare** [comment]
I dont know what version of r2 are you using, but the text-to-speech functionalities are disabled in master already. This feature was implemented in maybe 10 minutes in only one of the 14.000 commits that this repo have. And this is the base to have better support for blind users. Yes, there are blind users in r2land.

See `e~tts` to check the options.

The fortune messages can be also configured if you dont want to see them or change the kind of messages you get, feel free to send more useful and less funny fortune messages if that's what annoy you.

If you care about bug fixing you are up to fix bugs too instead of spending time reporting things.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.
