### ISSUE TITLE
orax is not an x86 register

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6652]
But appears in `dr`, and also in Visual debugger register bank, many time with 0xfffffffffffffff
value which screws up the alignment. Can get rid of it?

**Comment by radare** [comment]
orax is a register that is available only on linux for x86. you can get rid of it by using your own register profile (see the drp command). this register shows the old value of rax after a syscall.

**Comment by SchumBlubBlub** [comment]
> you can get rid of it by using your own register profile (see the drp command). 

I already have, but running `drp` in .radare2rc has no effect. I have to do it manually everytime.

**Comment by radare** [comment]
try with -i to confirm the issue is gone in this stage. we can probably add another rc to run depending on the miemtype, etc, this was a proposal i did 2 years ago, but didnt went forward because nobody was interested on that. my idea was to have something like vim that can run conditional blocks of scripts depending on the type of file. you can also put a file.r2 where ‘file’ is the filename of the bin you are opening, this script will be also opened after loading the file

**Comment by SchumBlubBlub** [comment]
Yeah, -i ~/.radare2rc works.
