### ISSUE TITLE
new output format of o on siol

### ISSUE THREAD

**Issue by condret** [radare/radare2#6798]
see this and let the shitstorm begin: https://asciinema.org/a/7na8v2b8x4d2kv5xmx08zj3be

**Comment by radare** [comment]
Wtf seems inconsistent.output shoyld be the same independently if it have custom maps or not. Or i missed something?

**Comment by condret** [comment]
Well, I thought it would be a nice feature, to show not just only the desc, but their maps too

**Comment by radare** [comment]
yep its nice, but its confusing because thats not shown in the first ‘o’. what about making the output of o consistent, and just have anohter command to show that?

imho the output of o must be one file per row. and we should be easily able to grab the fd with ~[] and then grep the output of another command to see all the maps applied to that fd… or mayb ejust passing this fd as argument to another command. that would be more ortogonal

**Comment by condret** [comment]
the reason, why it doesn't show the maps when io.va is off, is that maps don't matter without va

**Comment by radare** [comment]
uhm.. still seems insconsistent, i would prefer to have this in a separate command under `o`. what do you think alvaro?

**Comment by condret** [comment]
@radare I'm fine with an extra-command for this, just wanted to explain

**Comment by Maijin** [comment]
The `:` and `;` seems random can we just remove them ?

**Comment by Maijin** [comment]
ping.

**Comment by Maijin** [comment]
https://hackmd.io/GYBghgzAjBBGCcBaArAdgqxAWKATKi8AxmAQKYAcqZIqYxAbA8kA?both
