### ISSUE TITLE
Problem with rebuilding/reinstalling new versions.

### ISSUE THREAD

**Issue by Nevsor** [radare/radare2#6940]
I am not sure whether this is a bug, or whether I am doing something wrong.

After building radare I am not able to successfully build and install a new version of radare (e.g. after `git pull` or after manual changes to the source files).

The build finishes without errors, but the binaries in ./binr/radare2/ and /usr/local/bin/ always show the old version banner. 

I tried `sys/install.sh`, `sys/build.sh` and `./configure; make; sudo make install`.
`make clean` and `sudo make purge` do not help either.

The only way to actually make radare show the new banner is renaming the repo directory and cloning the repo again.

@cym13 seems to have a very similar problem according to #6937.

**Comment by cym13** [comment]
I confirm, what you describe is exactly what I experience.

**Comment by Nevsor** [comment]
Maybe this helps reproducing the problem:
https://gist.github.com/Nevsor/1ac975161c9e5e39524984ac4723c369

**Comment by wargio** [comment]
i don't have such problem.

**Comment by asutoshpalai** [comment]
Experienced the same problem. From a first-hand look, only the banner is not getting updated while the actual binary and libraries are getting updated.

**Comment by radare** [comment]
See r2 -vv

Do you know how ld find the libs? This is expected unless you install or use env.sh

**Comment by Nevsor** [comment]
I tried to update again today to check out test a bugfix in r_anal. The bug was fixed after that, but the banner still showed the old timestamp.

This is what I did:

```
sudo sys/uninstall.sh
sudo make purge
git pull
sys/install.sh
```

@radare, the version banners:

```
$ r2 -v # r2 -vv shows exactly the same
WARNING: r2 library versions mismatch! See r2 -V
radare2 1.3.0-git 13980 @ linux-x86-64 git.1.2.0-314-ga40343f
commit: a40343f2f025a2a8434034b2eadabc23b7dcbe86 build: 2017-03-07__00:49:31
```

```
$ r2 -V
1.2.0-314-ga40343f  r2
1.2.0-325-gbb20c45  r_anal
1.2.0-325-gbb20c45  r_lib
1.2.0-325-gbb20c45  r_egg
1.2.0-325-gbb20c45  r_asm
1.2.0-325-gbb20c45  r_bin
1.2.0-325-gbb20c45  r_cons
1.2.0-325-gbb20c45  r_flag
1.2.0-325-gbb20c45  r_core
1.2.0-325-gbb20c45  r_crypto
1.2.0-325-gbb20c45  r_bp
1.2.0-325-gbb20c45  r_debug
1.2.0-325-gbb20c45  r_hash
1.2.0-325-gbb20c45  r_fs
1.2.0-325-gbb20c45  r_io
1.2.0-325-gbb20c45  r_magic
1.2.0-325-gbb20c45  r_parse
1.2.0-325-gbb20c45  r_reg
1.2.0-325-gbb20c45  r_sign
1.2.0-325-gbb20c45  r_search
1.2.0-325-gbb20c45  r_syscall
1.2.0-325-gbb20c45  r_util
WARNING: r2 library versions mismatch!
```

So the libraries got updated, but the binary not, right?
Is this the expected result?

**Comment by Maijin** [comment]
`WARNING: r2 library versions mismatch! See r2 -V`

This means it's not correct, you are using old version of r2 with a new one -> Expect segfault and bugs. Clean everything and reinstall.

**Comment by radare** [comment]
You have an r2 in /usr/local and also in /usr

Ill make purge better to handle both.. use ldd r2 to see the libs your system is loading or use the rpath (see configue)

**Comment by radare** [comment]
Use `make purge2`

**Comment by PaquitoRiviera** [comment]
@Nevsor , @cym13 , @asutoshpalai 

Try deleting `libr/include/r_version.h`. The Makefile is missing a `.PHONY` target.

**Comment by radare** [comment]
Definitively no. Phony is not for this

**Comment by PaquitoRiviera** [comment]
`Definitively no. Phony is not for this`

I have no idea what makes you say that. For 2 years since 1306b87 it's been this way and everything worked until a month ago when you removed it in in 0a8dc8a. The Make manual explicitly states that PHONY targets are used for targets that should run unconditionally. So this is "Definitively", **Positively**, what PHONY targets are for.

If make doesn't want or can't generate the file (when compiling from a tarball, and no git), the target should run, detect that git isn't available and just do nothing. No idea where all the rest of this purge2 and double-install canards came from.

**Comment by radare** [comment]
its been like this for the ROOT makefile, which is not hte same thing that was two months ago that any make on any directory forced to recompile everything. if you build from scratch because you are a packager or a user with sys/install.sh all libraries will have the same versioning, so i dont see any problem with that because that only affects developers, because this file changes on every single commit, even the ones changing a comma in the readme

**Comment by PaquitoRiviera** [comment]
Ok, shorter compile cycles are a worthy goal. I get why you made that change.
What bother me is that it took this much discussion to learn that you made that decision. No one had any idea that or why you decided to make that compromise (faster compiles, stale version strings) because there was no pull request, no issue linked, no discussion, no code comment, no note to developers  (because there are no dev docs). 

And when 2 separate users (within weeks of the change) were impacted and reported it, it doesn't look like Maijin knew you made this change, nor did you seem to remember that you made this change, looking at the discussion. Otherwise, you'd have suggested the same workaround I ultimately did.
It's only when @asutoshpalai pointed out that just the banner is stale that I realized `r_version.h` isn't being updated. When I pointed this out, you blew me off without explanation of why this is the case. It took yet another round of comments to get you to finally reveal your reasons to the world. 

**Is this how a large open source project should work?**

If you had created an issue, either me or someone else might have suggested at least that `make clean` should remove r_version.h (it still doesn't).
Someone might have looked deeper and pointed out that the actual problem is not the updating r_version.h is too costly, but that r_version.h is included by too many files which don't need it. That this is a widespread problem in r2, and that @jvoisin pointed this to you [2 years ago](https://github.com/radare/radare2/issues/279#issuecomment-43000206). 

Then, you might have found that fixing THAT problem, instead of choosing a silly undocumented hack that changes long-standing behavior and surprises developers, will give you the same speedup in build time and keep the version up to date. It may take 10 minutes to do instead of 10 seconds, but it makes the project better, instead of worse.  

is this really THAT important? yes. because this whole thread is a classic example of the needless churn and technical debt building that is a daily occurrence in radare2, and created all the quality problems that currently plague it. 

It's time to grow up. You have thousands of users, you should give them quality software. Otherwise, you'll only continue to cultivate a mob of frustrated, angry users instead of a healthy FOSS community.

**Comment by radare** [comment]
> On 31 Mar 2017, at 23:43, PaquitoRiviera <notifications@github.com> wrote:
> 
> Ok, shorter compile cycles are a worthy goal. I get why you made that change.
> 

Its quite obvious. No need to explain that if you have a brain inside your head

> What bother me is that it took this much discussion to learn that you made that decision. No one had any idea that or why you decided to make that compromise (faster compiles, stale version strings) because there was no pull request, no issue linked, no discussion, no code comment, no note to developers (because there are no dev docs).
> 
None of this is needed to realize that if you type make twice without touching any file make takes 2 minutes to finish instead of 0.
> And when 2 separate users (within weeks of the change) were impacted and reported it, it doesn't look like Maijin knew you made this change, nor did you seem to remember that you made this change, looking at the discussion. Otherwise, you'd have suggested the same workaround I ultimately did.
> It's only when @asutoshpalai pointed out that just the banner is stale that I realized r_version.h isn't being updated. When I pointed this out, you blew me off without explanation of why this is the case. It took yet another round of comments to get you to finally reveal your reasons to the world.
> 

I still dont see any test case for this stupid issue that almost no one cares because it was not hurting anyone except devs reporting things because everyone else is using sys/install
> Is this how a large open source project should work?
> 
I have a live and certainly, burocracy is not one of my favourite hobbies
> If you had created an issue, either me or someone else might have suggested at least that make clean should remove r_version.h (it still doesn't).
> Someone might have looked deeper and pointed out that the actual problem is not the updating r_version.h is too costly, but that r_version.h is included by too many files which don't need it. That this is a widespread problem in r2, and that @jvoisin pointed this to you 2 years ago.
> 
Again. Too much discussion for something silly is a waste of time
> Then, you might have found that fixing THAT problem, instead of choosing a silly undocumented hack that changes long-standing behavior and surprises developers, will give you the same speedup in build time and keep the version up to date. It may take 10 minutes to do instead of 10 seconds, but it makes the project better, instead of worse.
> 
Not for devs
> is this really THAT important? yes. because this whole thread is a classic example of the needless churn and technical debt building that is a daily occurrence in radare2, and created all the quality problems that currently plague it.
> 
No, the whole thread evidences how some people gets obsessed with stupid problems that no one cares except you. And created a huge discussion thread just because you are not able to see beyond that and your litterary skills are clearly better than your technical or social ones.
> It's time to grow up. You have thousands of users, you should give them quality software. Otherwise, you'll only continue to cultivate a mob of frustrated, angry users instead of a healthy FOSS community.
> 

The only angry users are the ones that dont understand the work needed to maintain and develop this while being just a hobby project. If you have ever did any serious development lile u said in previous issues i would love to see them to understand better your background but i think that hiding behind a nickname is part of the game.

I agree that everything could be better, but discussing like this without any real work done is absolutely not the way to improve.

Good morning

**Comment by wargio** [comment]
Please stop this stupid discussion. It's useless to keep writing for this issue.
