### ISSUE TITLE
Please use travis to _avoid_ bad commits in master

### ISSUE THREAD

**Issue by PaquitoRiviera** [radare/radare2#6992]
![travis](https://cloud.githubusercontent.com/assets/26317705/23823938/1e453e64-0665-11e7-9df4-c73ac04c94c7.gif)

This plot shows the build status of the last 3000 commits or so to r2 master, top left (oldest) to bottom right (newest). Every block is a commit. Green for passed, red for fail, dark red for errored, grey for cancelled.  r2's never been great on this, but it has gotten much much worse in recent months. This image could pass for a dwarf fortress scene of frog genocide, given the right tileset.

**Comment by Maijin** [comment]
Something you forget is that, it's not because is red that the build failed. It only means the travis CI build fail, this build includes building the framework + the tests.
I control almost all outputs of travis-ci to determine the gravity of the regression if any and in many cases it appears the issue is caused by a test that need to be corrected.
I don't say the situation is perfect but this graph is not reflecting reality of the situation.

By the way any reason you are using an empty github account to report those issues ?

![image](https://cloud.githubusercontent.com/assets/1408600/23824545/c9de38e4-0678-11e7-88f0-42982efe4e4c.png)

**Comment by Maijin** [comment]
The reason why it was greener too at beginning is due to the fact that travis-CI was implemented differently too and also due to the increase number of tests which as explained before needs to be fixed time to time.

**Comment by Maijin** [comment]
If you want proper metrics on radare2 build failed/success you need to look at the following on the fail case:

* If the build time of "Linux GCC travis-ci" is less than 1min30 (shouldn't happen on master)
    * Then the tests couldn't take place because the PR has been merge before being retrieved, most of the time this is because the PR was typo fixed
* If the build time of  "Linux GCC travis-ci" is more than 1min30 but below 4 min 
    * Then radare2 build failed **<- Worst case**
* If the build time of  "Linux GCC travis-ci" is more than 4 min but fail 
     * Then the tests failed this can be due to tests failings

**Comment by radare** [comment]
I bet you are schumblub

**Comment by Maijin** [comment]
Nothing more to say here

**Comment by PaquitoRiviera** [comment]
> By the way any reason you are using an empty github account to report those issues ?

Do you see this issue as trolling??? yeah, I'm new here and maybe it's bad manners to start off with criticism, sorry for that. FWIW, It took me several hours to collect the this data and I honestly see this as an important issue to deal with. That's the only reason I opened this issue. 

> in many cases it appears the issue is caused by a test that need to be corrected.

I see, so CI is failing because of failing tests not compilation errors. How is that **not** a problem?

>    If the build time of "Linux GCC travis-ci" is less than 1min30 (shouldn't happen on master)
>        Then the tests couldn't take place because the PR has been merge before being retrieved, most 
>    If the build time of "Linux GCC travis-ci" is more than 1min30 but below 5 min
>        Then radare2 build failed <- Worst case

I believe both of these show up as the relatively few dark red blocks which indicate a failure during travis's build phase, instead of the testing phase. But my "question" is about the majority of commits which show up as bright red "Tests Failed".  Admittedly, haven't look at `.travis.yml` to confirm.

>    If the build time of "Linux GCC travis-ci" is more than 4 min but fail
>        Then the tests failed this can be due to tests failings

Right, and that's been the majority of commits for several months. The thing is, fixing a few tests won't really help as long as merging red commits is a standard practice. So this is about the broader issue of development practices, but I'm sure you know this already anyway. Why then does code that doesn't pass the tests get merged so regularly? 

FWIW, I'm not asking this to embarrass you guys but because it looks like a long-standing problem that looks like it's only getting worse over time. And one way to start fixing that is to initiate a discussion.  It's no fun dealing with the push-back from stakeholders, trust me, but for better or worse it's what I tend to do when I notice something wrong. See the issue I opened about the force-pushes to master, same thing exactly.

> I bet you are schumblub

???

> Nothing more to say here

Ok. I've said all I have to say about this too. I'm :disappointed: it's so unwelcome.

**Comment by Maijin** [comment]
"Why then does code that doesn't pass the tests get merged so regularly?"

If you want to help on fixing the tests when there are 300 tests failing because of stupid enhancement like tab output becoming spaces, you are more than welcome to assist me and the others.

Again, I'm checking what are the severity of the tests failings, IF they are not severe like stupid tabs instead of spaces, this can wait a bit... 

There is no real fix for that issue, that's why I closed it. The only thing that could be done is enhancing the metrics. I know you can retrieve time begin/time end in travis, but would cool to have a different status and a different color for build failed, and tests failed. I will look at this later except if you want to help ?
