### ISSUE TITLE
Search for read, write or exec references only

### ISSUE THREAD

**Issue by radare** [radare/radare2#7120]
/r and /R always search for refs, but doesnt care if its a read, write or exec one.

**Comment by radare** [comment]
i would go for /rw and /Rw... and the same goes for /rr and /rx.

**Comment by MaskRay** [comment]
This is tricky.

My plan:

* Fix #8189 - refactor search.c https://github.com/radare/radare2/pull/8195 i am annoyed this has been put off so long for some beauty issues and (i really hate unnecessary checks in function prologues) issue. This is correctness issue, I will not trust search results if this is not fixed.
* Wait for https://github.com/radare/radare2/pull/8402 Switch RIOMap interval type back to half-closed and fix #8388       , closed-interval is dumb.
* Use the code there https://github.com/radare/radare2/pull/8279#issuecomment-325170198
that is , an address-space-wraparound aware, RIOMap aware (knowing what is the current mapping and get the rwx permission) to build a generic r_io_read_at that also returns `RIOMap` being used. Hopefully this could return `st64/int` instead of `bool`. I really hate `bool` in this case.

**Comment by radare** [comment]
> On 4 Sep 2017, at 04:31, Fangrui Song <notifications@github.com> wrote:
> 
> This is tricky.
> 
> My plan:
> 
> Fix #8189 - refactor search.c #8195 i am annoyed this has been put off so long for some beauty issues and (i really hate unnecessary checks in function prologues) issue. This is correctness issue, I will not trust search results if this is not fixed.

There are still other issues in search, jot the one u fixed. Also, without having travis green i dont trust anything
> Wait for #8402 Switch RIOMap interval type back to half-closed and fix #8388 , closed-interval is dumb.
Yes i have no life, but my plan is to review and merge as much tings as possible, but dont want to break things or have to discuss things forever,
> Use the code there #8279 (comment)
> that is , an address-space-wraparound aware, RIOMap aware (knowing what is the current mapping and get the rwx permission) to build a generic r_io_read_at that also returns RIOMap being used. Hopefully this could return st64/int instead of bool. I really hate bool in this case.

Why do you need read with int here?, also if ioread is a wrapper on paddr and vaddr it shld be int, for consistency, otherwise the r3turn value of the pread will be lost

**Comment by condret** [comment]
@MaskRay What about instead of going for the halfclosed intervals, changing the rest of the codebase, so that it works with closed intervals.

**Comment by radare** [comment]
If we used the intervals api we can forget about this discussion. I think closed intervals are mathematically more correct. Because it allows to map a one byte page of 1 byte length at -1. But then size != to-from, which looks weird, but having an api to hide this we can change the thing with an ifdef if we want, but we will not have to care anymore about this

All structures having off + size shoukd be RInterval. Flags, maps, symbols, sections, ...

My 5c

**Comment by radare** [comment]
ping
