### ISSUE TITLE
Show human size in i

### ISSUE THREAD

**Issue by radare** [radare/radare2#7185]
```
[0x00000000]> i
file     8gb.dmg
fd       7
size     0x102700000
iorw     false
blksz    0x0
mode     -r--
block    0x100
format   any
```

**Comment by ITAYC0HEN** [comment]
It's a simple fix, just replacing with `r_num_units (NULL, fsz)`, will do it easy peasy but one question before:

How you want it to looks like?

1. Remove the hex size entirely
```
[0x00400490]> i
type     EXEC (Executable file)
file     example.bin
fd       6
size     8.4K
iorw     false
blksz    0x0
```

2. Adding 'human size' on a new line while keeping the full-hex-size
```
[0x00400490]> i
type     EXEC (Executable file)
file     example.bin
fd       6
humansz  8.4K
size     0x2198
iorw     false
blksz    0x0
```

3. Adding the human size or the hex-size between brackets
```
[0x00400490]> i
type     EXEC (Executable file)
file     example.bin
fd       6
size     0x2198 (8.4K)
iorw     false
blksz    0x0
```

The full hex-size is more accurate and usable in some cases so I believe we should keep it in some way.

Option 3 is my favorite but I don't like to think that someone would need to use string manipulation in order to retrieve only the human-size or only the hex-size while scripting. Another option is to show the human-size when executing `i` and the hex-size when executing `ij` but I don't think the results should be different between the two commands.

What do you think will be the best solution?

**Comment by radare** [comment]
Use option 2
