### ISSUE TITLE
Write assembly not working for ARM/thumb

### ISSUE THREAD

**Issue by zaweke** [radare/radare2#7344]
I am trying to modify the call target of the following instruction (to sym.minar::Scheduler::postCallback) .

0x000036d2      01f087fa       bl sym.minar::Scheduler::start

I tried **wa bl sym.minar::Scheduler::postCallback @0x000036d2**
r2 reports that 4 bytes are written, but I don't see any changes. Am I missing something?

**Comment by radare** [comment]
My guessis that you should be using -B to rebase to a higher address to avoid pa/va overlap. This is fixed in the siol branch, but you write address seems low enough

You can use pa instead of wa to see the bytes that should be written.

In case of writingthe wrong offset use the number instead of the flagname.

Also i assume you are using the latest r2 from git

**Comment by zaweke** [comment]
Rebasing  to a higher address and using a number instead of the symbol name seems to work. 
Thank you!
