### ISSUE TITLE
~str~? not working

### ISSUE THREAD

**Issue by radare** [radare/radare2#7373]
should do the same as ~?str

**Comment by prashast** [comment]
Can you point me to where in the codebase this functionality is implemented so that I can rectify this?

**Comment by qrux0** [comment]
Hello, @prashast 

At libr/core/cmd.c:1863 *r_core_cmd_subst_i* function checks for '~' and creates buffer for filtering with *r_cons_grep* (libr/cons/grep.c:53) which is used by *r_cons_grepbuf* after command execution.

Really this issue is not just about **\~str\~?**, any command with 2+ internal grep expressions works wrong.

**Comment by qrux0** [comment]
@radare, correct me if I am wrong.

This issue is not just about **\~str\~?**, any command with 2+ internal grep expressions produce unexpected output.
To solve this issue we need to add stack of RConsGrep structures into RCons for multiple filter usage?

**Comment by radare** [comment]
the thing is that r2 parsing doesnt handles more than one rconsgrep filtering, so what this should be doing is just modify the same instance of rconsgrep to get the same as `~?str`
