### ISSUE TITLE
Fix handling (show in disasm) of imports and relocations

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#755]
See https://github.com/radare/radare2/commit/b4f1cd220f738a7a6b494c5a883c0065ffc26a3e

**Comment by radare** [comment]
iirc relocs are already shown in disasm, not modying memory, but works more or less fine. can anyone confirm?

**Comment by radare** [comment]
what about this?

**Comment by Maijin** [comment]
Imports should be handled in the disassebly using flags. All the imports, symbols, relocs are imported as flags when loading the file. this is how actually works, and it should be working already, if not, that’s a bug, not a missing feature.

The current problems are:
- flags can have collisions (two files with same symbols loaded)
- flags should be reimplemented using Sdb
- symbol names are ‘mangled’ to be valid flag names, which makes some symbolnames to be destroyed

The plans for this are the following:
- Use Sdb in RBin to export all bin info using sdb, so instead of O(n) you get O(1) to get a symbol for a given address
- We need to handle the following situations
  - More than one file opened
  - More than one flag with the same name (already supported right now iirc), but problematic
  - Handle debug information too (memory maps, registers)
  - Handle All RBin information (headers, sections, symbols, relocs, …)

**Comment by radare** [comment]
there are issues already opened for all those points, can we close this issue?
