### ISSUE TITLE
anal.noncode is not respected

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#7613]
Following the new broken tests for anal.calls/anal.noncode -> https://github.com/radare/radare2-regressions/commit/8a22c7323815c85fd7e07230924e461f21aa2ab1 .

![image](https://cloud.githubusercontent.com/assets/1408600/26532220/21f6641a-43fb-11e7-9786-5ef93923ef70.png)

**Comment by sivaramaaa** [comment]
hey hi , looked into the this issue  and in r_core_anal_fcn() there is a check made which honors anal.noncode
```
if (!r_io_is_valid_offset (core->io, at, !core->anal->opt.noncode)) {

                      return false;
}
```
but the issue here is say the addr 0x100004b68  (str.Unix2003) contains string and it is non-exec region , but r_io_is_valid_offset() method is detecting it as exec region !!

I would like to get some suggestions here !!!

**Comment by radare** [comment]
Then its a bug :D can u fix it?

**Comment by Maijin** [comment]
@radare see the PR

**Comment by sivaramaaa** [comment]
Yeah it may be a bug in  r_io_is_valid_offset() , but i think i have fixed the regression and i have submitted the [PR](https://github.com/radare/radare2/pull/8968)
