### ISSUE TITLE
feature request: print equivalent in gdb

### ISSUE THREAD

**Issue by akowz87** [radare/radare2#7658]
Hey
When a binary is loaded in r2 i can't get address of function from libc (i must open libc in radare2 separately).
please provid print equivalent in gdb something like this:
`gdb-peda$ print system`
`$1 = {<text variable, no debug info>} 0x7ffff7a7a450 <__libc_system>`
<img width="486" alt="screen shot 2017-06-02 at 14 21 40" src="https://cloud.githubusercontent.com/assets/29142565/26720846/e6fa5798-479e-11e7-92e2-4b9859563826.png">
when i uses e anal.from and anal.to with libc address it can not resolve function names with afl.
tnq <#

**Comment by radare** [comment]
yes you can , but its not loaded by default because r2 is a low level debugger and gives you the option to do that if you want, not like gdb that takes half a minute to load because it needs to parse all the libraries at attach time.

use the dmi command to resolve symbols from libraries.

there are other ways to do that, but this is probably the simplest

**Comment by akowz87** [comment]
@radare : dmi can not do it !
for example i wanted get system from libc but that was not present there.
i shows this problem in a video : https://asciinema.org/a/a3lzb4pxuskpidvxzmwmntayj

**Comment by radare** [comment]
dmi libc system

If you dont soecify which library will show the symbils of the main executable
