### ISSUE TITLE
afu command not properly updating function end address in obfuscated PE file

### ISSUE THREAD

**Issue by Oldetymer** [radare/radare2#7715]
Fairly new to using radare, so hopefully I'm not misunderstanding the command. 

I have a piece of obfuscated code from a Windows DLL that is using push-ret, and jumps into the middle of instructions to obfuscate the control flow. The function starting at RVA 0x15A0, and should end at RVA 0x1AED, however the analysis engine has the function ending early at RVA 0x1A63 (a size of 1216 bytes).

<img width="396" alt="screen shot 2017-06-09 at 3 30 46 pm" src="https://user-images.githubusercontent.com/29313221/26992056-ec232484-4d2a-11e7-8bee-95ddf5047c0b.png">

I'm attempting to use afu to extend the function. Instead the afu instruction extends the flag associated with the function name, but doesn't change the bounds of the function.

<img width="467" alt="screen shot 2017-06-09 at 3 35 18 pm" src="https://user-images.githubusercontent.com/29313221/26992117-24f1331e-4d2b-11e7-86e3-a5a222c1c672.png">

Is this the intended behavior? Is there another way to manually define the end address of a function? If necessary I can generate a code excerpt that will cause the issue.

**Comment by xambroz** [comment]
Same story on linux. I have got function which has got "jmp rax" in the middle. The "aaa" ends this function with this "jmp rax" on main + 111.

I have tried to extend the end of the function and re-analyze, but moving the end of function with "afu main + 772" moved only the size, but the realsz remained the same.
The "pdf" now prints whole function as expected, but still the rest of the function is not reanalyzed and for example the local variables are not translated from "rbp - 0x54" to for example "local_54_password".

**Comment by Maijin** [comment]
for pushret you can use > e anal.pushret = true

**Comment by Maijin** [comment]
Did you try the proposed solution ping 1

**Comment by Maijin** [comment]
No answer since 12 August. Closing

**Comment by xambroz** [comment]
Actually it seems that afu can make function shorter but not bigger than already analyzed.

See this (benign, but potentially malicious) example - 1be43b8a34a908b2916a82ca715ebb9b_Project1.zip (password infected):
[1be43b8a34a908b2916a82ca715ebb9b_Project1.zip](https://github.com/radare/radare2/files/3583046/1be43b8a34a908b2916a82ca715ebb9b_Project1.zip)

The entry0 function gets analyzed longer than it actually is. The function entry0 is the standard VB stub which passes the address of the VB5 control structure (0x40126c) to the VB main function sub.MSVBVM60.DLL_ThunRTMain but doesn't expect to return back.

```
radare2 Project1.exe
[0x00401130]> s entry0
[0x00401130]> aF @entry0
[0x00401130]> pdf @entry0
┌ (fcn) entry0 82
│   entry0 ();
│           0x00401130      686c124000     push 0x40126c
│           0x00401135      e8eeffffff     call sub.MSVBVM60.DLL_ThunRTMain
│           0x0040113a      0000           add byte [eax], al
│           0x0040113c      0000           add byte [eax], al
...
└       │   0x00401181      cc             int3

```

You can make the function shorter with afu. Both size and realsz gets updated to be shorted and pdf works as instructed (except I by mistake used end address 0x00401135 instead of 0x0040113a):

```
[0x00401130]> afu 0x00401135 @entry0
[0x00401130]> pdf
┌ (fcn) entry0 5
│   entry0 ();
└           0x00401130      686c124000     push 0x40126c
[0x00401130]> afi
#
offset: 0x00401130
name: entry0
size: 5
is-pure: false
realsz: 5
stackframe: 12
call-convention: cdecl
cyclomatic-cost : 1
cyclomatic-complexity: 1
bits: 32
type: fcn [NEW]
num-bbs: 1
edges: 0
end-bbs: 1
call-refs: 0x00401128 C
data-refs: 0x0040126c
code-xrefs:
in-degree: 0
out-degree: 1
data-xrefs:
locals: 0
args: 0
diff: type: new
```

This was mistake and I want to make the function bigger - having the 2 opcodes = push + call. But using "afu" you can't make it back bigger. When making the function bigger it only changes "size", but not the "realsz". You can recognize it from the asciiart around function that the function is ending with the ".." and not with the "└", but that's all it changed:

```
[0x00401130]> afu 0x0040113a @entry0
[0x00401130]> pdf
┌ (fcn) entry0 5
│   entry0 ();
│           0x00401130      686c124000     push 0x40126c
..
[0x00401130]> afi
#
offset: 0x00401130
name: entry0
size: 10
is-pure: false
realsz: 5
stackframe: 12
call-convention: cdecl
cyclomatic-cost : 1
cyclomatic-complexity: 1
bits: 32
type: fcn [NEW]
num-bbs: 1
edges: 0
end-bbs: 1
call-refs: 0x00401128 C 0x004011de J
data-refs: 0x0040126c
code-xrefs:
in-degree: 0
out-degree: 1
data-xrefs:
locals: 0
args: 0
diff: type: new
```

The only work-around seems to be delete the function analysis data for this function and start from beginning:

```
[0x00401130]> af- entry0
[0x00401130]> afu 0x0040113a
[0x00401130]> pdf
┌ (fcn) entry0 10
│   entry0 ();
│           0x00401130      686c124000     push 0x40126c
└           0x00401135      e8eeffffff     call sub.MSVBVM60.DLL_ThunRTMain
[0x00401130]> afi
#
offset: 0x00401130
name: entry0
size: 10
is-pure: false
realsz: 10
stackframe: 0
call-convention: cdecl
cyclomatic-cost : 4
cyclomatic-complexity: 1
bits: 32
type: fcn [NEW]
num-bbs: 1
edges: 0
end-bbs: 1
call-refs: 0x00401128 C
data-refs: 0x0040126c
code-xrefs:
in-degree: 0
out-degree: 1
data-xrefs:
locals: 0
args: 0
diff: type: new
```

**Comment by xambroz** [comment]
> e anal.pushret = true

Usage of "e anal.pushret = true" is not changing the possibility to make functions bigger than already analyzed.

**Comment by Maijin** [comment]
@xambroz please open a new issue, this issue is 2 years old.
