### ISSUE TITLE
Fix the completion hints

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#8033]
- [ ] Rename it to `cfg.comphint`
 - [ ] Fix the regression tests for Travis
 - [ ] Fix the crashes and related memleaks

@MaskRay this is your part it seems.

**Comment by radare** [comment]
no regressions happened in travis because of this refactoring

the problem is that the initialization code that parses all the help messages is crap and have several issues:

* overflow
* slow startup
* fixed number of commands
* not using any r2 datastructure (qsort, raw arrays, ..)

i have commented out the code that was causing those issues, the idea of having an option was to not interfere with the rest of the logic in r2, so no crashes and such :D

**Comment by MaskRay** [comment]
Is this resolved?

**Comment by radare** [comment]
Yeah must improve but yep
