### ISSUE TITLE
break on install at Samsung Galaxy s7 (rooted) 

### ISSUE THREAD

**Issue by n82freak** [radare/radare2#8887]
on install break & stop 
tried to build with aide - there is 1 bug - so I cant build.
tried to repair the bug - build the installer but break always on install

**Comment by XVilka** [comment]
build log please

On Nov 26, 2017 2:19 PM, "n82freak" <notifications@github.com> wrote:

on install break & stop
tried to build with aide - there is 1 bug - so I cant build.
tried to repair the bug - build the installer but break always on install

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/radare/radare2/issues/8887>, or mute the thread

**Comment by n82freak** [comment]
Ich am not shure but aida didnt log on build...

**Comment by Maijin** [comment]
Try with termux package.

**Comment by radare** [comment]
The r2 installer is not updated and github changed the ssl certificate so it fails at cert pining. Will update soon or late but recommended way is termux

**Comment by n82freak** [comment]
I tried now for 3 or 4 hours ! pls make a funktional apk for mobile.
those what can ready download have script bug - same if i build by my self . then i fix the script bug but it does the same break on install again & again.
that wasted a lot of time 4 me know !

**Comment by radare** [comment]
Just use termux its way better than embedding a terminal in a dummy app

But ill try to push an update of the app fixing the issue and a button to open termux in the appstore

**Comment by n82freak** [comment]
I never used the Stock-Terminal.  

I have Termius  & Termin and the regular adb via PC...

**Comment by n82freak** [comment]
Termin should be termux - crap t9

**Comment by radare** [comment]
I have pushed radare2-installer 2.9 to the playstore. It should work fine now after the updated github cert

**Comment by n82freak** [comment]
this works fine 4 me ! thats it ! 5stars in Google!!! 

thx a lot...
