### ISSUE TITLE
agj/aoj is missing resolution

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#8998]
Forwarded from Cutter

![image](https://user-images.githubusercontent.com/1408600/33804593-86ce3ff6-dda8-11e7-9d84-a88385931b49.png)

![image](https://user-images.githubusercontent.com/1408600/33804596-8c64d362-dda8-11e7-8245-b15e8fc230f4.png)

![image](https://user-images.githubusercontent.com/1408600/33804600-a196cf10-dda8-11e7-8d56-5ac9aa66ee1f.png)

**Comment by wargio** [comment]
i had the same issue with r2dec.
my fix was searching for xrefs manually.

**Comment by radare** [comment]
can i have a sample and a testcase? not just screenshots?

**Comment by radare** [comment]
HELLO

**Comment by Maijin** [comment]
? All binaries have this issue - https://github.com/radare/radare2-regressions/blob/master/bins/elf/arm1.bin

at 0x0005cd88 for example

**Comment by radare** [comment]
thats also missing in aoj

**Comment by radare** [comment]
There's a "problem" here.. i have extended this json to contain a "disasm" field with the filtered/varsub/relsubbed string. The problem here is that we need to redesign asm/anal/parse into a proper way.. i'll think on this during those days and plan a proper strategy to cleanup and unify those APIs, or at least create a proper workflow to avoid multiple passes and correct pipelineing and data extraction from each instruction at binary and string level.

To make this clear: the problem we are facing here is that in disasm.c we handle things like this:

- ldr r0, [pc, 33]    -> ldr r0,[0x8048033] (relsub)
- load the dword in this address and resolve the (ptrsub)
- replace the address with a meaningful flag (varsub)

the relsub address is available in analop.ptr, but it's up to the user to read the dword in that place and resolve the pointer in there. doing recursive analysis on data references is dangerous and have a performance cost, so we need to be clear on that to avoid overloading the analysis

**Comment by radare** [comment]
So this issue is fixed now. but other cases it may not be ready yet

**Comment by radare** [comment]
<img width="1052" alt="screen shot 2017-12-22 at 13 30 01" src="https://user-images.githubusercontent.com/917142/34298103-452a103e-e71c-11e7-8384-a8d6f04ea4fd.png">
