### ISSUE TITLE
VV Graph inside Panels view?

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#9721]
Is it possible to put the Very Visual view inside the panels view? Primarily, I would find it helpful to be able to graphically step through a program (how VV does today), but with the added context of being able to watch the registers change or other enhancing information.

**Comment by radare** [comment]
VV is graph view, is this what u mean?

**Comment by bannsec** [comment]
So i mean, inside the `V!` view, on the left, i see a disassembly view of the program. I'd like to be able to switch that view out for the view i get with "VV". Meaning, I can see "VV" on the left as well as panels around it.

**Comment by radare** [comment]
there are some things to solve and refactor in panels to get this working because it requires the canvas to not be cropped at first and not updated unless seek changes, thats why its not in there and thats why jumping into graph mode from panels results in full interactive graph view and not in a frame.

**Comment by radare** [comment]
cc @Vane11ope

**Comment by bokoloc** [comment]
This would be super useful

**Comment by Vane11ope** [comment]
sorry i've not been aware of this suggestion.

i've been on adding some other useful function to V! right now. however, i think that's a nice feature to add so let me take a look and see what i can do :)

**Comment by XVilka** [comment]
@Vane11ope can be closed now, right?

**Comment by radare** [comment]
yes
