### ISSUE TITLE
`agft` is broken

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#9962]
Check on any single function.

@cyanpencil see this please too.

**Comment by cyanpencil** [comment]
@XVilka, are you referring to the fact that it only prints the tiny graph for the function in the current seek, and not the function provided in the argument? 
(example: `agft` and `agft sym.xxx` are the same because the argument is ignored)

**Comment by cyanpencil** [comment]
Since I wasn't able to find the source of this bug I manually binary-serched on the commit history to see when it was introduced.

I found out that tiny graph edges were broken since the very commit that introduced them.
In particular, in commit [b49314a94](https://github.com/radare/radare2/commit/b49314a94b5ca94cfe83e05dd90c4e0a19fe5bbf) we can see they were introduced because in line 3052 in file graph.c the following `if` was commented out:
```
// TODO: add an option/key to toggle this
if (!g->is_tiny) {
		agraph_print_edges (g);
}
```

Before that commit, the tiny graph was rendered without edges, like this:
![2018-05-01-004143_652x275_scrot](https://user-images.githubusercontent.com/3428362/39453882-6ed8ef32-4cd8-11e8-82d3-44c656772ee4.png)

And this is the same function just after that commit:
![2018-05-01-004534_655x380_scrot](https://user-images.githubusercontent.com/3428362/39453982-ff14e858-4cd8-11e8-84b4-dd0769203880.png)


So this makes me think that tiny graph edges were never meant to be in the first place...
Please @radare correct me if I'm wrong

**Comment by radare** [comment]
Press the e key to toggle edges

**Comment by cyanpencil** [comment]
Thank you for your answer @radare , but I think I didn't formulate well the question.

The problem is that `graph.edges = 2` by default, so that we the `agft` command is ran, the broken edges of the tiny graph are shown by default.

My question is then: should the graph edges be disabled when running `agft` (and, more in general, when displaying the tiny graph) unless specified by the user?

**Comment by radare** [comment]
act as a minigraph?

next step was to show it in a corner when scrolling a huge graph (or in panels)
