### ISSUE TITLE
Deprecate the `anal.bb.*` variables

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#9965]
Just kill them.

**Comment by sivaramaaa** [comment]
Basically there are 3 variables under `anal.bb.*`

```
anal.bb.align     anal.bb.maxsize   anal.bb.split
```
anal.bb.maxsize cannot be killed at the moment coz u need to change this value for binaries with larger basic block size , almost all analysis modules use this size 

But once this issue is fixed https://github.com/radare/radare2/issues/9564 , we could then kill anal.bb.maxsize

i don't know about the rest of 2 variables

**Comment by radare** [comment]
we killed anal.bb.splt, and we will kill more after release

**Comment by sivaramaaa** [comment]
Closing this issue , since only `anal.bb.maxsize` is left to kill , and we already have a issue to track that !
